module.exports = [
  { topic: "Nouns (នាម)", questions: [
    { q: "Which word is a noun?", c: ["A) quickly", "B) beautiful", "C) doctor", "D) run"], a: "C" },
    { q: "Which is NOT a noun?", c: ["A) table", "B) love", "C) Paris", "D) happy"], a: "D" },
    { q: "Which is a proper noun?", c: ["A) city", "B) Cambodia", "C) river", "D) school"], a: "B" },
    { q: "Which is an abstract noun?", c: ["A) dog", "B) car", "C) freedom", "D) apple"], a: "C" },
    { q: "Which is a collective noun?", c: ["A) sheep", "B) water", "C) team", "D) run"], a: "C" },
    { q: "ពាក្យ 'book' ជានោមមុខប្រភេទណា?", c: ["A) Abstract noun", "B) Proper noun", "C) Concrete noun", "D) Collective noun"], a: "C" },
    { q: "ពាក្យ 'Cambodia' ជានោមប្រភេទណា?", c: ["A) Common noun", "B) Proper noun", "C) Abstract noun", "D) Collective noun"], a: "B" },
    { q: "ពាក្យ 'joy' ជានោមប្រភេទណា?", c: ["A) Concrete noun", "B) Proper noun", "C) Abstract noun", "D) Collective noun"], a: "C" },
    { q: "Which sentence uses a noun correctly?", c: ["A) She runs fast.", "B) He is tall.", "C) I have a pen.", "D) They look happy."], a: "C" },
    { q: "What type of noun is 'class'?", c: ["A) Abstract", "B) Proper", "C) Collective", "D) None"], a: "C" }
  ]},
  { topic: "Plural Nouns (នាមពហុវចនៈ)", questions: [
    { q: "What is the plural of 'cat'?", c: ["A) cates", "B) cats", "C) catses", "D) catis"], a: "B" },
    { q: "What is the plural of 'box'?", c: ["A) boxs", "B) boxi", "C) boxes", "D) boxies"], a: "C" },
    { q: "What is the plural of 'child'?", c: ["A) childs", "B) childes", "C) childrens", "D) children"], a: "D" },
    { q: "What is the plural of 'man'?", c: ["A) mans", "B) men", "C) manes", "D) manie"], a: "B" },
    { q: "What is the plural of 'city'?", c: ["A) citys", "B) cityes", "C) cities", "D) citie"], a: "C" },
    { q: "Which plural is INCORRECT?", c: ["A) dogs", "B) buses", "C) tomatoes", "D) childs"], a: "D" },
    { q: "What is the plural of 'knife'?", c: ["A) knifes", "B) knives", "C) knifves", "D) knif"], a: "B" },
    { q: "What is the plural of 'mouse'?", c: ["A) mouses", "B) moose", "C) mice", "D) mouse"], a: "C" },
    { q: "ពាក្យ 'church' ក្នុងទម្រង់ពហុវចនៈគឺ?", c: ["A) churchs", "B) churches", "C) churchies", "D) church"], a: "B" },
    { q: "ពាក្យ 'baby' ក្នុងទម្រង់ពហុវចនៈគឺ?", c: ["A) babys", "B) babyes", "C) babies", "D) baby"], a: "C" }
  ]},
  { topic: "Uncountable Nouns (នាមរាប់មិនបាន)", questions: [
    { q: "Which is an uncountable noun?", c: ["A) book", "B) water", "C) car", "D) apple"], a: "B" },
    { q: "Which is countable?", c: ["A) milk", "B) sugar", "C) cat", "D) rice"], a: "C" },
    { q: "Which sentence is correct?", c: ["A) I want two rices.", "B) I want two rice.", "C) I want some rice.", "D) I want a rices."], a: "C" },
    { q: "Which is uncountable?", c: ["A) pencil", "B) chair", "C) love", "D) hat"], a: "C" },
    { q: "We use ___ before uncountable nouns.", c: ["A) a / an", "B) two / three", "C) some / much", "D) many / few"], a: "C" },
    { q: "Which word goes with uncountable?", c: ["A) many", "B) few", "C) several", "D) much"], a: "D" },
    { q: "ពាក្យ 'money' ជានោមប្រភេទណា?", c: ["A) Countable", "B) Uncountable", "C) Plural", "D) Proper"], a: "B" },
    { q: "ពាក្យ 'information' ជានោមប្រភេទណា?", c: ["A) Countable", "B) Collective", "C) Uncountable", "D) Proper"], a: "C" },
    { q: "Which is WRONG?", c: ["A) much water", "B) some milk", "C) many advices", "D) little sugar"], a: "C" },
    { q: "'I need ___ advice.' Fill in the blank.", c: ["A) an", "B) a", "C) some", "D) many"], a: "C" }
  ]},
  { topic: "Possessive Nouns (នាមកម្មសិទ្ធិ)", questions: [
    { q: "Which shows possession correctly?", c: ["A) the dog tail", "B) the dogs tail", "C) the dog's tail", "D) the tail dog"], a: "C" },
    { q: "Tom has a book. = ___", c: ["A) Tom book", "B) Tom's book", "C) Toms book", "D) Toms' book"], a: "B" },
    { q: "Two girls own a bag. = ___", c: ["A) the girl's bag", "B) the girls bag", "C) the girls' bag", "D) girls's bag"], a: "C" },
    { q: "Where does the apostrophe go for plural?", c: ["A) Before s: dog's", "B) After s: dogs'", "C) No apostrophe", "D) Both A and B"], a: "B" },
    { q: "Which is CORRECT?", c: ["A) the childrens' toys", "B) the childrens toys", "C) the children's toys", "D) the childrens's toys"], a: "C" },
    { q: "'The cat ___ food is on the table.' Fill in.", c: ["A) 's", "B) s'", "C) s's", "D) '"], a: "A" },
    { q: "ការប្រើ 's ក្នុងភាសាអង់គ្លេស មានន័យថា?", c: ["A) ពហុវចនៈ", "B) ភ្ជាប់ V", "C) ការចង់", "D) កម្មសិទ្ធិ"], a: "D" },
    { q: "Which is WRONG?", c: ["A) John's car", "B) Mary's pen", "C) the teacher's desk", "D) the students's work"], a: "D" },
    { q: "The house of my father = ___", c: ["A) My father house", "B) My fathers' house", "C) My father's house", "D) My father house's"], a: "C" },
    { q: "James has a computer. = ___", c: ["A) James computer", "B) James's computer", "C) Jame's computer", "D) James' computer"], a: "B" }
  ]},
  { topic: "Compound Nouns (នាមសមាស)", questions: [
    { q: "Which is a compound noun?", c: ["A) beautiful", "B) toothbrush", "C) quickly", "D) happy"], a: "B" },
    { q: "tooth + brush = ?", c: ["A) toothbrush", "B) tooth brush", "C) brushooth", "D) toothes"], a: "A" },
    { q: "What does 'schoolbag' mean in Khmer?", c: ["A) ថ្នាក់រៀន", "B) កាបូបស្ពាយ", "C) ស្ពៃ", "D) ប័ណ្ណ"], a: "B" },
    { q: "Which is NOT a compound noun?", c: ["A) football", "B) sunflower", "C) birthday", "D) running"], a: "D" },
    { q: "fire + man = ?", c: ["A) manfire", "B) fireman", "C) firemen", "D) fire-men"], a: "B" },
    { q: "'Bedroom' is a compound noun made of?", c: ["A) bed + room", "B) be + droom", "C) bedr + oom", "D) b + edroom"], a: "A" },
    { q: "Which compound noun means 'ល្ហម'?", c: ["A) lighthouse", "B) blackboard", "C) sunrise", "D) waterfall"], a: "D" },
    { q: "Which is correct?", c: ["A) raincoat", "B) raincoating", "C) coatrain", "D) raincoated"], a: "A" },
    { q: "sun + flower = ?", c: ["A) flowerun", "B) sunnflower", "C) sunflower", "D) sun-flower"], a: "C" },
    { q: "ពាក្យ 'homework' ប្រែជាភាសាខ្មែរថា?", c: ["A) ផ្ទះ", "B) ការងារ", "C) កិច្ចការផ្ទះ", "D) ធ្វើការ"], a: "C" }
  ]},
  { topic: "Adjectives (គុណនាម)", questions: [
    { q: "Which word is an adjective?", c: ["A) quickly", "B) run", "C) beautiful", "D) table"], a: "C" },
    { q: "Which sentence has an adjective?", c: ["A) She runs.", "B) He ate.", "C) It is hot.", "D) They go."], a: "C" },
    { q: "Adjectives usually come ___ nouns.", c: ["A) after", "B) before", "C) inside", "D) without"], a: "B" },
    { q: "'A big house.' The adjective is?", c: ["A) A", "B) big", "C) house", "D) a big"], a: "B" },
    { q: "Which is NOT an adjective?", c: ["A) tall", "B) happy", "C) table", "D) cold"], a: "C" },
    { q: "ពាក្យ 'beautiful' ប្រែជាខ្មែរថា?", c: ["A) ល្អ", "B) ធំ", "C) ស្រស់ស្អាត", "D) លឿន"], a: "C" },
    { q: "Choose the correct sentence.", c: ["A) She is a doctor kind.", "B) She is a kind doctor.", "C) Kind a doctor she is.", "D) A she kind doctor."], a: "B" },
    { q: "Which adjective means ខ្លី?", c: ["A) long", "B) tall", "C) short", "D) small"], a: "C" },
    { q: "Which is the opposite of 'new'?", c: ["A) young", "B) tall", "C) fast", "D) old"], a: "D" },
    { q: "'The ___ dog is friendly.' Fill in.", c: ["A) quickly", "B) run", "C) black", "D) bark"], a: "C" }
  ]},
  { topic: "Comparative Adjectives (គុណនាមប្រៀបធៀប)", questions: [
    { q: "How do we form comparative for short adjectives?", c: ["A) more + adj", "B) adj + er", "C) adj + est", "D) most + adj"], a: "B" },
    { q: "What is the comparative of 'big'?", c: ["A) more big", "B) bigger", "C) biggest", "D) bigest"], a: "B" },
    { q: "What is the comparative of 'beautiful'?", c: ["A) beautifuler", "B) more beautifuler", "C) more beautiful", "D) beautifulest"], a: "C" },
    { q: "Fill in: 'She is ___ than her sister.'", c: ["A) tall", "B) more tall", "C) taller", "D) tallest"], a: "C" },
    { q: "Which is CORRECT?", c: ["A) He is more tall.", "B) He is taller.", "C) He is tallmore.", "D) He is tall more."], a: "B" },
    { q: "What is the comparative of 'good'?", c: ["A) gooder", "B) goodest", "C) more good", "D) better"], a: "D" },
    { q: "What is the comparative of 'bad'?", c: ["A) badder", "B) worse", "C) more bad", "D) baddest"], a: "B" },
    { q: "ការប្រៀបធៀប 'ធំជាង' = ___", c: ["A) biggest", "B) bigger", "C) big", "D) more big"], a: "B" },
    { q: "Which sentence is CORRECT?", c: ["A) This book is more cheap.", "B) This book is cheaper.", "C) This book is cheapest.", "D) This book is more cheaper."], a: "B" },
    { q: "Comparative uses ___ to compare.", c: ["A) one thing", "B) three things", "C) two things", "D) all things"], a: "C" }
  ]},
  { topic: "Superlative Adjectives (គុណនាមបំផុត)", questions: [
    { q: "How do we form superlative for short adjectives?", c: ["A) more + adj", "B) adj + er", "C) the + adj + est", "D) most + adj"], a: "C" },
    { q: "What is the superlative of 'tall'?", c: ["A) taller", "B) more tall", "C) the tallest", "D) most tall"], a: "C" },
    { q: "What is the superlative of 'beautiful'?", c: ["A) beautifulest", "B) the most beautiful", "C) more beautiful", "D) the beautifulest"], a: "B" },
    { q: "What is the superlative of 'good'?", c: ["A) the goodest", "B) the better", "C) the best", "D) gooderest"], a: "C" },
    { q: "What is the superlative of 'bad'?", c: ["A) the baddest", "B) the worst", "C) the badest", "D) the worser"], a: "B" },
    { q: "Fill in: 'He is ___ student in the class.'", c: ["A) the smarter", "B) smart", "C) smarter", "D) the smartest"], a: "D" },
    { q: "Which is WRONG?", c: ["A) the biggest", "B) the most expensive", "C) the most tallest", "D) the cheapest"], a: "C" },
    { q: "Superlative compares ___ things.", c: ["A) two", "B) three or more", "C) one", "D) zero"], a: "B" },
    { q: "ពាក្យ 'the best' ប្រែជាខ្មែរថា?", c: ["A) ល្អជាង", "B) ល្អ", "C) ល្អជាងគេ", "D) ល្អបំផុត"], a: "D" },
    { q: "We always use ___ before superlative adjectives.", c: ["A) a", "B) an", "C) the", "D) some"], a: "C" }
  ]},
  { topic: "Personal Pronouns (សព្វនាមបុគ្គល)", questions: [
    { q: "Which is a subject pronoun?", c: ["A) me", "B) him", "C) she", "D) us"], a: "C" },
    { q: "What is the subject pronoun for a male?", c: ["A) her", "B) him", "C) he", "D) his"], a: "C" },
    { q: "Fill in: '___ am a student.'", c: ["A) Me", "B) My", "C) I", "D) Mine"], a: "C" },
    { q: "Which pronoun replaces 'John and Mary'?", c: ["A) he", "B) she", "C) they", "D) we"], a: "C" },
    { q: "ពាក្យ 'We' ប្រែជាខ្មែរថា?", c: ["A) ខ្ញុំ", "B) ពួកយើង", "C) ពួកគេ", "D) អ្នក"], a: "B" },
    { q: "Which pronoun replaces a thing?", c: ["A) he", "B) she", "C) they", "D) it"], a: "D" },
    { q: "Fill in: '___ are my friends.'", c: ["A) Him", "B) Them", "C) They", "D) Us"], a: "C" },
    { q: "ពាក្យ 'You' ប្រើជំនួសសម្រាប់?", c: ["A) ខ្ញុំ", "B) ពួកគេ", "C) អ្នក/ពួកអ្នក", "D) គាត់"], a: "C" },
    { q: "Which is WRONG? Fill: '___ is a good teacher.'", c: ["A) He", "B) She", "C) It", "D) Them"], a: "D" },
    { q: "Subject pronouns come ___ the verb.", c: ["A) after", "B) before", "C) inside", "D) without"], a: "B" }
  ]},
  { topic: "Object Pronouns (សព្វនាមកម្មបទ)", questions: [
    { q: "Which is an object pronoun?", c: ["A) I", "B) he", "C) him", "D) she"], a: "C" },
    { q: "Fill in: 'She loves ___.' (referring to me)", c: ["A) I", "B) my", "C) me", "D) mine"], a: "C" },
    { q: "Object pronoun for 'she' is?", c: ["A) her", "B) she", "C) hers", "D) him"], a: "A" },
    { q: "Object pronoun for 'they' is?", c: ["A) their", "B) theirs", "C) them", "D) they"], a: "C" },
    { q: "Fill in: 'I saw ___ at the market.' (him/her)", c: ["A) he", "B) she", "C) him", "D) they"], a: "C" },
    { q: "Which is CORRECT?", c: ["A) She told I the secret.", "B) She told me the secret.", "C) She told my the secret.", "D) She told mine the secret."], a: "B" },
    { q: "ពាក្យ 'us' ជា object pronoun ជំនួសសម្រាប់?", c: ["A) I", "B) we", "C) they", "D) you"], a: "B" },
    { q: "Object pronouns come ___ the verb.", c: ["A) before", "B) after", "C) inside", "D) never"], a: "B" },
    { q: "'Please help ___.' Fill with object pronoun.", c: ["A) I", "B) we", "C) me", "D) my"], a: "C" },
    { q: "Object pronoun for 'it' is?", c: ["A) its", "B) itself", "C) it", "D) him"], a: "C" }
  ]},
  { topic: "Reflexive Pronouns (សព្វនាមខ្លួនឯង)", questions: [
    { q: "Which is a reflexive pronoun?", c: ["A) him", "B) himself", "C) he", "D) his"], a: "B" },
    { q: "Reflexive pronouns end in?", c: ["A) -tion", "B) -ly", "C) -self / -selves", "D) -er"], a: "C" },
    { q: "Reflexive of 'I' is?", c: ["A) itself", "B) yourself", "C) myself", "D) himself"], a: "C" },
    { q: "Reflexive of 'they' is?", c: ["A) theirself", "B) themselfes", "C) themselves", "D) theirselves"], a: "C" },
    { q: "Fill in: 'She did it ___.'", c: ["A) himself", "B) myself", "C) yourself", "D) herself"], a: "D" },
    { q: "'ខ្ញុំធ្វើវាដោយខ្លួនឯង' = ___", c: ["A) I did it itself.", "B) I did it myself.", "C) I did it yourself.", "D) I did it themselves."], a: "B" },
    { q: "Which is CORRECT?", c: ["A) He hurt hisself.", "B) He hurt himself.", "C) He hurt itself.", "D) He hurt heself."], a: "B" },
    { q: "Reflexive of 'you' (singular) is?", c: ["A) yourself", "B) yourselves", "C) himself", "D) itself"], a: "A" },
    { q: "We use reflexive when subject and object are ___.", c: ["A) different people", "B) the same person", "C) plural only", "D) singular only"], a: "B" },
    { q: "Reflexive of 'we' is?", c: ["A) ourself", "B) ourselves", "C) weself", "D) us"], a: "B" }
  ]},
  { topic: "Demonstrative Pronouns (សព្វនាមចង្អុល)", questions: [
    { q: "Which is a demonstrative pronoun?", c: ["A) he", "B) this", "C) myself", "D) some"], a: "B" },
    { q: "We use ___ for things near us (singular).", c: ["A) that", "B) those", "C) these", "D) this"], a: "D" },
    { q: "We use ___ for things far (plural).", c: ["A) this", "B) that", "C) those", "D) these"], a: "C" },
    { q: "'___ is my book.' (near, singular)", c: ["A) Those", "B) These", "C) That", "D) This"], a: "D" },
    { q: "'___ are my friends.' (near, plural)", c: ["A) This", "B) That", "C) Those", "D) These"], a: "D" },
    { q: "ពាក្យ 'that' ចង្អុលលើ?", c: ["A) ជិត, ឯកវចនៈ", "B) ឆ្ងាយ, ឯកវចនៈ", "C) ជិត, ពហុវចនៈ", "D) ឆ្ងាយ, ពហុវចនៈ"], a: "B" },
    { q: "Which is CORRECT?", c: ["A) Those is my pen.", "B) These is my car.", "C) That is my book.", "D) This are my kids."], a: "C" },
    { q: "'___ were good times.' (past, plural)", c: ["A) This", "B) That", "C) These", "D) Those"], a: "D" },
    { q: "How many demonstrative pronouns are there?", c: ["A) 2", "B) 3", "C) 4", "D) 5"], a: "C" },
    { q: "ការប្រើ 'these' ប្រើជាមួយ?", c: ["A) ឯកវចនៈ ជិត", "B) ពហុវចនៈ ជិត", "C) ឯកវចនៈ ឆ្ងាយ", "D) ពហុវចនៈ ឆ្ងាយ"], a: "B" }
  ]},
  { topic: "Indefinite Pronouns (សព្វនាមមិនកំណត់)", questions: [
    { q: "Which is an indefinite pronoun?", c: ["A) I", "B) this", "C) someone", "D) him"], a: "C" },
    { q: "Fill in: '___ is at the door.'", c: ["A) Everything", "B) Nobody", "C) Something", "D) Someone"], a: "D" },
    { q: "Which is used in negative sentences?", c: ["A) someone", "B) anyone", "C) no one", "D) B and C"], a: "D" },
    { q: "'___ knows the answer.' (no person)", c: ["A) Someone", "B) Everyone", "C) Nobody", "D) Anybody"], a: "C" },
    { q: "Which means 'all things'?", c: ["A) nothing", "B) something", "C) everything", "D) anything"], a: "C" },
    { q: "Indefinite pronouns take ___ verb (singular).", c: ["A) plural", "B) singular", "C) none", "D) both"], a: "B" },
    { q: "'Has ___ seen my keys?' (question)", c: ["A) someone", "B) anyone", "C) no one", "D) everyone"], a: "B" },
    { q: "Which is CORRECT?", c: ["A) Everyone are here.", "B) Everyone is here.", "C) Everyone were here.", "D) Everyone am here."], a: "B" },
    { q: "ពាក្យ 'nothing' ប្រែជាខ្មែរថា?", c: ["A) អ្វីមួយ", "B) ទាំងអស់", "C) គ្មានអ្វី", "D) អ្វីៗ"], a: "C" },
    { q: "'I have ___ to say.' (negative idea)", c: ["A) something", "B) anything", "C) nothing", "D) everything"], a: "C" }
  ]},
  { topic: "Present Simple Tense", questions: [
    { q: "When do we use Present Simple?", c: ["A) Actions happening now", "B) Habits and facts", "C) Past actions", "D) Future plans"], a: "B" },
    { q: "Which is correct (He)?", c: ["A) He play football.", "B) He plays football.", "C) He playing football.", "D) He played football."], a: "B" },
    { q: "Fill in: 'The sun ___ in the east.'", c: ["A) rise", "B) rises", "C) rising", "D) risen"], a: "B" },
    { q: "Which sentence is Present Simple?", c: ["A) She is eating.", "B) She ate.", "C) She eats rice.", "D) She will eat."], a: "C" },
    { q: "We add ___ to verbs for he/she/it.", c: ["A) ing", "B) ed", "C) s/es", "D) will"], a: "C" },
    { q: "Negative of 'I work' = ___", c: ["A) I not work.", "B) I doesn't work.", "C) I don't work.", "D) I no work."], a: "C" },
    { q: "Question form: 'She speaks English.' = ___", c: ["A) Does she speaks English?", "B) Do she speak English?", "C) Does she speak English?", "D) Is she speak English?"], a: "C" },
    { q: "ប្រើ Present Simple ក្នុងករណីណា?", c: ["A) សកម្មភាពកំពុងកើតឡើង", "B) ការពិតទូទៅ/ទម្លាប់", "C) អតីតកាល", "D) អនាគត"], a: "B" },
    { q: "Which adverb goes with Present Simple?", c: ["A) now", "B) yesterday", "C) tomorrow", "D) always"], a: "D" },
    { q: "'He ___ to school every day.'", c: ["A) go", "B) goes", "C) going", "D) went"], a: "B" }
  ]},
  { topic: "Present Continuous Tense", questions: [
    { q: "Present Continuous form is?", c: ["A) S + V1", "B) S + am/is/are + V-ing", "C) S + was/were + V-ing", "D) S + will + V1"], a: "B" },
    { q: "Which sentence is Present Continuous?", c: ["A) She eats.", "B) She ate.", "C) She is eating.", "D) She will eat."], a: "C" },
    { q: "Fill in: 'He ___ a book now.'", c: ["A) read", "B) reads", "C) is reading", "D) read"], a: "C" },
    { q: "Which word signals Present Continuous?", c: ["A) always", "B) yesterday", "C) now / at the moment", "D) tomorrow"], a: "C" },
    { q: "'I ___ to music.' (right now)", c: ["A) listen", "B) am listening", "C) listened", "D) will listen"], a: "B" },
    { q: "Negative: 'She is sleeping.' = ___", c: ["A) She not sleeping.", "B) She isn't sleeping.", "C) She doesn't sleeping.", "D) She no sleeping."], a: "B" },
    { q: "Question: '___ you working now?'", c: ["A) Do", "B) Does", "C) Are", "D) Did"], a: "C" },
    { q: "ប្រើ Present Continuous ក្នុងករណីណា?", c: ["A) ទម្លាប់", "B) ការពិត", "C) សកម្មភាពកំពុងកើត", "D) អតីតកាល"], a: "C" },
    { q: "Which V-ing is correct?", c: ["A) runing", "B) running", "C) runining", "D) runnes"], a: "B" },
    { q: "The verb 'run' + ing = ?", c: ["A) runing", "B) runnning", "C) running", "D) runs"], a: "C" }
  ]},
  { topic: "Past Simple Tense", questions: [
    { q: "Past Simple is used for?", c: ["A) Habits now", "B) Actions happening now", "C) Completed past actions", "D) Future plans"], a: "C" },
    { q: "What is the past of 'go'?", c: ["A) goed", "B) gone", "C) went", "D) going"], a: "C" },
    { q: "What is the past of 'eat'?", c: ["A) eated", "B) eating", "C) eat", "D) ate"], a: "D" },
    { q: "Regular past tense ends in?", c: ["A) -ing", "B) -ed", "C) -s", "D) -en"], a: "B" },
    { q: "'I ___ to the market yesterday.'", c: ["A) go", "B) goes", "C) went", "D) going"], a: "C" },
    { q: "Which word signals Past Simple?", c: ["A) now", "B) tomorrow", "C) yesterday", "D) always"], a: "C" },
    { q: "Negative Past Simple = ___", c: ["A) She not ate.", "B) She didn't eat.", "C) She doesn't ate.", "D) She wasn't eat."], a: "B" },
    { q: "Question form of 'She worked hard.' = ___", c: ["A) Does she work hard?", "B) Did she worked hard?", "C) Did she work hard?", "D) Was she work hard?"], a: "C" },
    { q: "ប្រើ Past Simple ក្នុងករណីណា?", c: ["A) ទម្លាប់", "B) ភាពជាក់ស្តែង", "C) សកម្មភាពដែលបានបញ្ចប់", "D) ផែនការ"], a: "C" },
    { q: "Past of 'buy'?", c: ["A) buyed", "B) buying", "C) buys", "D) bought"], a: "D" }
  ]},
  { topic: "Past Continuous Tense", questions: [
    { q: "Past Continuous form is?", c: ["A) S + am/is/are + Ving", "B) S + was/were + Ving", "C) S + V2", "D) S + will + Ving"], a: "B" },
    { q: "Which is Past Continuous?", c: ["A) She eats.", "B) She was eating.", "C) She has eaten.", "D) She ate."], a: "B" },
    { q: "'I ___ when he called.' Fill in.", c: ["A) sleep", "B) slept", "C) was sleeping", "D) have slept"], a: "C" },
    { q: "Past Continuous is used for?", c: ["A) A habit in past", "B) Action in progress at past time", "C) Completed action", "D) Future plan"], a: "B" },
    { q: "'They ___ football at 5pm yesterday.'", c: ["A) play", "B) played", "C) were playing", "D) are playing"], a: "C" },
    { q: "Which is CORRECT?", c: ["A) She was study.", "B) She was studied.", "C) She was studying.", "D) She were studying."], a: "C" },
    { q: "ប្រើ was/were ក្នុង Past Continuous យ៉ាងណា?", c: ["A) I/he/she/it → was", "B) you/we/they → were", "C) Both A and B", "D) None"], a: "C" },
    { q: "While ___-ing suggests Past Continuous.", c: ["A) future", "B) present", "C) background action", "D) completed action"], a: "C" },
    { q: "Negative: 'He was working.' = ___", c: ["A) He not was working.", "B) He wasn't working.", "C) He didn't working.", "D) He not working."], a: "B" },
    { q: "'It ___ heavily when I left.' Fill in.", c: ["A) rained", "B) raining", "C) was raining", "D) rains"], a: "C" }
  ]},
  { topic: "Present Perfect Tense", questions: [
    { q: "Present Perfect form is?", c: ["A) S + V2", "B) S + have/has + V3", "C) S + am/is + Ving", "D) S + will + V1"], a: "B" },
    { q: "Which is Present Perfect?", c: ["A) She ate.", "B) She is eating.", "C) She has eaten.", "D) She eats."], a: "C" },
    { q: "'I ___ my homework.' (just finished)", c: ["A) finish", "B) finished", "C) have finished", "D) am finishing"], a: "C" },
    { q: "Past participle (V3) of 'go' = ?", c: ["A) went", "B) gone", "C) going", "D) goes"], a: "B" },
    { q: "Present Perfect uses ___ with he/she/it.", c: ["A) have", "B) had", "C) has", "D) is"], a: "C" },
    { q: "'Have you ___ to Paris?' Fill in.", c: ["A) go", "B) went", "C) going", "D) been"], a: "D" },
    { q: "Which word often goes with Present Perfect?", c: ["A) yesterday", "B) ago", "C) ever / never", "D) last year"], a: "C" },
    { q: "Negative: 'I have seen it.' = ___", c: ["A) I not have seen it.", "B) I haven't seen it.", "C) I didn't seen it.", "D) I hasn't seen it."], a: "B" },
    { q: "ប្រើ Present Perfect ក្នុងករណីណា?", c: ["A) ការពិត", "B) អតីតកាលថ្ងៃពិតប្រាកដ", "C) បទពិសោធន៍ ឬការទើបបញ្ចប់", "D) ផែនការ"], a: "C" },
    { q: "'She ___ never eaten sushi.'", c: ["A) have", "B) has", "C) had", "D) is"], a: "B" }
  ]},
  { topic: "Present Perfect Continuous", questions: [
    { q: "Present Perfect Continuous form is?", c: ["A) have/has + V3", "B) have/has + been + Ving", "C) was/were + Ving", "D) will + be + Ving"], a: "B" },
    { q: "Which is Present Perfect Continuous?", c: ["A) She is working.", "B) She has worked.", "C) She has been working.", "D) She was working."], a: "C" },
    { q: "'I ___ here for 5 years.' (still working)", c: ["A) work", "B) worked", "C) have worked", "D) have been working"], a: "D" },
    { q: "This tense shows action that ___.", c: ["A) finished yesterday", "B) started in past and continues now", "C) will happen", "D) happens daily"], a: "B" },
    { q: "'How long ___ you been studying?'", c: ["A) has", "B) have", "C) had", "D) are"], a: "B" },
    { q: "'She ___ waiting for an hour.'", c: ["A) is", "B) was", "C) has been", "D) had been"], a: "C" },
    { q: "Keywords: 'for' and 'since' signal ___.", c: ["A) Past Simple", "B) Future", "C) Present Simple", "D) Present Perfect Continuous"], a: "D" },
    { q: "Which is CORRECT?", c: ["A) She have been sleeping.", "B) She has been sleeping.", "C) She been sleeping.", "D) She has sleeping."], a: "B" },
    { q: "ប្រើ Present Perfect Continuous ក្នុង?", c: ["A) ទម្លាប់ប្រចាំថ្ងៃ", "B) ផែនការ", "C) ការបន្តពីអតីតដល់បច្ចុប្បន្ន", "D) ការព្រួយ"], a: "C" },
    { q: "'I ___ been learning English for 2 years.'", c: ["A) am", "B) is", "C) have", "D) was"], a: "C" }
  ]},
  { topic: "Past Perfect Tense", questions: [
    { q: "Past Perfect form is?", c: ["A) have/has + V3", "B) had + V3", "C) was/were + Ving", "D) S + V2"], a: "B" },
    { q: "Which is Past Perfect?", c: ["A) She has eaten.", "B) She ate.", "C) She had eaten.", "D) She eats."], a: "C" },
    { q: "Past Perfect shows action ___ another past action.", c: ["A) same time as", "B) before", "C) after", "D) during"], a: "B" },
    { q: "'I ___ already eaten when she arrived.'", c: ["A) have", "B) has", "C) had", "D) was"], a: "C" },
    { q: "'When he came, I ___ finished my work.'", c: ["A) have", "B) had", "C) was", "D) am"], a: "B" },
    { q: "Past Perfect uses ___ for all subjects.", c: ["A) have", "B) has", "C) had", "D) was"], a: "C" },
    { q: "Which is CORRECT?", c: ["A) She have read.", "B) She has read.", "C) She had read.", "D) She had readed."], a: "C" },
    { q: "Negative: 'He had gone.' = ___", c: ["A) He not had gone.", "B) He hadn't gone.", "C) He didn't had gone.", "D) He hasn't gone."], a: "B" },
    { q: "ប្រើ Past Perfect ក្នុងករណីណា?", c: ["A) ទម្លាប់", "B) ការបញ្ចប់មុននៅអតីតកាល", "C) ផែនការ", "D) ការពិត"], a: "B" },
    { q: "'She ___ left before I arrived.'", c: ["A) has", "B) have", "C) had", "D) was"], a: "C" }
  ]},
  { topic: "Future Simple Tense", questions: [
    { q: "Future Simple form is?", c: ["A) S + V2", "B) S + am/is/are + Ving", "C) S + will + V1", "D) S + have + V3"], a: "C" },
    { q: "Which is Future Simple?", c: ["A) She eats.", "B) She is eating.", "C) She ate.", "D) She will eat."], a: "D" },
    { q: "'I ___ help you tomorrow.'", c: ["A) am", "B) was", "C) will", "D) have"], a: "C" },
    { q: "Future Simple uses ___ for all subjects.", c: ["A) shall / will", "B) am/is/are", "C) was/were", "D) have/has"], a: "A" },
    { q: "Negative: 'I will go.' = ___", c: ["A) I not will go.", "B) I won't go.", "C) I am not go.", "D) I didn't go."], a: "B" },
    { q: "Question: 'He will come.' = ___", c: ["A) Does he will come?", "B) Will he comes?", "C) Will he come?", "D) Is he will come?"], a: "C" },
    { q: "Which keyword signals future?", c: ["A) yesterday", "B) last week", "C) ago", "D) tomorrow / next week"], a: "D" },
    { q: "ប្រើ will ក្នុងករណីណា?", c: ["A) ទម្លាប់", "B) ការព្យាករណ៍ / ការសំណូមពរ", "C) អតីតកាល", "D) ការពិត"], a: "B" },
    { q: "'She ___ buy a new car next year.'", c: ["A) is", "B) was", "C) will", "D) has"], a: "C" },
    { q: "'won't' = ___", c: ["A) will not", "B) was not", "C) would not", "D) were not"], a: "A" }
  ]},
  { topic: "Future Continuous Tense", questions: [
    { q: "Future Continuous form is?", c: ["A) will + V1", "B) will + be + Ving", "C) am/is/are + Ving", "D) was/were + Ving"], a: "B" },
    { q: "Which is Future Continuous?", c: ["A) She eats.", "B) She will eat.", "C) She will be eating.", "D) She was eating."], a: "C" },
    { q: "Future Continuous describes action ___ at future time.", c: ["A) completed", "B) in progress", "C) repeated", "D) uncertain"], a: "B" },
    { q: "'I ___ sleeping at 10pm tonight.'", c: ["A) am", "B) will", "C) will be", "D) was"], a: "C" },
    { q: "'This time tomorrow, she ___ flying to London.'", c: ["A) is", "B) was", "C) will be", "D) has been"], a: "C" },
    { q: "Which is CORRECT?", c: ["A) They will being working.", "B) They will be working.", "C) They will been working.", "D) They will being work."], a: "B" },
    { q: "Negative: 'I will be sleeping.' = ___", c: ["A) I won't be sleeping.", "B) I am not sleeping.", "C) I wasn't sleeping.", "D) I not will be sleeping."], a: "A" },
    { q: "Question form: ___", c: ["A) Do they will be coming?", "B) Will they be coming?", "C) Are they will be coming?", "D) Were they coming?"], a: "B" },
    { q: "ប្រើ Future Continuous ក្នុងករណីណា?", c: ["A) ផែនការ", "B) ទម្លាប់", "C) សកម្មភាពនឹងកំពុងកើតឡើង", "D) ការបញ្ចប់"], a: "C" },
    { q: "'At 8am tomorrow, he ___ working.'", c: ["A) was", "B) is", "C) will be", "D) has been"], a: "C" }
  ]},
  { topic: "Be Going To (ផែនការ)", questions: [
    { q: "'Be going to' is used for?", c: ["A) Sudden decisions", "B) General predictions only", "C) Planned future actions", "D) Past habits"], a: "C" },
    { q: "Form of 'be going to' = ___", c: ["A) will + V1", "B) am/is/are + going to + V1", "C) was/were + going to", "D) have + V3"], a: "B" },
    { q: "'I ___ going to buy a car.'", c: ["A) will", "B) am", "C) was", "D) have"], a: "B" },
    { q: "'She ___ going to study tonight.'", c: ["A) am", "B) are", "C) is", "D) was"], a: "C" },
    { q: "Which is CORRECT?", c: ["A) They is going to leave.", "B) They are going to leave.", "C) They am going to leave.", "D) They going to leave."], a: "B" },
    { q: "Negative: 'He is going to go.' = ___", c: ["A) He isn't going to go.", "B) He won't going to go.", "C) He not going to go.", "D) He doesn't going to go."], a: "A" },
    { q: "Question: '___ she going to work?'", c: ["A) Does", "B) Do", "C) Is", "D) Are"], a: "C" },
    { q: "ប្រើ 'be going to' ខុសពី 'will' យ៉ាងណា?", c: ["A) be going to = ផែនការ, will = ការព្យាករណ៍/ការសំណូមពរ", "B) ស្រដៀងគ្នា", "C) will = ផែនការ, be going to = ការព្យាករណ៍", "D) be going to = អតីតកាល"], a: "A" },
    { q: "'They ___ going to visit us next week.'", c: ["A) am", "B) is", "C) are", "D) was"], a: "C" },
    { q: "'Look at the clouds! It ___ going to rain.'", c: ["A) am", "B) is", "C) are", "D) were"], a: "B" }
  ]},
  { topic: "Modal Verbs: Can & Could", questions: [
    { q: "'Can' is used to express?", c: ["A) Obligation", "B) Ability", "C) Condition", "D) Time"], a: "B" },
    { q: "Fill in: 'She ___ swim very well.'", c: ["A) cans", "B) can", "C) caning", "D) could to"], a: "B" },
    { q: "'Could' is the ___ form of 'can'.", c: ["A) future", "B) present", "C) past", "D) plural"], a: "C" },
    { q: "Which is polite request?", c: ["A) Can you help me?", "B) Could you help me?", "C) Both are polite", "D) Neither is polite"], a: "B" },
    { q: "Negative of 'can' = ___", c: ["A) can not", "B) cannot / can't", "C) can'nt", "D) cann't"], a: "B" },
    { q: "'___ you speak Khmer?' (ability question)", c: ["A) Could", "B) Can", "C) Both A and B", "D) Neither"], a: "C" },
    { q: "ពាក្យ 'can' ប្រែជាខ្មែរថា?", c: ["A) ត្រូវ", "B) អាច/ជំនាញ", "C) ត្រូវ/ចាំបាច់", "D) ប្រហែល"], a: "B" },
    { q: "Which is CORRECT?", c: ["A) She cans drive.", "B) She can drives.", "C) She can drive.", "D) She could drives."], a: "C" },
    { q: "Modal verbs never take ___.", c: ["A) -ing", "B) -ed or -s", "C) objects", "D) subjects"], a: "B" },
    { q: "'When I was young, I ___ run fast.'", c: ["A) can", "B) could", "C) will", "D) may"], a: "B" }
  ]},
  { topic: "Modal Verbs: May & Might", questions: [
    { q: "'May' is used to express?", c: ["A) Certainty", "B) Obligation", "C) Possibility / Permission", "D) Ability"], a: "C" },
    { q: "'It ___ rain today.' (possibility)", c: ["A) can", "B) must", "C) may", "D) should"], a: "C" },
    { q: "'___ I come in?' (permission)", c: ["A) Must", "B) May", "C) Should", "D) Will"], a: "B" },
    { q: "'Might' is ___ certain than 'may'.", c: ["A) more", "B) less", "C) equally", "D) never"], a: "B" },
    { q: "Which shows 50% possibility?", c: ["A) must", "B) will", "C) may / might", "D) should"], a: "C" },
    { q: "ពាក្យ 'might' ប្រែជាខ្មែរថា?", c: ["A) ត្រូវ", "B) ប្រហែលជា", "C) អាច", "D) គួរ"], a: "B" },
    { q: "Which is CORRECT?", c: ["A) She mays come.", "B) She might comes.", "C) She might come.", "D) She may comes."], a: "C" },
    { q: "'He ___ be at home.' (not sure)", c: ["A) must", "B) will", "C) might", "D) should"], a: "C" },
    { q: "Negative of 'may' = ___", c: ["A) mayn't", "B) may not", "C) no may", "D) cannot"], a: "B" },
    { q: "'She said she ___ come later.' (indirect)", c: ["A) may", "B) might", "C) can", "D) Both A and B"], a: "B" }
  ]},
  { topic: "Modal Verbs: Must & Have to", questions: [
    { q: "'Must' expresses?", c: ["A) Ability", "B) Possibility", "C) Obligation / Necessity", "D) Permission"], a: "C" },
    { q: "Fill in: 'You ___ wear a seatbelt.'", c: ["A) should", "B) can", "C) must", "D) might"], a: "C" },
    { q: "Difference: 'must' vs 'have to'?", c: ["A) Must = personal rule, have to = external rule", "B) They are the same", "C) Must = past, have to = present", "D) Have to = advice only"], a: "A" },
    { q: "'I ___ go now. I'm late.'", c: ["A) may", "B) might", "C) have to", "D) can"], a: "C" },
    { q: "Negative of 'must' = ___", c: ["A) mustn't", "B) don't must", "C) must not", "D) Both A and C"], a: "D" },
    { q: "'You ___ smoke here. It's forbidden.'", c: ["A) mustn't", "B) don't have to", "C) can't to", "D) shouldn't to"], a: "A" },
    { q: "ពាក្យ 'must' ប្រែជាខ្មែរថា?", c: ["A) ប្រហែល", "B) អាច", "C) ត្រូវ/ចាំបាច់", "D) គួរ"], a: "C" },
    { q: "'You ___ to finish by Monday.' (external rule)", c: ["A) must", "B) have", "C) can", "D) might"], a: "B" },
    { q: "'Mustn't' means ___ something.", c: ["A) not necessary to do", "B) forbidden to do", "C) able to do", "D) advised to do"], a: "B" },
    { q: "Which is CORRECT?", c: ["A) She musts go.", "B) She must go.", "C) She must goes.", "D) She must to go."], a: "B" }
  ]},
  { topic: "Modal Verbs: Should & Ought to", questions: [
    { q: "'Should' is used for?", c: ["A) Certainty", "B) Advice / Recommendation", "C) Ability", "D) Permission"], a: "B" },
    { q: "'You ___ see a doctor.' (advice)", c: ["A) must", "B) should", "C) can", "D) will"], a: "B" },
    { q: "'Ought to' means the same as?", c: ["A) can", "B) must", "C) should", "D) will"], a: "C" },
    { q: "Negative of 'should' = ___", c: ["A) should not / shouldn't", "B) no should", "C) not should", "D) shouln't"], a: "A" },
    { q: "ពាក្យ 'should' ប្រែជាខ្មែរថា?", c: ["A) ត្រូវ", "B) អាច", "C) គួរ/ដែលគួរ", "D) ប្រហែល"], a: "C" },
    { q: "Which is CORRECT?", c: ["A) You should to go.", "B) You ought go.", "C) You should go.", "D) You should going."], a: "C" },
    { q: "'Ought to' form = ___", c: ["A) ought + V1", "B) ought to + V1", "C) ought + Ving", "D) ought + V3"], a: "B" },
    { q: "'She ___ study harder.' (advice)", c: ["A) will", "B) can", "C) ought to", "D) could to"], a: "C" },
    { q: "'You ___ eat too much sugar.' (negative advice)", c: ["A) should", "B) shouldn't", "C) must", "D) can"], a: "B" },
    { q: "Which is a polite suggestion?", c: ["A) You must go.", "B) You will go.", "C) You should go.", "D) You can go."], a: "C" }
  ]},
  { topic: "Adverbs of Manner (របៀប)", questions: [
    { q: "Adverbs of Manner answer which question?", c: ["A) When?", "B) Where?", "C) How?", "D) How often?"], a: "C" },
    { q: "How do we usually form adverbs of manner?", c: ["A) adj + er", "B) adj + ly", "C) adj + est", "D) adj + s"], a: "B" },
    { q: "'She speaks ___.'' (soft → adverb)", c: ["A) softly", "B) softer", "C) softest", "D) soft"], a: "A" },
    { q: "Which is an adverb of manner?", c: ["A) here", "B) now", "C) quickly", "D) often"], a: "C" },
    { q: "Adverbs of manner usually go ___ the verb.", c: ["A) before", "B) after", "C) inside", "D) never near"], a: "B" },
    { q: "'He runs ___.' Fill in.", c: ["A) quick", "B) quickly", "C) quicker", "D) quickest"], a: "B" },
    { q: "ពាក្យ 'carefully' ប្រែជាខ្មែរថា?", c: ["A) ប្រញាប់", "B) ដោយប្រុងប្រយ័ត្ន", "C) ខ្លាំង", "D) ទន់"], a: "B" },
    { q: "Adverb of 'happy' = ___", c: ["A) happily", "B) happyer", "C) more happy", "D) happiness"], a: "A" },
    { q: "Which sentence is CORRECT?", c: ["A) She sings beautiful.", "B) She sings beautifully.", "C) She beautiful sings.", "D) She sings beautifull."], a: "B" },
    { q: "Adverb of 'good' = ___", c: ["A) goodly", "B) gooder", "C) well", "D) goodly"], a: "C" }
  ]},
  { topic: "Adverbs of Frequency (ភាពញឹកញាប់)", questions: [
    { q: "Adverbs of frequency answer?", c: ["A) How?", "B) Where?", "C) How often?", "D) When?"], a: "C" },
    { q: "Which adverb means 100%?", c: ["A) sometimes", "B) often", "C) always", "D) rarely"], a: "C" },
    { q: "Order from most to least frequent: ___", c: ["A) always > usually > often > sometimes > never", "B) never > sometimes > often > usually > always", "C) often > always > never > sometimes", "D) always > never > often > usually"], a: "A" },
    { q: "Where does the adverb go? 'She ___ wakes up early.'", c: ["A) sometimes", "B) at the end", "C) before the verb", "D) Both A and C"], a: "D" },
    { q: "ពាក្យ 'never' ប្រែជាខ្មែរថា?", c: ["A) ជាប្រចាំ", "B) ម្តងម្កាល", "C) ដែរ", "D) មិនដែល"], a: "D" },
    { q: "'He ___ eats breakfast.' (every day)", c: ["A) never", "B) always", "C) rarely", "D) sometimes"], a: "B" },
    { q: "Which is correct position?", c: ["A) She always is late.", "B) She is always late.", "C) Always she is late.", "D) She is late always."], a: "B" },
    { q: "'I ___ go to the gym.' (50% of the time)", c: ["A) always", "B) never", "C) sometimes", "D) rarely"], a: "C" },
    { q: "ពាក្យ 'usually' ប្រែជាខ្មែរថា?", c: ["A) ជាប្រចាំ", "B) ជាធម្មតា", "C) ម្តងម្កាល", "D) ដំបូង"], a: "B" },
    { q: "Which adverb means almost never?", c: ["A) often", "B) sometimes", "C) rarely / seldom", "D) usually"], a: "C" }
  ]},
  { topic: "Adverbs of Time (ពេលវេលា)", questions: [
    { q: "Adverbs of time tell us?", c: ["A) How something is done", "B) Where something happens", "C) When something happens", "D) How often it happens"], a: "C" },
    { q: "Which is an adverb of time?", c: ["A) quickly", "B) here", "C) yesterday", "D) often"], a: "C" },
    { q: "'I will see you ___.' (next day)", c: ["A) here", "B) tomorrow", "C) quickly", "D) always"], a: "B" },
    { q: "ពាក្យ 'yesterday' ប្រែជាខ្មែរថា?", c: ["A) ថ្ងៃស្អែក", "B) ឥឡូវ", "C) ម្សិលមិញ", "D) នៅ"], a: "C" },
    { q: "Which goes with Past Simple?", c: ["A) tomorrow", "B) now", "C) last week", "D) next year"], a: "C" },
    { q: "Which goes with Future?", c: ["A) yesterday", "B) ago", "C) last month", "D) next week"], a: "D" },
    { q: "'She left ___.' (recently)", c: ["A) tomorrow", "B) just now / recently", "C) next week", "D) here"], a: "B" },
    { q: "Adverbs of time usually go at the ___ of a sentence.", c: ["A) beginning", "B) middle", "C) end or beginning", "D) always middle"], a: "C" },
    { q: "ពាក្យ 'soon' ប្រែជាខ្មែរថា?", c: ["A) ត្រូវ", "B) ឆាប់ៗ/ក្នុងពេលឆាប់", "C) ម្សិលមិញ", "D) ដូច"], a: "B" },
    { q: "'___, she was a teacher.' (before now)", c: ["A) Tomorrow", "B) Now", "C) Formerly / Previously", "D) Here"], a: "C" }
  ]},
  { topic: "Adverbs of Place (ទីកន្លែង)", questions: [
    { q: "Adverbs of place answer?", c: ["A) When?", "B) How?", "C) Where?", "D) How often?"], a: "C" },
    { q: "Which is an adverb of place?", c: ["A) often", "B) quickly", "C) here", "D) yesterday"], a: "C" },
    { q: "'Please put it ___.' (near speaker)", c: ["A) there", "B) everywhere", "C) here", "D) nowhere"], a: "C" },
    { q: "ពាក្យ 'everywhere' ប្រែជាខ្មែរថា?", c: ["A) មិនមែន", "B) ទីណា", "C) គ្រប់ទីកន្លែង", "D) ទីនេះ"], a: "C" },
    { q: "Which sentence has adverb of place?", c: ["A) She runs quickly.", "B) She runs daily.", "C) She is here.", "D) She runs yesterday."], a: "C" },
    { q: "'I can't find it ___.' (not any place)", c: ["A) everywhere", "B) somewhere", "C) anywhere", "D) nowhere"], a: "C" },
    { q: "ពាក្យ 'nearby' ប្រែជាខ្មែរថា?", c: ["A) ឆ្ងាយ", "B) ក្បែរ/នៅជិត", "C) ខ្ពស់", "D) ទូទៅ"], a: "B" },
    { q: "Adverbs of place usually go ___ the verb.", c: ["A) before", "B) after", "C) inside", "D) before subject"], a: "B" },
    { q: "'She went ___.' (opposite of 'here')", c: ["A) now", "B) there", "C) often", "D) well"], a: "B" },
    { q: "Which is NOT adverb of place?", c: ["A) inside", "B) outside", "C) upstairs", "D) carefully"], a: "D" }
  ]},
  { topic: "Prepositions of Time (ធ្នាក់ពេលវេលា)", questions: [
    { q: "We use 'at' with?", c: ["A) months", "B) years", "C) exact times", "D) seasons"], a: "C" },
    { q: "We use 'on' with?", c: ["A) years", "B) specific days / dates", "C) exact times", "D) centuries"], a: "B" },
    { q: "We use 'in' with?", c: ["A) specific days", "B) exact times", "C) months / years / seasons", "D) clock time"], a: "C" },
    { q: "Fill in: 'She was born ___ 2000.'", c: ["A) at", "B) on", "C) in", "D) for"], a: "C" },
    { q: "Fill in: 'The meeting is ___ Monday.'", c: ["A) in", "B) at", "C) on", "D) since"], a: "C" },
    { q: "Fill in: 'Class starts ___ 8 o'clock.'", c: ["A) in", "B) on", "C) at", "D) by"], a: "C" },
    { q: "ធ្នាក់ 'since' ប្រើជាមួយ?", c: ["A) ចំណាយពេល", "B) ចាប់ពីពេលណាមួយ", "C) ពេលវេលាជាក់លាក់", "D) ថ្ងៃ"], a: "B" },
    { q: "ធ្នាក់ 'for' ប្រើជាមួយ?", c: ["A) ចំណាយពេលប៉ុន្មាន", "B) ថ្ងៃ", "C) ខែ", "D) ម៉ោង"], a: "A" },
    { q: "'___ the morning, I exercise.'", c: ["A) At", "B) On", "C) In", "D) By"], a: "C" },
    { q: "'She will arrive ___ Friday morning.'", c: ["A) in", "B) on", "C) at", "D) during"], a: "B" }
  ]},
  { topic: "Prepositions of Place (ធ្នាក់ទីកន្លែង)", questions: [
    { q: "'In' is used for?", c: ["A) Exact point", "B) Surface", "C) Inside / enclosed space", "D) Near"], a: "C" },
    { q: "'On' is used for?", c: ["A) Inside space", "B) Surface", "C) Exact point", "D) Above"], a: "B" },
    { q: "'At' is used for?", c: ["A) Inside", "B) Surface", "C) Specific location or point", "D) General area"], a: "C" },
    { q: "Fill in: 'The book is ___ the table.'", c: ["A) at", "B) in", "C) on", "D) by"], a: "C" },
    { q: "Fill in: 'She is ___ the kitchen.'", c: ["A) on", "B) at", "C) in", "D) over"], a: "C" },
    { q: "Fill in: 'I'll meet you ___ the bus stop.'", c: ["A) in", "B) on", "C) at", "D) under"], a: "C" },
    { q: "ធ្នាក់ 'under' ប្រែជាខ្មែរថា?", c: ["A) លើ", "B) ក្រោម", "C) ក្នុង", "D) ក្បែរ"], a: "B" },
    { q: "'The cat is ___ the box.' (inside)", c: ["A) on", "B) under", "C) in", "D) at"], a: "C" },
    { q: "ធ្នាក់ 'behind' ប្រែជាខ្មែរថា?", c: ["A) ខាងមុខ", "B) ខាងក្រោយ", "C) ខាងក្រោម", "D) ខ្ជាប់"], a: "B" },
    { q: "'The school is ___ the park.' (next to)", c: ["A) in", "B) on", "C) at", "D) next to"], a: "D" }
  ]},
  { topic: "Articles: a, an, the", questions: [
    { q: "We use 'a' before?", c: ["A) Vowel sounds", "B) Consonant sounds", "C) Specific nouns", "D) Plural nouns"], a: "B" },
    { q: "We use 'an' before?", c: ["A) Consonant sounds", "B) Vowel sounds (a,e,i,o,u)", "C) Proper nouns", "D) Uncountable nouns"], a: "B" },
    { q: "Fill in: '___ apple a day keeps the doctor away.'", c: ["A) A", "B) An", "C) The", "D) No article"], a: "B" },
    { q: "Fill in: '___ cat sat on the mat.' (first mention)", c: ["A) An", "B) The", "C) A", "D) Some"], a: "C" },
    { q: "Fill in: '___ sun rises in the east.'", c: ["A) A", "B) An", "C) The", "D) No article"], a: "C" },
    { q: "'The' is used for?", c: ["A) First mention", "B) Any one thing", "C) Specific / known noun", "D) Vowel sounds"], a: "C" },
    { q: "Fill in: 'She is ___ honest person.'", c: ["A) a", "B) an", "C) the", "D) no article"], a: "B" },
    { q: "Which needs no article?", c: ["A) ___ Mekong River", "B) ___ Cambodia", "C) ___ Eiffel Tower", "D) ___ Amazon River"], a: "B" },
    { q: "ការប្រើ 'a' ក្នុងភាសាអង់គ្លេស គឺ?", c: ["A) ប្រើជាមួយនាមច្បាស់", "B) ប្រើជាមួយនាមមិនច្បាស់ ឯកវចនៈ", "C) ប្រើជាមួយនាមពហុវចនៈ", "D) ប្រើជាមួយបរិមាណ"], a: "B" },
    { q: "Fill in: '___ university I attend is good.'", c: ["A) A", "B) An", "C) The", "D) No article"], a: "C" }
  ]},
  { topic: "Quantifiers: some, any", questions: [
    { q: "'Some' is used in?", c: ["A) Questions only", "B) Negatives only", "C) Positive statements", "D) All sentences"], a: "C" },
    { q: "'Any' is usually used in?", c: ["A) Positive statements", "B) Questions and negatives", "C) Past tense only", "D) Formal writing"], a: "B" },
    { q: "Fill in: 'I have ___ money.'", c: ["A) any", "B) some", "C) much", "D) many"], a: "B" },
    { q: "Fill in: 'Do you have ___ questions?'", c: ["A) some", "B) much", "C) any", "D) a"], a: "C" },
    { q: "Fill in: 'I don't have ___ friends here.'", c: ["A) some", "B) any", "C) many", "D) a"], a: "B" },
    { q: "'Would you like ___ coffee?' (offering)", c: ["A) any", "B) some", "C) much", "D) many"], a: "B" },
    { q: "ពាក្យ 'some' ប្រែជាខ្មែរថា?", c: ["A) ទាំងអស់", "B) ខ្លះ/ចំនួនខ្លះ", "C) គ្មាន", "D) ច្រើន"], a: "B" },
    { q: "Fill in: 'There isn't ___ milk left.'", c: ["A) some", "B) many", "C) any", "D) few"], a: "C" },
    { q: "Which is CORRECT?", c: ["A) I have any time.", "B) I have some time.", "C) I have a time.", "D) I have every time."], a: "B" },
    { q: "'She didn't eat ___ vegetables.'", c: ["A) some", "B) any", "C) much", "D) a"], a: "B" }
  ]},
  { topic: "Quantifiers: much, many, a lot of", questions: [
    { q: "'Many' is used with?", c: ["A) Uncountable nouns", "B) Countable plural nouns", "C) Singular nouns", "D) Proper nouns"], a: "B" },
    { q: "'Much' is used with?", c: ["A) Countable nouns", "B) Plural nouns", "C) Uncountable nouns", "D) Proper nouns"], a: "C" },
    { q: "Fill in: 'How ___ water do you drink?'", c: ["A) many", "B) much", "C) few", "D) a lot"], a: "B" },
    { q: "Fill in: 'How ___ students are in your class?'", c: ["A) much", "B) little", "C) many", "D) few"], a: "C" },
    { q: "'A lot of' can be used with?", c: ["A) Countable only", "B) Uncountable only", "C) Both countable and uncountable", "D) Neither"], a: "C" },
    { q: "Fill in: 'She has ___ friends.' (lots)", c: ["A) much", "B) a lot of", "C) little", "D) few"], a: "B" },
    { q: "ពាក្យ 'much' ប្រែជាខ្មែរថា?", c: ["A) ច្រើន (សម្រាប់ count)", "B) ច្រើន (សម្រាប់ uncount)", "C) តិច", "D) ខ្លះ"], a: "B" },
    { q: "Which is CORRECT?", c: ["A) How much books do you have?", "B) How many books do you have?", "C) How much book do you have?", "D) How many book do you have?"], a: "B" },
    { q: "'I don't have ___ time.' (uncountable)", c: ["A) many", "B) few", "C) much", "D) a few"], a: "C" },
    { q: "'There are ___ cars in the street.'", c: ["A) much", "B) a lot of", "C) little", "D) a little"], a: "B" }
  ]},
  { topic: "Quantifiers: few, little", questions: [
    { q: "'A few' is used with?", c: ["A) Uncountable nouns", "B) Countable plural nouns", "C) Singular nouns", "D) Proper nouns"], a: "B" },
    { q: "'A little' is used with?", c: ["A) Countable nouns", "B) Plural nouns", "C) Uncountable nouns", "D) Proper nouns"], a: "C" },
    { q: "'Few' (without 'a') means?", c: ["A) Some - positive", "B) Hardly any - negative idea", "C) Many", "D) All"], a: "B" },
    { q: "'Little' (without 'a') means?", c: ["A) Some - positive", "B) Hardly any - negative idea", "C) Many", "D) All"], a: "B" },
    { q: "Fill in: 'I have ___ friends.' (a small number, OK)", c: ["A) little", "B) few", "C) a few", "D) a little"], a: "C" },
    { q: "Fill in: 'I have ___ money.' (a small amount, OK)", c: ["A) few", "B) a few", "C) little", "D) a little"], a: "D" },
    { q: "ពាក្យ 'a few' ប្រែជាខ្មែរថា?", c: ["A) ច្រើន", "B) ខ្លះ/ចំនួនដ៏ល្អ", "C) គ្មាន", "D) ទាំងអស់"], a: "B" },
    { q: "Which is CORRECT?", c: ["A) She has a few money.", "B) She has few moneys.", "C) She has a little money.", "D) She has little moneys."], a: "C" },
    { q: "'He has ___ friends.' (almost none, sad)", c: ["A) a few", "B) few", "C) little", "D) a little"], a: "B" },
    { q: "'There is ___ sugar in the bowl.' (very little)", c: ["A) few", "B) a few", "C) little", "D) many"], a: "C" }
  ]},
  { topic: "Conjunctions: and, but, or", questions: [
    { q: "'And' is used to?", c: ["A) Show contrast", "B) Show alternatives", "C) Add similar ideas", "D) Show cause"], a: "C" },
    { q: "'But' is used to?", c: ["A) Show contrast", "B) Add similar ideas", "C) Show alternatives", "D) Show result"], a: "A" },
    { q: "'Or' is used to?", c: ["A) Add ideas", "B) Show contrast", "C) Show alternatives / choices", "D) Show cause"], a: "C" },
    { q: "'She is rich ___ unhappy.'", c: ["A) and", "B) but", "C) or", "D) so"], a: "B" },
    { q: "'Do you want tea ___ coffee?'", c: ["A) and", "B) but", "C) or", "D) because"], a: "C" },
    { q: "'I like cats ___ dogs.'", c: ["A) or", "B) but", "C) and", "D) so"], a: "C" },
    { q: "ពាក្យ 'but' ប្រែជាខ្មែរថា?", c: ["A) ហើយ/និង", "B) ឬ", "C) ប៉ុន្តែ", "D) ពីព្រោះ"], a: "C" },
    { q: "Which sentence uses 'or' correctly?", c: ["A) I am tired or happy.", "B) Come now or be late.", "C) She is tall or clever.", "D) He eats or drinks."], a: "B" },
    { q: "FANBOYS stands for coordinating conjunctions including?", c: ["A) for, and, not, but, or, yet, so", "B) for, and, nor, but, or, yet, so", "C) for, any, nor, but, only, yet, so", "D) for, and, no, by, or, yet, some"], a: "B" },
    { q: "'She is young ___ wise.'", c: ["A) or", "B) and", "C) because", "D) so"], a: "B" }
  ]},
  { topic: "Conjunctions: because, so", questions: [
    { q: "'Because' shows?", c: ["A) Contrast", "B) Alternatives", "C) Cause / Reason", "D) Result"], a: "C" },
    { q: "'So' shows?", c: ["A) Reason", "B) Result / Consequence", "C) Contrast", "D) Condition"], a: "B" },
    { q: "'I am tired ___ I slept late.'", c: ["A) so", "B) but", "C) because", "D) or"], a: "C" },
    { q: "'It was raining, ___ I took an umbrella.'", c: ["A) because", "B) but", "C) so", "D) or"], a: "C" },
    { q: "ពាក្យ 'because' ប្រែជាខ្មែរថា?", c: ["A) ដូច្នេះ", "B) ប៉ុន្តែ", "C) ពីព្រោះ", "D) ហើយ"], a: "C" },
    { q: "Which is CORRECT?", c: ["A) She cried because she was sad.", "B) She cried so she was sad.", "C) She cried but she was sad.", "D) Because she cried, was sad."], a: "A" },
    { q: "'I was hungry, ___ I ate.'", c: ["A) because", "B) so", "C) but", "D) or"], a: "B" },
    { q: "'Because' introduces a ___ clause.", c: ["A) result", "B) contrast", "C) reason", "D) condition"], a: "C" },
    { q: "'So' comes ___ the result clause.", c: ["A) before", "B) after", "C) inside", "D) outside"], a: "A" },
    { q: "Which is WRONG?", c: ["A) Because it was hot, I drank water.", "B) It was hot because I drank water.", "C) I drank water because it was hot.", "D) It was hot, so I drank water."], a: "B" }
  ]},
  { topic: "Conjunctions: although, even though", questions: [
    { q: "'Although' means?", c: ["A) Because", "B) So", "C) Even if / Despite the fact that", "D) When"], a: "C" },
    { q: "Fill in: '___ it was raining, he went out.'", c: ["A) Because", "B) So", "C) Although", "D) Or"], a: "C" },
    { q: "'Even though' is ___ 'although'.", c: ["A) Opposite of", "B) Similar to", "C) Weaker than", "D) Unrelated to"], a: "B" },
    { q: "ពាក្យ 'although' ប្រែជាខ្មែរថា?", c: ["A) ពីព្រោះ", "B) ដូច្នេះ", "C) ទោះបីជា...ក៏ដោយ", "D) ហើយ"], a: "C" },
    { q: "'___ she studied hard, she failed.'", c: ["A) Because", "B) Even though", "C) So", "D) And"], a: "B" },
    { q: "Which is CORRECT?", c: ["A) Although it was cold but I swam.", "B) Although it was cold, I swam.", "C) Although but it was cold, I swam.", "D) Because although it was cold, I swam."], a: "B" },
    { q: "We do NOT use 'but' after 'although'.", c: ["A) True", "B) False", "C) Sometimes", "D) Depends"], a: "A" },
    { q: "'Although' introduces ___ clause.", c: ["A) result", "B) reason", "C) concession / contrast", "D) condition"], a: "C" },
    { q: "Fill in: '___ he is rich, he is not happy.'", c: ["A) So", "B) Because", "C) Even though", "D) Or"], a: "C" },
    { q: "'Although' can go at the ___ of a sentence.", c: ["A) beginning only", "B) end only", "C) middle only", "D) beginning or middle"], a: "D" }
  ]},
  { topic: "Relative Clauses: who, which, that", questions: [
    { q: "'Who' is used for?", c: ["A) Animals and things", "B) People", "C) Places", "D) Time"], a: "B" },
    { q: "'Which' is used for?", c: ["A) People", "B) Animals or things", "C) Places only", "D) Time"], a: "B" },
    { q: "'That' can replace?", c: ["A) who only", "B) which only", "C) who and which", "D) none"], a: "C" },
    { q: "'The man ___ called you is my friend.'", c: ["A) which", "B) whose", "C) who", "D) where"], a: "C" },
    { q: "'The book ___ I read was interesting.'", c: ["A) who", "B) whom", "C) whose", "D) which"], a: "D" },
    { q: "ពាក្យ 'who' ប្រើជំនួសសម្រាប់?", c: ["A) វត្ថុ", "B) ទីកន្លែង", "C) មនុស្ស", "D) ពេលវេលា"], a: "C" },
    { q: "'The car ___ she bought is red.'", c: ["A) who", "B) whom", "C) that / which", "D) where"], a: "C" },
    { q: "Relative clauses give ___ about a noun.", c: ["A) less information", "B) more information", "C) no information", "D) opposite information"], a: "B" },
    { q: "Which is CORRECT?", c: ["A) The woman who works here is kind.", "B) The woman which works here is kind.", "C) The woman where works here is kind.", "D) The woman whom works here is kind."], a: "A" },
    { q: "'The movie ___ we watched was great.'", c: ["A) who", "B) whom", "C) that", "D) whose"], a: "C" }
  ]},
  { topic: "Relative Clauses: whose, whom, where", questions: [
    { q: "'Whose' shows?", c: ["A) Place", "B) Time", "C) Possession", "D) Object"], a: "C" },
    { q: "'Where' is used for?", c: ["A) People", "B) Things", "C) Places", "D) Possession"], a: "C" },
    { q: "'Whom' is used for?", c: ["A) Subject of relative clause", "B) Object of relative clause (formal)", "C) Possession", "D) Places"], a: "B" },
    { q: "'The boy ___ bag was stolen cried.'", c: ["A) who", "B) which", "C) whose", "D) where"], a: "C" },
    { q: "'The city ___ I was born is beautiful.'", c: ["A) who", "B) which", "C) whose", "D) where"], a: "D" },
    { q: "ពាក្យ 'whose' ប្រើជំនួសសម្រាប់?", c: ["A) ទីកន្លែង", "B) កម្មសិទ្ធិ", "C) វត្ថុ", "D) ពេលវេលា"], a: "B" },
    { q: "'The man ___ I spoke to was kind.' (formal)", c: ["A) who", "B) whose", "C) whom", "D) which"], a: "C" },
    { q: "'The school ___ she studied is old.'", c: ["A) who", "B) whose", "C) which", "D) where"], a: "D" },
    { q: "Which is CORRECT?", c: ["A) The girl whose sister is a doctor.", "B) The girl who sister is a doctor.", "C) The girl which sister is a doctor.", "D) The girl whom sister is a doctor."], a: "A" },
    { q: "'The time ___ we met was special.'", c: ["A) where", "B) whose", "C) which", "D) when"], a: "D" }
  ]},
  { topic: "Passive Voice Present (ទម្រង់អកម្ម)", questions: [
    { q: "Present Passive form = ___", c: ["A) S + V1", "B) S + is/are + V3", "C) S + was/were + V3", "D) S + have + V3"], a: "B" },
    { q: "Active: 'She cleans the room.' → Passive: ___", c: ["A) The room cleans she.", "B) The room is cleaned by her.", "C) The room was cleaned by her.", "D) The room is cleaning."], a: "B" },
    { q: "Passive is used when we focus on?", c: ["A) The subject/doer", "B) The action or object", "C) The time", "D) The place"], a: "B" },
    { q: "'The letter ___ written every day.' (passive)", c: ["A) is", "B) was", "C) has", "D) does"], a: "A" },
    { q: "ប្រើ 'by' ក្នុង Passive Voice ដើម្បី?", c: ["A) បង្ហាញពេលវេលា", "B) បង្ហាញអ្នកធ្វើ", "C) បង្ហាញទីកន្លែង", "D) បង្ហាញ object"], a: "B" },
    { q: "Which is CORRECT Present Passive?", c: ["A) The car drives by him.", "B) The car is driving by him.", "C) The car is driven by him.", "D) The car drived by him."], a: "C" },
    { q: "Active: 'They sell the products.' → Passive: ___", c: ["A) The products sell.", "B) The products are sold.", "C) The products were sold.", "D) The products is sold."], a: "B" },
    { q: "Plural subject in passive uses?", c: ["A) is", "B) was", "C) are", "D) were"], a: "C" },
    { q: "Singular subject in passive uses?", c: ["A) are", "B) is", "C) were", "D) have"], a: "B" },
    { q: "'English ___ spoken here.' Fill in.", c: ["A) speak", "B) speaks", "C) is spoken", "D) are spoken"], a: "C" }
  ]},
  { topic: "Passive Voice Past (ទម្រង់អកម្មអតីតកាល)", questions: [
    { q: "Past Passive form = ___", c: ["A) S + is/are + V3", "B) S + was/were + V3", "C) S + have + V3", "D) S + V2"], a: "B" },
    { q: "Active: 'He wrote the letter.' → Passive: ___", c: ["A) The letter is written by him.", "B) The letter was written by him.", "C) The letter were written by him.", "D) The letter written by him."], a: "B" },
    { q: "'The house ___ built in 1950.'", c: ["A) is", "B) are", "C) was", "D) has"], a: "C" },
    { q: "Plural past passive uses?", c: ["A) was", "B) is", "C) were", "D) are"], a: "C" },
    { q: "Which is CORRECT Past Passive?", c: ["A) The books was read.", "B) The books were read.", "C) The books are read.", "D) The books is read."], a: "B" },
    { q: "Active: 'Police arrested them.' → Passive: ___", c: ["A) They was arrested.", "B) They are arrested.", "C) They were arrested.", "D) They arrested."], a: "C" },
    { q: "ប្រើ Past Passive ក្នុងករណីណា?", c: ["A) ផ្ដោតលើអ្នកធ្វើ", "B) ផ្ដោតលើ object ឬការពិពណ៌នា", "C) ទម្លាប់", "D) ផែនការ"], a: "B" },
    { q: "'The cake ___ eaten by the children.'", c: ["A) is", "B) are", "C) was", "D) were"], a: "C" },
    { q: "Which is WRONG?", c: ["A) She was chosen.", "B) They were invited.", "C) He was told.", "D) We was informed."], a: "D" },
    { q: "'Many trees ___ planted last year.'", c: ["A) is", "B) was", "C) were", "D) are"], a: "C" }
  ]},
  { topic: "Direct and Indirect Speech", questions: [
    { q: "Direct Speech uses ___ to show exact words.", c: ["A) brackets ( )", "B) quotation marks \" \"", "C) apostrophes ' '", "D) dashes — —"], a: "B" },
    { q: "He said, 'I am tired.' → Indirect: ___", c: ["A) He said that he is tired.", "B) He said that he was tired.", "C) He said that I am tired.", "D) He said that he will be tired."], a: "B" },
    { q: "In indirect speech, 'am/is' → ___", c: ["A) are", "B) will be", "C) was", "D) has been"], a: "C" },
    { q: "In indirect speech, 'will' → ___", c: ["A) would", "B) shall", "C) can", "D) may"], a: "A" },
    { q: "She said, 'I can swim.' → Indirect: ___", c: ["A) She said that she cans swim.", "B) She said that she could swim.", "C) She said that she can swim.", "D) She said that she will swim."], a: "B" },
    { q: "ដំណាក់កាលប្រែ tense ក្នុង Indirect Speech ហៅថា?", c: ["A) Passive Voice", "B) Backshift", "C) Reduction", "D) Conversion"], a: "B" },
    { q: "'Now' changes to ___ in indirect speech.", c: ["A) here", "B) tomorrow", "C) then", "D) ago"], a: "C" },
    { q: "'Today' changes to ___ in indirect speech.", c: ["A) tomorrow", "B) yesterday", "C) that day", "D) now"], a: "C" },
    { q: "He asked, 'Are you ready?' → Indirect: ___", c: ["A) He asked if I was ready.", "B) He asked that I am ready.", "C) He asked are you ready.", "D) He asked if am I ready."], a: "A" },
    { q: "Which reporting verb is for commands?", c: ["A) said", "B) told", "C) ordered / told + to", "D) asked"], a: "C" }
  ]},
  { topic: "Conditional Type 0 & 1", questions: [
    { q: "Type 0 conditional is for?", c: ["A) Unreal situations", "B) General truths / facts", "C) Past regrets", "D) Wishes"], a: "B" },
    { q: "Type 0 form = ___", c: ["A) If + V2, would + V1", "B) If + V1, V1", "C) If + had + V3, would have + V3", "D) If + will, can"], a: "B" },
    { q: "Type 1 conditional is for?", c: ["A) Unreal present", "B) Real / possible future", "C) Past unreal", "D) General truth"], a: "B" },
    { q: "Type 1 form = ___", c: ["A) If + V2, would + V1", "B) If + V1, will + V1", "C) If + had V3, would have V3", "D) If + is, was"], a: "B" },
    { q: "'If it rains, ___ stay home.'", c: ["A) I would", "B) I will", "C) I had", "D) I was"], a: "B" },
    { q: "'If you heat water to 100°C, it ___ boil.' (Type 0)", c: ["A) would", "B) will", "C) boils", "D) boiled"], a: "C" },
    { q: "ប្រើ Type 1 Conditional ក្នុង?", c: ["A) ស្ថានភាពមិនពិត", "B) ស្ថានភាពពិតក្នុងអនាគត", "C) អតីតកាល", "D) បំណងប្រាថ្នា"], a: "B" },
    { q: "Which is CORRECT Type 1?", c: ["A) If it will rain, I take an umbrella.", "B) If it rains, I will take an umbrella.", "C) If it rained, I would take an umbrella.", "D) If it had rained, I would have taken."], a: "B" },
    { q: "Type 0: 'If you ___ plants, they die.'", c: ["A) don't water", "B) didn't water", "C) won't water", "D) hadn't watered"], a: "A" },
    { q: "Type 1: 'If she ___ hard, she will pass.'", c: ["A) studied", "B) would study", "C) studies", "D) had studied"], a: "C" }
  ]},
  { topic: "Conditional Type 2", questions: [
    { q: "Type 2 conditional is for?", c: ["A) Real future situations", "B) General truths", "C) Unreal / imaginary present", "D) Past regrets"], a: "C" },
    { q: "Type 2 form = ___", c: ["A) If + V1, will + V1", "B) If + V2, would + V1", "C) If + had V3, would have V3", "D) If + is, was"], a: "B" },
    { q: "'If I ___ rich, I would buy a mansion.'", c: ["A) am", "B) was / were", "C) have been", "D) will be"], a: "B" },
    { q: "'If I were you, I ___ take the job.'", c: ["A) will", "B) am", "C) would", "D) had"], a: "C" },
    { q: "Type 2 uses 'were' for?", c: ["A) plural only", "B) all persons (formal)", "C) first person only", "D) third person only"], a: "B" },
    { q: "ប្រើ Type 2 Conditional ក្នុង?", c: ["A) ស្ថានភាពពិតក្នុងអនាគត", "B) ការពិតទូទៅ", "C) ស្ថានភាពមិនពិតក្នុងបច្ចុប្បន្ន", "D) ការប្រៀបធៀប"], a: "C" },
    { q: "'If she ___ the truth, she wouldn't lie.'", c: ["A) knows", "B) knew", "C) has known", "D) had known"], a: "B" },
    { q: "Which is CORRECT Type 2?", c: ["A) If he studies, he will pass.", "B) If he studied, he would pass.", "C) If he had studied, he would have passed.", "D) If he studies, he would pass."], a: "B" },
    { q: "'I would go to Paris if I ___ money.'", c: ["A) have", "B) had", "C) will have", "D) had had"], a: "B" },
    { q: "The 'result' clause in Type 2 uses ___.", c: ["A) will + V1", "B) would + V1", "C) had + V3", "D) was + V3"], a: "B" }
  ]},
  { topic: "Conditional Type 3", questions: [
    { q: "Type 3 conditional is for?", c: ["A) Real future", "B) General truths", "C) Unreal present", "D) Unreal / regretted past"], a: "D" },
    { q: "Type 3 form = ___", c: ["A) If + V2, would + V1", "B) If + had + V3, would have + V3", "C) If + V1, will + V1", "D) If + is, was"], a: "B" },
    { q: "'If I ___ harder, I would have passed.'", c: ["A) studied", "B) study", "C) had studied", "D) have studied"], a: "C" },
    { q: "'If she ___ the medicine, she would have recovered.'", c: ["A) takes", "B) took", "C) had taken", "D) has taken"], a: "C" },
    { q: "Result clause in Type 3 = ___", c: ["A) would + V1", "B) would have + V3", "C) will + V1", "D) had + V3"], a: "B" },
    { q: "ប្រើ Type 3 Conditional ក្នុង?", c: ["A) ស្ថានភាពពិត", "B) ស្ថានភាពមិនពិតនៃអតីតកាល", "C) ទម្លាប់", "D) ការព្យាករណ៍"], a: "B" },
    { q: "'She ___ the party if she had known about it.'", c: ["A) would attend", "B) would have attended", "C) will attend", "D) attended"], a: "B" },
    { q: "Which is CORRECT Type 3?", c: ["A) If he had worked harder, he would passed.", "B) If he had worked harder, he would have passed.", "C) If he worked harder, he would pass.", "D) If he works harder, he will pass."], a: "B" },
    { q: "Type 3 expresses?", c: ["A) A real plan", "B) A wish about the present", "C) Regret about the past", "D) A general truth"], a: "C" },
    { q: "'If they ___ the map, they wouldn't have gotten lost.'", c: ["A) have", "B) had", "C) had had", "D) would have"], a: "C" }
  ]}
];
