module.exports = [
  { topic: "Nouns (នាម)", kh: "នាមគឺជាពាក្យសម្រាប់សម្គាល់មនុស្ស សត្វ ទីកន្លែង ឬវត្ថុ។\n- dog (ឆ្កែ)\n- man (មនុស្ស)\n- table (តុ)" },
  { topic: "Plural Nouns (នាមពហុវចនៈ)", kh: "ការបង្កើតនាមពហុវចនៈជាទូទៅថែម s ឬ es។\n- cat -> cats\n- box -> boxes" },
  { topic: "Uncountable Nouns (នាមរាប់មិនបាន)", kh: "នាមដែលមិនអាចរាប់បាន (គ្មានទម្រង់ពហុវចនៈ)។\n- water (ទឹក)\n- rice (បាយ)\n- money (លុយ)" },
  { topic: "Possessive Nouns (នាមកម្មសិទ្ធិ)", kh: "ការប្រើប្រាស់ 's ដើម្បីបញ្ជាក់កម្មសិទ្ធិ។\n- Tom's book (សៀវភៅរបស់ Tom)\n- girl's bag (កាបូបរបស់ក្មេងស្រី)" },
  { topic: "Compound Nouns (នាមសមាស)", kh: "នាមពីរផ្សំបញ្ចូលគ្នាបង្កើតបាននាមថ្មី។\n- tooth + brush = toothbrush (ច្រាសដុសធ្មេញ)\n- school + bag = schoolbag (កាបូបស្ពាយ)" },
  { topic: "Adjectives (គុណនាម)", kh: "គុណនាមប្រើសម្រាប់ពណ៌នានាម។\n- a good boy (ក្មេងប្រុសល្អ)\n- a big house (ផ្ទះធំ)" },
  { topic: "Comparative Adjectives (គុណនាមកម្រិតប្រៀបធៀប)", kh: "ប្រើដើម្បីប្រៀបធៀបវត្ថុ២ ដោយថែម er ឬ more។\n- taller (ខ្ពស់ជាង)\n- more beautiful (ស្រស់ស្អាតជាង)" },
  { topic: "Superlative Adjectives (គុណនាមកម្រិតបំផុត)", kh: "ប្រើដើម្បីប្រៀបធៀបកម្រិតខ្ពស់បំផុត ដោយថែម est ឬ most។\n- the tallest (ខ្ពស់ជាងគេ)\n- the most beautiful (ស្អាតជាងគេ)" },
  { topic: "Personal Pronouns (សព្វនាមបុគ្គល)", kh: "ពាក្យជំនួសនាមជាប្រធាន៖ I, you, we, they, he, she, it។\n- I am a student.\n- She is a doctor." },
  { topic: "Object Pronouns (សព្វនាមកម្មបទ)", kh: "ពាក្យជំនួសនាមជាកម្មបទ៖ me, you, us, them, him, her, it។\n- He gave it to me.\n- I saw them." },
  { topic: "Reflexive Pronouns (សព្វនាមបញ្ជាក់ខ្លួនឯង)", kh: "បញ្ចប់ដោយ self ឬ selves៖ myself, yourself, themselves.\n- I did it myself. (ខ្ញុំធ្វើវាដោយខ្លួនឯង)" },
  { topic: "Demonstrative Pronouns (សព្វនាមចង្អុល)", kh: "this, that, these, those.\n- This is a book.\n- Those are cars." },
  { topic: "Indefinite Pronouns (សព្វនាមមិនកំណត់)", kh: "someone, anyone, nothing, everything.\n- Someone is here.\n- I have nothing." },
  { topic: "Present Simple Tense", kh: "ប្រើសម្រាប់ទម្លាប់ ឬការពិតទូទៅ។\n- I go to school every day.\n- The sun rises in the east." },
  { topic: "Present Continuous Tense", kh: "ប្រើសម្រាប់សកម្មភាពកំពុងកើតឡើង។\n- I am eating now.\n- She is studying." },
  { topic: "Past Simple Tense", kh: "ប្រើសម្រាប់សកម្មភាពដែលបានបញ្ចប់ក្នុងអតីតកាល។\n- I went to the market yesterday.\n- She bought a new car." },
  { topic: "Past Continuous Tense", kh: "ប្រើសម្រាប់សកម្មភាពកំពុងកើតឡើងក្នុងអតីតកាល។\n- I was sleeping when he called." },
  { topic: "Present Perfect Tense", kh: "ប្រើសម្រាប់សកម្មភាពទើបនឹងបញ្ចប់ ឬបទពិសោធន៍។\n- I have finished my homework.\n- She has been to Paris." },
  { topic: "Present Perfect Continuous", kh: "សកម្មភាពចាប់ផ្តើមពីអតីតកាលហើយបន្តដល់បច្ចុប្បន្ន។\n- I have been working here for 5 years." },
  { topic: "Past Perfect Tense", kh: "ប្រើសម្រាប់សកម្មភាពមួយបញ្ចប់មុនសកម្មភាពមួយទៀតក្នុងអតីតកាល។\n- I had eaten before he arrived." },
  { topic: "Future Simple Tense", kh: "ប្រើសម្រាប់និយាយអំពីអនាគត (will/shall)។\n- I will help you tomorrow." },
  { topic: "Future Continuous Tense", kh: "សកម្មភាពនឹងកំពុងកើតឡើងនៅពេលកំណត់មួយក្នុងអនាគត។\n- I will be sleeping at 10 PM tonight." },
  { topic: "Be Going To (អនាគតកាលមានគម្រោង)", kh: "ប្រើសម្រាប់ផែនការដែលបានព្រាងទុក។\n- I am going to buy a car next year." },
  { topic: "Modal Verbs: Can & Could", kh: "ប្រើប្រាប់ពីសមត្ថភាព ឬការសុំអនុញ្ញាត។\n- I can swim.\n- Could you help me?" },
  { topic: "Modal Verbs: May & Might", kh: "ប្រើប្រាប់ពីលទ្ធភាព ឬការសុំអនុញ្ញាត។\n- It may rain today.\n- May I come in?" },
  { topic: "Modal Verbs: Must & Have to", kh: "ប្រើប្រាប់ពីភាពចាំបាច់ ឬកាតព្វកិច្ច។\n- You must wear a helmet.\n- I have to go now." },
  { topic: "Modal Verbs: Should & Ought to", kh: "ប្រើសម្រាប់ផ្តល់ដំបូន្មាន។\n- You should see a doctor.\n- You ought to study harder." },
  { topic: "Adverbs of Manner (គុណកិរិយាប្រាប់របៀប)", kh: "ប្រាប់ថាតើធ្វើសកម្មភាពនោះដោយរបៀបណា (ភាគច្រើនបញ្ចប់ដោយ ly)។\n- He runs quickly.\n- She speaks softly." },
  { topic: "Adverbs of Frequency (គុណកិរិយាប្រាប់ភាពញឹកញាប់)", kh: "always, usually, often, sometimes, never.\n- I always get up early." },
  { topic: "Adverbs of Time (គុណកិរិយាប្រាប់ពេលវេលា)", kh: "now, yesterday, tomorrow, soon.\n- I will see you tomorrow." },
  { topic: "Adverbs of Place (គុណកិរិយាប្រាប់ទីកន្លែង)", kh: "here, there, everywhere, nowhere.\n- Please put it here." },
  { topic: "Prepositions of Time (ធ្នាក់ពេលវេលា)", kh: "in (ខែ, ឆ្នាំ), on (ថ្ងៃ), at (ម៉ោង)។\n- at 7 o'clock\n- on Monday\n- in January" },
  { topic: "Prepositions of Place (ធ្នាក់ទីកន្លែង)", kh: "in (ក្នុង), on (លើ), at (នៅទីតាំងជាក់លាក់)។\n- in the room\n- on the table\n- at the bus stop" },
  { topic: "Articles: a, an, the", kh: "A/An ប្រើជាមួយនាមរាប់បានឯកវចនៈទូទៅ។ The ប្រើជាមួយនាមជាក់លាក់។\n- a cat, an apple, the sun" },
  { topic: "Quantifiers: some, any", kh: "Some ប្រើក្នុងប្រយោគស្រប Any ប្រើក្នុងប្រយោគបដិសេធនិងសំណួរ។\n- I have some money.\n- I don't have any money." },
  { topic: "Quantifiers: much, many, a lot of", kh: "Many (នាមរាប់បាន), Much (នាមរាប់មិនបាន)។\n- many books\n- much water\n- a lot of people" },
  { topic: "Quantifiers: few, little", kh: "A few (នាមរាប់បាន), A little (នាមរាប់មិនបាន)។\n- a few friends\n- a little milk" },
  { topic: "Conjunctions: and, but, or", kh: "ពាក្យភ្ជាប់ប្រយោគ ឬពាក្យ។\n- I like apples and bananas.\n- He is rich but unhappy." },
  { topic: "Conjunctions: because, so", kh: "Because (ពីព្រោះ), So (ដូច្នេះ)។\n- I am crying because I am sad.\n- I am tired, so I will sleep." },
  { topic: "Conjunctions: although, even though", kh: "ទោះបីជាយ៉ាងណាក៏ដោយ។\n- Although it was raining, he went out." },
  { topic: "Relative Clauses: who, which, that", kh: "Who (សម្រាប់មនុស្ស), Which (សម្រាប់សត្វ/វត្ថុ), That (ទូទៅ)។\n- The man who called you is my brother." },
  { topic: "Relative Clauses: whose, whom, where", kh: "Whose (កម្មសិទ្ធិ), Where (ទីកន្លែង)។\n- The place where we met.\n- The boy whose car was stolen." },
  { topic: "Passive Voice (ទម្រង់អកម្ម) Present", kh: "ប្រើពេលយើងផ្ដោតលើកម្មវត្ថុ។ ទម្រង់: is/are + V3.\n- The room is cleaned every day." },
  { topic: "Passive Voice (ទម្រង់អកម្ម) Past", kh: "ទម្រង់: was/were + V3.\n- The letter was written yesterday." },
  { topic: "Direct and Indirect Speech", kh: "ការនាំពាក្យសម្ដីអ្នកដទៃមកនិយាយប្រាប់គេ។\n- He said, 'I am tired.'\n- He said that he was tired." },
  { topic: "Conditional Type 0 & 1", kh: "លក្ខខណ្ឌពិត ឬអាចកើតឡើង។\n- If it rains, I will stay home." },
  { topic: "Conditional Type 2", kh: "លក្ខខណ្ឌមិនពិតក្នុងបច្ចុប្បន្ន។\n- If I had money, I would buy a car." },
  { topic: "Conditional Type 3", kh: "លក្ខខណ្ឌមិនពិតក្នុងអតីតកាល។\n- If I had studied hard, I would have passed." }
];
