module.exports = [
  {
    "topic": "Nouns (នាម)",
    "kh": "📖 និយមន័យ និងការប្រើប្រាស់ (Definition & Usage)៖\nនាម (Noun) គឺជាពាក្យដែលប្រើសម្រាប់សម្គាល់ឈ្មោះ មនុស្ស សត្វ វត្ថុ ទីកន្លែង រុក្ខជាតិ ឬគំនិតអរូបី។\n\n📐 រូបមន្ត និងក្បួនវេយ្យាករណ៍ (Formulas & Rules)៖\n១. Proper Nouns (នាមអសាធារណ៍ ត្រូវសរសេរអក្សរធំ): Cambodia, Phnom Penh, John\n២. Common Nouns (នាមសាធារណ៍ទូទៅ): teacher, city, book, computer\n៣. Concrete Nouns (នាមរូបិយមើលឃើញ/ប៉ះបាន): car, house, mobile phone\n៤. Abstract Nouns (នាមអរូបីមើលមិនឃើញ): success, happiness, knowledge, freedom\n\n💡 ឧទាហរណ៍ជាក់ស្តែង & ការបកប្រែជាភាសាខ្មែរ (Practical Examples with Khmer Translation)៖\n1. 🇬🇧 The dedicated teacher explains the English grammar clearly.\n   🇰🇭 (លោកគ្រូដែលខិតខំប្រឹងប្រែងបានពន្យល់វេយ្យាករណ៍ភាសាអង់គ្លេសយ៉ាងច្បាស់លាស់។)\n\n2. 🇬🇧 Phnom Penh is developing very rapidly with many modern buildings.\n   🇰🇭 (រាជធានីភ្នំពេញកំពុងអភិវឌ្ឍយ៉ាងលឿនជាមួយនឹងអគារទំនើបៗជាច្រើន។)\n\n3. 🇬🇧 True happiness comes from helping others and continuous learning.\n   🇰🇭 (សុភមង្គលពិតប្រាកដកើតចេញពីការជួយអ្នកដទៃ និងការរៀនសូត្រឥតឈប់ឈរ។)\n\n4. 🇬🇧 She bought a new laptop and several business books yesterday.\n   🇰🇭 (នាងបានទិញកុំព្យូទ័រយួរដៃថ្មីមួយ និងសៀវភៅជំនួញជាច្រើនក្បាលកាលពីម្សិលមិញ។)\n\n⚠️ កំហុសញឹកញាប់ដែលត្រូវចៀសវាង (Common Mistakes)៖\n❌ ខុស: angkor wat is in cambodia.\n✅ ត្រូវ: Angkor Wat is in Cambodia. (នាមអសាធារណ៍ត្រូវតែសរសេរអក្សរធំជានិច្ច!)\n\n✍️ លំហាត់អនុវត្ត (Practice Exercise)៖\nចូរកំណត់ថាតើពាក្យណាខ្លះជានាមក្នុងប្រយោគនេះ៖ 'The smart student reads many interesting books in the library.'"
  },
  {
    "topic": "Plural Nouns (នាមពហុវចនៈ)",
    "kh": "📖 និយមន័យ និងការប្រើប្រាស់ (Definition & Usage)៖\nនាមពហុវចនៈ (Plural Nouns) គឺជានាមដែលបញ្ជាក់ពីចំនួនចាប់ពី ២ ឡើងទៅ។\n\n📐 រូបមន្ត និងក្បួនវេយ្យាករណ៍ (Formulas & Rules)៖\n១. នាមទូទៅថែម 's': book -> books, student -> students\n២. បញ្ចប់ដោយ s, ss, sh, ch, x, z ថែម 'es': bus -> buses, watch -> watches, box -> boxes\n៣. ព្យញ្ជនៈ + y ប្តូរទៅ 'ies': city -> cities, baby -> babies\n៤. បញ្ចប់ដោយ f/fe ប្តូរទៅ 'ves': knife -> knives, leaf -> leaves\n៥. នាមមិនទៀងទាត់ (Irregular): man -> men, woman -> women, child -> children, tooth -> teeth, person -> people\n\n💡 ឧទាហរណ៍ជាក់ស្តែង & ការបកប្រែជាភាសាខ្មែរ (Practical Examples with Khmer Translation)៖\n1. 🇬🇧 Many international tourists visit ancient temples every year.\n   🇰🇭 (ភ្ញៀវទេសចរអន្តរជាតិជាច្រើនមកទស្សនាប្រាសាទបុរាណជារៀងរាល់ឆ្នាំ។)\n\n2. 🇬🇧 The children are playing happily in the school garden.\n   🇰🇭 (ក្មេងៗកំពុងលេងកម្សាន្តយ៉ាងសប្បាយរីករាយនៅក្នុងសួនច្បារសាលារៀន។)\n\n3. 🇬🇧 We need three new laptops and five computer mice for our new staff.\n   🇰🇭 (យើងក្រោមកុំព្យូទ័រយួរដៃថ្មីចំនួន ៣ គ្រឿង និង Mouse ចំនួន ៥ សម្រាប់បុគ្គលិកថ្មីរបស់យើង។)\n\n4. 🇬🇧 The chef sharpened all the kitchen knives before preparing dinner.\n   🇰🇭 (មេចុងភៅបានសំលៀងកាំបិតផ្ទះបាយទាំងអស់ មុនពេលរៀបចំអាហារពេលល្ងាច។)\n\n⚠️ កំហុសញឹកញាប់ដែលត្រូវចៀសវាង (Common Mistakes)៖\n❌ ខុស: There are five childs in the classroom.\n✅ ត្រូវ: There are five children in the classroom. (child -> children មិនថែម s ទេ)\n\n✍️ លំហាត់អនុវត្ត (Practice Exercise)៖\nចូរប្តូរនាមខាងក្រោមទៅជាពហុវចនៈ៖ city, tomato, leaf, woman, box."
  },
  {
    "topic": "Uncountable Nouns (នាមរាប់មិនបាន)",
    "kh": "📖 និយមន័យ និងការប្រើប្រាស់ (Definition & Usage)៖\nនាមរាប់មិនបាន (Uncountable Nouns) គឺជានាមដែលមិនអាចរាប់ជាចំនួន ១, ២, ៣ ដោយផ្ទាល់បានទេ គ្មានទម្រង់ពហុវចនៈ និងប្រើជាមួយកិរិយាសព្ទឯកវចនៈ។\n\n📐 រូបមន្ត និងក្បួនវេយ្យាករណ៍ (Formulas & Rules)៖\n• វត្ថុរាវ៖ water, milk, coffee, tea, oil\n• គ្រាប់ល្អិតៗ៖ rice, sugar, salt, sand, flour\n• គំនិត និងព័ត៌មាន៖ information, advice, news, knowledge, homework\n• នាមជាក្រុម៖ money, furniture, luggage, equipment\n• របៀបរាប់៖ ត្រូវប្រើពាក្យរង្វាស់ (a bottle of water, a piece of advice, a cup of tea, a bag of rice)\n\n💡 ឧទាហរណ៍ជាក់ស្តែង & ការបកប្រែជាភាសាខ្មែរ (Practical Examples with Khmer Translation)៖\n1. 🇬🇧 Can you give me some helpful advice about learning spoken English?\n   🇰🇭 (តើអ្នកអាចផ្តល់ដំបូន្មានល្អៗខ្លះដល់ខ្ញុំអំពីការរៀននិយាយភាសាអង់គ្លេសបានទេ?)\n\n2. 🇬🇧 She drinks three cups of green tea every day for her health.\n   🇰🇭 (នាងពិសាទឹកតែបៃតង ៣ ពែងរាល់ថ្ងៃដើម្បីសុខភាពរបស់នាង។)\n\n3. 🇬🇧 We don't have much information about the new scholarship yet.\n   🇰🇭 (ពួកយើងមិនទាន់មានព័ត៌មានច្រើនអំពីអាហារូបករណ៍ថ្មីនេះនៅឡើយទេ។)\n\n4. 🇬🇧 Drinking enough clean water keeps your mind and body active.\n   🇰🇭 (ការទទួលទានទឹកស្អាតឱ្យបានគ្រប់គ្រាន់ ជួយឱ្យខួរក្បាល និងរាងកាយរបស់អ្នកស្វាហាប់។)\n\n⚠️ កំហុសញឹកញាប់ដែលត្រូវចៀសវាង (Common Mistakes)៖\n❌ ខុស: I have many homeworks today.\n✅ ត្រូវ: I have a lot of homework today. (homework រាប់មិនបាន មិនអាចថែម s ឡើយ)\n\n✍️ លំហាត់អនុវត្ត (Practice Exercise)៖\nចូរជ្រើសរើសពាក្យត្រឹមត្រូវ៖ 'He gave me (a / some) useful information.'"
  },
  {
    "topic": "Possessive Nouns (នាមកម្មសិទ្ធិ)",
    "kh": "📖 និយមន័យ និងការប្រើប្រាស់ (Definition & Usage)៖\nនាមកម្មសិទ្ធិ ប្រើសម្រាប់បញ្ជាក់ភាពជាម្ចាស់លើវត្ថុ ឬទំនាក់ទំនងរវាងមនុស្ស ដោយប្រើសញ្ញា Apostrophe ('s)។\n\n📐 រូបមន្ត និងក្បួនវេយ្យាករណ៍ (Formulas & Rules)៖\n១. នាមឯកវចនៈ៖ Noun + 's (the teacher's book, Sokha's car)\n២. នាមពហុវចនៈមាន s៖ Noun + ' (the students' classroom, my parents' house)\n៣. នាមពហុវចនៈគ្មាន s៖ Noun + 's (the children's toys, women's rights)\n\n💡 ឧទាហរណ៍ជាក់ស្តែង & ការបកប្រែជាភាសាខ្មែរ (Practical Examples with Khmer Translation)៖\n1. 🇬🇧 The company's CEO announced a major expansion plan today.\n   🇰🇭 (នាយកប្រតិបត្តិ (CEO) របស់ក្រុមហ៊ុនបានប្រកាសពីផែនការពង្រីកអាជីវកម្មដ៏ធំនៅថ្ងៃនេះ។)\n\n2. 🇬🇧 I borrowed my brother's motorcycle to go to the supermarket.\n   🇰🇭 (ខ្ញុំបានខ្ចីម៉ូតូរបស់បងប្រុសខ្ញុំ ដើម្បីទៅផ្សារទំនើប។)\n\n3. 🇬🇧 The students' examination results were exceptionally outstanding.\n   🇰🇭 (លទ្ធផលប្រឡងរបស់សិស្សានុសិស្សទាំងឡាយគឺល្អប្រសើរគួរឱ្យកត់សម្គាល់។)\n\n4. 🇬🇧 Sarah's English presentation won the first prize in the competition.\n   🇰🇭 (បទបង្ហាញភាសាអង់គ្លេសរបស់សារ៉ាបានឈ្នះរង្វាន់លេខមួយក្នុងការប្រកួត។)\n\n⚠️ កំហុសញឹកញាប់ដែលត្រូវចៀសវាង (Common Mistakes)៖\n❌ ខុស: The phone of my sister is new.\n✅ ត្រូវ: My sister's phone is new. (ប្រើ 's គឺមានលក្ខណៈធម្មជាតិ និងត្រឹមត្រូវជាង)\n\n✍️ លំហាត់អនុវត្ត (Practice Exercise)៖\nចូរសរសេរជាទម្រង់កម្មសិទ្ធិ៖ 'The house belonging to Mr. David'."
  },
  {
    "topic": "Compound Nouns (នាមសមាស)",
    "kh": "📖 និយមន័យ និងការប្រើប្រាស់ (Definition & Usage)៖\nនាមសមាស គឺជាការរួមផ្សំគ្នានៃពាក្យពីរ ឬច្រើន ដើម្បីបង្កើតបានជានាមថ្មីមួយដែលមានអត្ថន័យជាក់លាក់។\n\n📐 រូបមន្ត និងក្បួនវេយ្យាករណ៍ (Formulas & Rules)៖\n• Noun + Noun: bedroom (បន្ទប់គេង), toothbrush (ច្រាសដុសធ្មេញ), textbook (សៀវភៅពុម្ព)\n• Adjective + Noun: blackboard (ក្តារខៀន), smartphone (ទូរស័ព្ទឆ្លាតវៃ), full moon (ព្រះចន្ទពេញបូណ៌មី)\n• Verb(-ing) + Noun: swimming pool (អាងហែលទឹក), washing machine (ម៉ាស៊ីនបោកខោអាវ)\n\n💡 ឧទាហរណ៍ជាក់ស្តែង & ការបកប្រែជាភាសាខ្មែរ (Practical Examples with Khmer Translation)៖\n1. 🇬🇧 Don't forget to pack your toothbrush and toothpaste for the trip.\n   🇰🇭 (កុំភ្លេចច្រកច្រាសដុសធ្មេញ និងថ្នាំដុសធ្មេញរបស់អ្នកសម្រាប់ដំណើរកម្សាន្ត។)\n\n2. 🇬🇧 Our hotel features an Olympic-sized swimming pool on the rooftop.\n   🇰🇭 (សណ្ឋាគាររបស់យើងមានអាងហែលទឹកខ្នាតអូឡាំពិកនៅលើដំបូលអគារ។)\n\n3. 🇬🇧 She bought a new washing machine that saves energy and water.\n   🇰🇭 (នាងបានទិញម៉ាស៊ីនបោកគក់ថ្មីមួយដែលសន្សំសំចៃថាមពល និងទឹក។)\n\n4. 🇬🇧 You need a valid passport and your boarding pass at the airport gate.\n   🇰🇭 (អ្នកត្រូវការលិខិតឆ្លងដែនដែលមានសុពលភាព និងសំបុត្រឡើងយន្តហោះនៅច្រកទ្វារព្រលានយន្តហោះ។)\n\n⚠️ កំហុសញឹកញាប់ដែលត្រូវចៀសវាង (Common Mistakes)៖\n❌ ខុស: swimming-pools (ពហុវចនៈត្រូវថែមលើនាមចុងក្រោយ)\n✅ ត្រូវ: swimming pools\n\n✍️ លំហាត់អនុវត្ត (Practice Exercise)៖\nចូរស្វែងរកនាមសមាស ៣ ពាក្យដែលអ្នកប្រើប្រាស់ជារៀងរាល់ថ្ងៃ។"
  },
  {
    "topic": "Adjectives (គុណនាម)",
    "kh": "📖 និយមន័យ និងការប្រើប្រាស់ (Definition & Usage)៖\nគុណនាម (Adjectives) គឺជាពាក្យដែលប្រើសម្រាប់បញ្ជាក់ន័យ បន្ថែមលក្ខណៈ ឬពណ៌នាអំពីនាម (Noun)។\n\n📐 រូបមន្ត និងក្បួនវេយ្យាករណ៍ (Formulas & Rules)៖\n• ទីតាំងទី១៖ នៅពីមុខនាម (Adjective + Noun): a beautiful girl, a big house\n• ទីតាំងទី២៖ នៅខាងក្រោយកិរិយាសព្ទ To Be ឬ Linking Verbs: She is smart, The soup tastes delicious\n\n💡 ឧទាហរណ៍ជាក់ស្តែង & ការបកប្រែជាភាសាខ្មែរ (Practical Examples with Khmer Translation)៖\n1. 🇬🇧 She is an intelligent and hardworking student.\n   🇰🇭 (នាងគឺជាសិស្សស្រីដ៏ឆ្លាតវៃ និងឧស្សាហ៍ព្យាយាមម្នាក់។)\n\n2. 🇬🇧 The new marketing strategy was extremely successful.\n   🇰🇭 (យុទ្ធសាស្ត្រទីផ្សារថ្មីគឺទទួលបានជោគជ័យយ៉ាងខ្លាំង។)\n\n3. 🇬🇧 Cambodia has many wonderful historic destinations to explore.\n   🇰🇭 (ប្រទេសកម្ពុជាមានគោលដៅប្រវត្តិសាស្ត្រដ៏អស្ចារ្យជាច្រើនសម្រាប់ទស្សនាកម្សាន្ត។)\n\n4. 🇬🇧 This cup of hot coffee smells absolutely amazing.\n   🇰🇭 (កាហ្វេក្តៅមួយពែងនេះមានក្លិនឈ្ងុយគួរឱ្យចង់ពិសាខ្លាំងណាស់។)\n\n⚠️ កំហុសញឹកញាប់ដែលត្រូវចៀសវាង (Common Mistakes)៖\n❌ ខុស: She has eyes blue. (ភាសាខ្មែរដាក់ក្រោយ តែអង់គ្លេសគុណនាមត្រូវនៅមុខនាម!)\n✅ ត្រូវ: She has blue eyes.\n\n✍️ លំហាត់អនុវត្ត (Practice Exercise)៖\nចូរបញ្ចូលគុណនាម 'expensive' ទៅក្នុងប្រយោគ៖ 'He drives a car.'"
  },
  {
    "topic": "Comparative Adjectives (គុណនាមប្រៀបធៀប)",
    "kh": "📖 និយមន័យ និងការប្រើប្រាស់ (Definition & Usage)៖\nគុណនាមកម្រិតប្រៀបធៀប ប្រើសម្រាប់ប្រៀបធៀបមនុស្ស ឬវត្ថុ ២ នាក់/២ យ៉ាង។\n\n📐 រូបមន្ត និងក្បួនវេយ្យាករណ៍ (Formulas & Rules)៖\n១. ព្យាង្គខ្លី (១ ព្យាង្គ)៖ adj + er + than (taller than, faster than, bigger than)\n២. ២ ព្យាង្គបញ្ចប់ដោយ y៖ adj(ier) + than (happier than, easier than)\n៣. ព្យាង្គវែង (២ ព្យាង្គឡើង)៖ more + adj + than (more expensive than, more beautiful than)\n៤. មិនទៀងទាត់ (Irregular)៖ good -> better than, bad -> worse than, far -> further than\n\n💡 ឧទាហរណ៍ជាក់ស្តែង & ការបកប្រែជាភាសាខ្មែរ (Practical Examples with Khmer Translation)៖\n1. 🇬🇧 Studying English online with StudyAI is much faster than self-study alone.\n   🇰🇭 (ការរៀនភាសាអង់គ្លេសអនឡាញជាមួយ StudyAI គឺលឿនជាងការរៀនតែឯងឆ្ងាយណាស់។)\n\n2. 🇬🇧 This modern electric car is more economical than my old gasoline vehicle.\n   🇰🇭 (រថយន្តអគ្គិសនីទំនើបនេះគឺសន្សំសំចៃជាងរថយន្តសាំងចាស់របស់ខ្ញុំ។)\n\n3. 🇬🇧 Today's weather is significantly cooler than yesterday's scorching heat.\n   🇰🇭 (អាកាសធាតុថ្ងៃនេះគឺត្រជាក់ជាងកម្តៅដ៏ក្តៅគគុកកាលពីម្សិលមិញយ៉ាងខ្លាំង។)\n\n4. 🇬🇧 Sophea speaks English better than anyone else in our study group.\n   🇰🇭 (សុភា និយាយភាសាអង់គ្លេសបានល្អជាងអ្នកណាៗទាំងអស់នៅក្នុងក្រុមសិក្សារបស់យើង។)\n\n⚠️ កំហុសញឹកញាប់ដែលត្រូវចៀសវាង (Common Mistakes)៖\n❌ ខុស: This phone is more cheap than that one.\n✅ ត្រូវ: This phone is cheaper than that one. (cheap ជាព្យាង្គខ្លី ប្រើ cheaper មិនមែន more cheap ទេ)\n\n✍️ លំហាត់អនុវត្ត (Practice Exercise)៖\nចូរប្តូរគុណនាម 'difficult' ទៅជាទម្រង់ប្រៀបធៀប។"
  },
  {
    "topic": "Superlative Adjectives (គុណនាមបំផុត)",
    "kh": "📖 និយមន័យ និងការប្រើប្រាស់ (Definition & Usage)៖\nគុណនាមកម្រិតបំផុត ប្រើដើម្បីប្រៀបធៀបមនុស្ស ឬវត្ថុ ចាប់ពី ៣ ឡើងទៅ ដើម្បីបង្ហាញថាអ្នកណា ឬរបស់ណាដែលលើសគេបង្អស់។\n\n📐 រូបមន្ត និងក្បួនវេយ្យាករណ៍ (Formulas & Rules)៖\n១. ព្យាង្គខ្លី៖ the + adj-est (the tallest, the fastest, the biggest)\n២. បញ្ចប់ដោយ y៖ the + adj-iest (the easiest, the happiest)\n៣. ព្យាង្គវែង៖ the most + adj (the most expensive, the most comfortable)\n៤. មិនទៀងទាត់៖ good -> the best, bad -> the worst, far -> the furthest\n\n💡 ឧទាហរណ៍ជាក់ស្តែង & ការបកប្រែជាភាសាខ្មែរ (Practical Examples with Khmer Translation)៖\n1. 🇬🇧 Angkor Wat is the most famous historical attraction in Cambodia.\n   🇰🇭 (ប្រាសាទអង្គរវត្ត គឺជាតំបន់ទាក់ទាញប្រវត្តិសាស្ត្រដ៏ល្បីល្បាញបំផុតនៅក្នុងប្រទេសកម្ពុជា។)\n\n2. 🇬🇧 He is the most experienced software developer on our entire team.\n   🇰🇭 (គាត់គឺជាអ្នកអភិវឌ្ឍន៍សូហ្វវែរដែលមានបទពិសោធន៍ច្រើនជាងគេបំផុតនៅក្នុងក្រុមទាំងមូលរបស់យើង។)\n\n3. 🇬🇧 This is the best opportunity you will ever get to learn English.\n   🇰🇭 (នេះគឺជាឱកាសដ៏ល្អបំផុតដែលអ្នកនឹងទទួលបានដើម្បីរៀនភាសាអង់គ្លេស។)\n\n4. 🇬🇧 What is the highest mountain peak in Southeast Asia?\n   🇰🇭 (តើកំពូលភ្នំណាដែលខ្ពស់ជាងគេបំផុតនៅតំបន់អាស៊ីអាគ្នេយ៍?)\n\n⚠️ កំហុសញឹកញាប់ដែលត្រូវចៀសវាង (Common Mistakes)៖\n❌ ខុស: He is smartest boy in the school.\n✅ ត្រូវ: He is the smartest boy in the school. (ត្រូវតែមានពាក្យ 'the' នៅពីមុខជានិច្ច!)\n\n✍️ លំហាត់អនុវត្ត (Practice Exercise)៖\nចូរបង្កើតល្បះមួយដោយប្រើ 'the most interesting'."
  },
  {
    "topic": "Personal Pronouns (សព្វនាមបុគ្គល)",
    "kh": "📖 និយមន័យ និងការប្រើប្រាស់ (Definition & Usage)៖\nសព្វនាមបុគ្គលជាប្រធាន (Subject Pronouns) ប្រើសម្រាប់ជំនួសនាមជាប្រធាននៃល្បះ ដើម្បីកុំឱ្យនិយាយឈ្មោះដដែលៗ។\n\n📐 រូបមន្ត និងក្បួនវេយ្យាករណ៍ (Formulas & Rules)៖\n• បុរសទី១ (អ្នកនិយាយ): I (ខ្ញុំ), We (ពួកយើង)\n• បុរសទី២ (អ្នកស្តាប់): You (អ្នក/អ្នកទាំងអស់គ្នា)\n• បុរសទី៣ (អ្នកដែលគេនិយាយដល់): He (គាត់ - បុរស), She (នាង - ស្ត្រី), It (វា - វត្ថុ/សត្វ), They (ពួកគេ)\n\n💡 ឧទាហរណ៍ជាក់ស្តែង & ការបកប្រែជាភាសាខ្មែរ (Practical Examples with Khmer Translation)៖\n1. 🇬🇧 I practice English speaking for thirty minutes every single day.\n   🇰🇭 (ខ្ញុំហ្វឹកហាត់និយាយភាសាអង់គ្លេសរយៈពេល ៣០ នាទីជារៀងរាល់ថ្ងៃ។)\n\n2. 🇬🇧 She is a skilled accountant working for a leading multinational bank.\n   🇰🇭 (នាងគឺជាគណនេយ្យករដ៏ជំនាញម្នាក់ដែលធ្វើការឱ្យធនាគារពហុជាតិឈានមុខគេមួយ។)\n\n3. 🇬🇧 They are organizing a major business summit in Siem Reap next week.\n   🇰🇭 (ពួកគេកំពុងរៀបចំកិច្ចប្រជុំកំពូលធុរកិច្ចដ៏ធំមួយនៅខេត្តសៀមរាបនៅសប្តាហ៍ក្រោយ។)\n\n4. 🇬🇧 We are determined to achieve our fluency goals this year.\n   🇰🇭 (ពួកយើងប្តេជ្ញាចិត្តសម្រេចឱ្យបាននូវគោលដៅនិយាយភាសាអង់គ្លេសឱ្យស្ទាត់ក្នុងឆ្នាំនេះ។)\n\n⚠️ កំហុសញឹកញាប់ដែលត្រូវចៀសវាង (Common Mistakes)៖\n❌ ខុស: My friend and me went to the library.\n✅ ត្រូវ: My friend and I went to the library. (ពេលធ្វើជាប្រធាន ត្រូវប្រើ I មិនមែន me ទេ)\n\n✍️ លំហាត់អនុវត្ត (Practice Exercise)៖\nចូរជំនួសពាក្យ 'Sokha and Dara' ដោយសព្វនាមសមស្រប។"
  },
  {
    "topic": "Object Pronouns (សព្វនាមកម្មបទ)",
    "kh": "📖 និយមន័យ និងការប្រើប្រាស់ (Definition & Usage)៖\nសព្វនាមកម្មបទ (Object Pronouns) ប្រើសម្រាប់ជំនួសនាមដែលទទួលរងអំពើ ហើយស្ថិតនៅខាងក្រោយកិរិយាសព្ទ ឬធ្នាក់ (Prepositions)។\n\n📐 រូបមន្ត និងក្បួនវេយ្យាករណ៍ (Formulas & Rules)៖\n• I -> me (ខ្ញុំ)\n• You -> you (អ្នក)\n• We -> us (ពួកយើង)\n• They -> them (ពួកគេ)\n• He -> him (គាត់)\n• She -> her (នាង)\n• It -> it (វា)\n\n💡 ឧទាហរណ៍ជាក់ស្តែង & ការបកប្រែជាភាសាខ្មែរ (Practical Examples with Khmer Translation)៖\n1. 🇬🇧 The teacher gave us detailed feedback on our writing assignments.\n   🇰🇭 (លោកគ្រូបានផ្តល់មតិកែលម្អយ៉ាងក្បោះក្បាយដល់ពួកយើងលើកិច្ចការតែងសេចក្តី។)\n\n2. 🇬🇧 I saw him at the international business conference yesterday.\n   🇰🇭 (ខ្ញុំបានឃើញគាត់នៅក្នុងសន្និសីទធុរកិច្ចអន្តរជាតិកាលពីម្សិលមិញ។)\n\n3. 🇬🇧 Could you please send the updated contract to them as soon as possible?\n   🇰🇭 (តើអ្នកអាចមេត្តាផ្ញើកិច្ចសន្យាដែលបានកែសម្រួលរួចទៅកាន់ពួកគេឱ្យបានឆាប់បំផុតបានទេ?)\n\n4. 🇬🇧 She called me last night to discuss the weekend study schedule.\n   🇰🇭 (នាងបានទូរស័ព្ទមកខ្ញុំកាលពីយប់មិញដើម្បីពិភាក្សាអំពីកាលវិភាគរៀនចុងសប្តាហ៍។)\n\n⚠️ កំហុសញឹកញាប់ដែលត្រូវចៀសវាង (Common Mistakes)៖\n❌ ខុស: He gave the book to I.\n✅ ត្រូវ: He gave the book to me. (នៅក្រោយធ្នាក់ 'to' ត្រូវប្រើកម្មបទ 'me')\n\n✍️ លំហាត់អនុវត្ត (Practice Exercise)៖\nចូរជ្រើសរើសសព្វនាមត្រឹមត្រូវ៖ 'Please contact (he / him) immediately.'"
  },
  {
    "topic": "Reflexive Pronouns (សព្វនាមខ្លួនឯង)",
    "kh": "📖 និយមន័យ និងការប្រើប្រាស់ (Definition & Usage)៖\nសព្វនាមបញ្ជាក់ខ្លួនឯង បញ្ចប់ដោយ '-self' (ឯកវចនៈ) ឬ '-selves' (ពហុវចនៈ) ប្រើនៅពេលដែលប្រធាន និងកម្មបទជាមនុស្សតែមួយ ឬប្រើដើម្បីបញ្ជាក់ការធ្វើដោយខ្លួនឯងផ្ទាល់។\n\n📐 រូបមន្ត និងក្បួនវេយ្យាករណ៍ (Formulas & Rules)៖\n• myself (ខ្លួនខ្ញុំផ្ទាល់), yourself (ខ្លួនអ្នក), himself (ខ្លួនគាត់), herself (ខ្លួននាង), itself (ខ្លួនវា)\n• ourselves (ខ្លួនពួកយើង), yourselves (ខ្លួនអ្នកទាំងអស់គ្នា), themselves (ខ្លួនពួកគេ)\n\n💡 ឧទាហរណ៍ជាក់ស្តែង & ការបកប្រែជាភាសាខ្មែរ (Practical Examples with Khmer Translation)៖\n1. 🇬🇧 I built this entire online learning web application myself.\n   🇰🇭 (ខ្ញុំបានបង្កើតវេបសាយកម្មវិធីសិក្សាអនឡាញទាំងមូលនេះដោយខ្លួនខ្ញុំផ្ទាល់។)\n\n2. 🇬🇧 She taught herself how to code and speak English fluently.\n   🇰🇭 (នាងបានបង្រៀនខ្លួនឯងឱ្យចេះសរសេរកូដ និងនិយាយភាសាអង់គ្លេសបានយ៉ាងស្ទាត់។)\n\n3. 🇬🇧 Take good care of yourselves during the rainy season.\n   🇰🇭 (សូមថែរក្សាខ្លួនអ្នកទាំងអស់គ្នាឱ្យបានល្អក្នុងអំឡុងរដូវវស្សានេះ។)\n\n4. 🇬🇧 He looked at himself in the mirror and smiled with confidence.\n   🇰🇭 (គាត់បានសម្លឹងមើលខ្លួនគាត់នៅក្នុងកញ្ចក់ ហើយញញឹមប្រកបដោយទំនុកចិត្ត។)\n\n⚠️ កំហុសញឹកញាប់ដែលត្រូវចៀសវាង (Common Mistakes)៖\n❌ ខុស: They did the homework by theirselves.\n✅ ត្រូវ: They did the homework by themselves. (ពាក្យត្រូវគឺ themselves មិនមែន theirselves ទេ)\n\n✍️ លំហាត់អនុវត្ត (Practice Exercise)៖\nចូរជ្រើសរើសពាក្យត្រឹមត្រូវ៖ 'She made this delicious cake (her / herself).'"
  },
  {
    "topic": "Demonstrative Pronouns (សព្វនាមចង្អុល)",
    "kh": "📖 និយមន័យ និងការប្រើប្រាស់ (Definition & Usage)៖\nសព្វនាមចង្អុល ប្រើសម្រាប់ចង្អុលបង្ហាញវត្ថុ ឬមនុស្ស ដោយផ្អែកលើចម្ងាយ (ជិត ឬ ឆ្ងាយ) និងចំនួន (ឯកវចនៈ ឬ ពហុវចនៈ)។\n\n📐 រូបមន្ត និងក្បួនវេយ្យាករណ៍ (Formulas & Rules)៖\n• This (នេះ): ឯកវចនៈ នៅជិត (This is my book)\n• That (នោះ): ឯកវចនៈ នៅឆ្ងាយ (That is a tall building)\n• These (ទាំងនេះ): ពហុវចនៈ នៅជិត (These are my keys)\n• Those (ទាំងនោះ): ពហុវចនៈ នៅឆ្ងាយ (Those are beautiful flowers)\n\n💡 ឧទាហរណ៍ជាក់ស្តែង & ការបកប្រែជាភាសាខ្មែរ (Practical Examples with Khmer Translation)៖\n1. 🇬🇧 This is the most helpful English grammar guide I have ever read.\n   🇰🇭 (នេះគឺជាសៀវភៅណែនាំវេយ្យាករណ៍ភាសាអង់គ្លេសដែលមានប្រយោជន៍បំផុតដែលខ្ញុំធ្លាប់បានអាន។)\n\n2. 🇬🇧 That company over there has been operating in Phnom Penh since 2010.\n   🇰🇭 (ក្រុមហ៊ុននៅទីនោះបានដំណើរការនៅក្នុងរាជធានីភ្នំពេញតាំងពីឆ្នាំ ២០១០ មកម្ល៉េះ។)\n\n3. 🇬🇧 These sentences are great examples of professional workplace communication.\n   🇰🇭 (ប្រយោគទាំងនេះគឺជាឧទាហរណ៍ដ៏អស្ចារ្យនៃការប្រាស្រ័យទាក់ទងក្នុងកន្លែងធ្វើការប្រកបដោយវិជ្ជាជីវៈ។)\n\n4. 🇬🇧 Those mountains in the distance look magnificent during sunrise.\n   🇰🇭 (ជួរភ្នំទាំងនោះនៅឯនាយមើលទៅពិតជាអស្ចារ្យណាស់ក្នុងអំឡុងពេលព្រះអាទិត្យរះ។)\n\n⚠️ កំហុសញឹកញាប់ដែលត្រូវចៀសវាង (Common Mistakes)៖\n❌ ខុស: These car is expensive.\n✅ ត្រូវ: This car is expensive. (ឬ These cars are expensive)\n\n✍️ លំហាត់អនុវត្ត (Practice Exercise)៖\nចូរជ្រើសរើសពាក្យត្រឹមត្រូវ៖ '(This / These) documents are strictly confidential.'"
  },
  {
    "topic": "Indefinite Pronouns (សព្វនាមមិនកំណត់)",
    "kh": "📖 និយមន័យ និងការប្រើប្រាស់ (Definition & Usage)៖\nសព្វនាមមិនកំណត់ ប្រើសម្រាប់សំដៅលើមនុស្ស វត្ថុ ឬទីកន្លែង ដោយមិនបញ្ជាក់ច្បាស់លាស់។ ភាគច្រើនចាត់ទុកជាឯកវចនៈ និងប្រើជាមួយកិរិយាសព្ទឯកវចនៈ (Singular Verb)។\n\n📐 រូបមន្ត និងក្បួនវេយ្យាករណ៍ (Formulas & Rules)៖\n• មនុស្ស៖ someone / somebody (នរណាម្នាក់), anyone / anybody (នរណាម្នាក់/អ្នកណា), everyone / everybody (អ្នករាល់គ្នា), no one / nobody (គ្មាននរណាម្នាក់)\n• វត្ថុ៖ something (អ្វីមួយ), anything (អ្វីមួយ), everything (អ្វីៗទាំងអស់), nothing (គ្មានអ្វីសោះ)\n• ទីកន្លែង៖ somewhere (កន្លែងណាមួយ), anywhere, everywhere, nowhere\n\n💡 ឧទាហរណ៍ជាក់ស្តែង & ការបកប្រែជាភាសាខ្មែរ (Practical Examples with Khmer Translation)៖\n1. 🇬🇧 Everyone in our online class is working hard to improve their speaking.\n   🇰🇭 (អ្នករាល់គ្នានៅក្នុងថ្នាក់អនឡាញរបស់យើងកំពុងខិតខំប្រឹងប្រែងដើម្បីកែលម្អការនិយាយរបស់ពួកគេ។)\n\n2. 🇬🇧 Is there anyone here who can translate this document into English?\n   🇰🇭 (តើមាននរណាម្នាក់នៅទីនេះដែលអាចបកប្រែឯកសារនេះទៅជាភាសាអង់គ្លេសបានទេ?)\n\n3. 🇬🇧 There is something wrong with the internet connection this afternoon.\n   🇰🇭 (មានអ្វីមួយមិនប្រក្រតីជាមួយការតភ្ជាប់អ៊ីនធឺណិតនៅរសៀលនេះ។)\n\n4. 🇬🇧 Nobody knows the exact secret to success without hard work.\n   🇰🇭 (គ្មាននរណាម្នាក់ដឹងពីអាថ៌កំបាំងនៃភាពជោគជ័យដោយគ្មានការខិតខំប្រឹងប្រែងនោះឡើយ។)\n\n⚠️ កំហុសញឹកញាប់ដែលត្រូវចៀសវាង (Common Mistakes)៖\n❌ ខុស: Everyone are happy today.\n✅ ត្រូវ: Everyone is happy today. (Everyone ចាត់ទុកជាឯកវចនៈ ត្រូវប្រើ 'is')\n\n✍️ លំហាត់អនុវត្ត (Practice Exercise)៖\nចូរជ្រើសរើសកិរិយាសព្ទត្រឹមត្រូវ៖ 'Somebody (has / have) left their umbrella here.'"
  },
  {
    "topic": "Present Simple Tense",
    "kh": "📖 និយមន័យ និងការប្រើប្រាស់ (Definition & Usage)៖\nបច្ចុប្បន្នកាលធម្មតា ប្រើសម្រាប់ទម្លាប់ប្រចាំថ្ងៃ ការពិតទូទៅ ឬច្បាប់ធម្មជាតិ។\n\n📐 រូបមន្ត និងក្បួនវេយ្យាករណ៍ (Formulas & Rules)៖\n(+) S + V1(s/es) + O\n(-) S + do/does not + V1 + O\n(?) Do/Does + S + V1 + O?\n(I/You/We/They ប្រើ V1 / do | He/She/It ប្រើ V1(s/es) / does)\n\n💡 ឧទាហរណ៍ជាក់ស្តែង & ការបកប្រែជាភាសាខ្មែរ (Practical Examples with Khmer Translation)៖\n1. 🇬🇧 He studies English vocabulary and grammar for one hour every morning.\n   🇰🇭 (គាត់រៀនវាក្យសព្ទ និងវេយ្យាករណ៍ភាសាអង់គ្លេសរយៈពេលមួយម៉ោងជារៀងរាល់ព្រឹក។)\n\n2. 🇬🇧 She doesn't drink coffee after 4:00 PM because it affects her sleep.\n   🇰🇭 (នាងមិនពិសាកាហ្វេក្រោយម៉ោង ៤:០០ រសៀលនោះទេ ពីព្រោះវាប៉ះពាល់ដល់ការគេងរបស់នាង។)\n\n3. 🇬🇧 Do you practice English conversation with your classmates every week?\n   🇰🇭 (តើអ្នកហ្វឹកហាត់ការសន្ទនាភាសាអង់គ្លេសជាមួយមិត្តរួមថ្នាក់ជារៀងរាល់សប្តាហ៍ដែរឬទេ?)\n\n4. 🇬🇧 Water boils at 100 degrees Celsius at standard atmospheric pressure.\n   🇰🇭 (ទឹកពុះនៅសីតុណ្ហភាព ១០០ អង្សាសេក្នុងកម្រិតសម្ពាធបរិយាកាសស្តង់ដារ។)\n\n⚠️ កំហុសញឹកញាប់ដែលត្រូវចៀសវាង (Common Mistakes)៖\n❌ ខុស: She go to market every Sunday.\n✅ ត្រូវ: She goes to market every Sunday. (កិរិយាសព្ទជាមួយ She ត្រូវថែម es)\n\n✍️ លំហាត់អនុវត្ត (Practice Exercise)៖\nចូរប្តូរប្រយោគនេះជាទម្រង់បដិសេធ៖ 'He likes spicy food.'"
  },
  {
    "topic": "Present Continuous Tense",
    "kh": "📖 និយមន័យ និងការប្រើប្រាស់ (Definition & Usage)៖\nបច្ចុប្បន្នកាលកំពុងបន្ត ប្រើសម្រាប់សកម្មភាពដែលកំពុងតែកើតឡើងនៅពេលកំពុងនិយាយ ឬផែនការអនាគតជិត។\n\n📐 រូបមន្ត និងក្បួនវេយ្យាករណ៍ (Formulas & Rules)៖\n(+) S + am/is/are + V-ing + O\n(-) S + am not/isn't/aren't + V-ing + O\n(?) Am/Is/Are + S + V-ing + O?\n(Signal words: now, right now, at the moment, currently, Look!, Listen!)\n\n💡 ឧទាហរណ៍ជាក់ស្តែង & ការបកប្រែជាភាសាខ្មែរ (Practical Examples with Khmer Translation)៖\n1. 🇬🇧 I am currently preparing for the international English proficiency test.\n   🇰🇭 (បច្ចុប្បន្ននេះ ខ្ញុំកំពុងតែរៀបចំខ្លួនសម្រាប់ការប្រឡងសមត្ថភាពភាសាអង់គ្លេសកម្រិតអន្តរជាតិ។)\n\n2. 🇬🇧 Listen! The professor is explaining an important concept right now.\n   🇰🇭 (ស្តាប់ន៎! សាស្ត្រាចារ្យកំពុងតែពន្យល់អំពីទ្រឹស្តីដ៏សំខាន់មួយនៅពេលនេះ។)\n\n3. 🇬🇧 They aren't working today because it is a national public holiday.\n   🇰🇭 (ពួកគេមិនកំពុងធ្វើការនៅថ្ងៃនេះទេ ពីព្រោះវាជាថ្ងៃឈប់សម្រាកបុណ្យជាតិ។)\n\n4. 🇬🇧 We are meeting our marketing partners at the café at 2:00 PM today.\n   🇰🇭 (ពួកយើងនឹងជួបដៃគូទីផ្សារនៅហាងកាហ្វេនៅម៉ោង ២:០០ រសៀលថ្ងៃនេះ។)\n\n⚠️ កំហុសញឹកញាប់ដែលត្រូវចៀសវាង (Common Mistakes)៖\n❌ ខុស: I am wanting to go home now.\n✅ ត្រូវ: I want to go home now. (កិរិយាសព្ទ want មិនប្រើក្នុងទម្រង់ Continuous ទេ)\n\n✍️ លំហាត់អនុវត្ត (Practice Exercise)៖\nចូរប្តូរប្រយោគនេះទៅជា Present Continuous៖ 'She (write) an email to the client now.'"
  },
  {
    "topic": "Past Simple Tense",
    "kh": "📖 និយមន័យ និងការប្រើប្រាស់ (Definition & Usage)៖\nអតីតកាលធម្មតា ប្រើសម្រាប់សកម្មភាពដែលបានកើតឡើង និងបានបញ្ចប់ទាំងស្រុងក្នុងអតីតកាល ដោយមានពេលវេលាជាក់លាក់។\n\n📐 រូបមន្ត និងក្បួនវេយ្យាករណ៍ (Formulas & Rules)៖\n(+) S + V2 + O\n(-) S + did not (didn't) + V1 + O\n(?) Did + S + V1 + O?\n(Signal words: yesterday, last night, last year, 2 days ago, in 2021)\n\n💡 ឧទាហរណ៍ជាក់ស្តែង & ការបកប្រែជាភាសាខ្មែរ (Practical Examples with Khmer Translation)៖\n1. 🇬🇧 We launched our online English academy platform three months ago.\n   🇰🇭 (ពួកយើងបានចាប់ផ្តើមដំណើរការវេទិកាសាលាភាសាអង់គ្លេសអនឡាញកាលពី ៣ ខែមុន។)\n\n2. 🇬🇧 She didn't attend the business seminar yesterday due to heavy traffic.\n   🇰🇭 (នាងមិនបានចូលរួមសិក្ខាសាលាធុរកិច្ចកាលពីម្សិលមិញទេ ដោយសារការកកស្ទះចរាចរណ៍ខ្លាំង។)\n\n3. 🇬🇧 Did you receive the official certificate after passing the final exam?\n   🇰🇭 (តើអ្នកបានទទួលវិញ្ញាបនបត្រផ្លូវការបន្ទាប់ពីប្រឡងជាប់ការប្រឡងបញ្ចប់វគ្គដែរឬទេ?)\n\n4. 🇬🇧 They went to Siem Reap and visited many magnificent temples.\n   🇰🇭 (ពួកគេបានទៅខេត្តសៀមរាប ហើយបានទស្សនាប្រាសាទដ៏អស្ចារ្យជាច្រើន។)\n\n⚠️ កំហុសញឹកញាប់ដែលត្រូវចៀសវាង (Common Mistakes)៖\n❌ ខុស: Did you saw the movie last night?\n✅ ត្រូវ: Did you see the movie last night? (មាន Did ត្រូវប្រើ V1 គឺ see មិនមែន saw ទេ)\n\n✍️ លំហាត់អនុវត្ត (Practice Exercise)៖\nចូរប្តូរ 'buy' ទៅជា Past Simple (V2) ក្នុងប្រយោគ៖ 'He ___ a new car yesterday.'"
  },
  {
    "topic": "Past Continuous Tense",
    "kh": "📖 និយមន័យ និងការប្រើប្រាស់ (Definition & Usage)៖\nអតីតកាលកំពុងបន្ត ប្រើសម្រាប់សកម្មភាពកំពុងកើតឡើងនៅពេលជាក់លាក់ក្នុងអតីតកាល ឬកំពុងកើតឡើងស្រាប់តែមានសកម្មភាពមួយទៀតចូលមកកាត់ផ្តាច់ (When / While)។\n\n📐 រូបមន្ត និងក្បួនវេយ្យាករណ៍ (Formulas & Rules)៖\n(+) S + was/were + V-ing + O\n(-) S + wasn't/weren't + V-ing + O\n(?) Was/Were + S + V-ing + O?\n(I/He/She/It ប្រើ was | You/We/They ប្រើ were)\n\n💡 ឧទាហរណ៍ជាក់ស្តែង & ការបកប្រែជាភាសាខ្មែរ (Practical Examples with Khmer Translation)៖\n1. 🇬🇧 I was practicing my English pronunciation when the power suddenly went out.\n   🇰🇭 (ខ្ញុំកំពុងតែហ្វឹកហាត់បញ្ចេញសំឡេងភាសាអង់គ្លេស ស្រាប់តែដាច់ចរន្តអគ្គិសនីភ្លាមៗ។)\n\n2. 🇬🇧 At 9:00 PM yesterday, we were reviewing the monthly marketing report.\n   🇰🇭 (នៅម៉ោង ៩:០០ យប់មិញ ពួកយើងកំពុងត្រួតពិនិត្យរបាយការណ៍ទីផ្សារប្រចាំខែ។)\n\n3. 🇬🇧 While Sophea was cooking dinner, her brother was doing his homework.\n   🇰🇭 (ខណៈពេលដែលសុភាកំពុងចម្អិនអាហារពេលល្ងាច ប្អូនប្រុសរបស់នាងកំពុងធ្វើកិច្ចការផ្ទះ។)\n\n4. 🇬🇧 Were you sleeping when I called you last night?\n   🇰🇭 (តើអ្នកកំពុងគេងលក់ឬ នៅពេលដែលខ្ញុំទូរស័ព្ទទៅអ្នកកាលពីយប់មិញ?)\n\n⚠️ កំហុសញឹកញាប់ដែលត្រូវចៀសវាង (Common Mistakes)៖\n❌ ខុស: They was watching television when I arrived.\n✅ ត្រូវ: They were watching television when I arrived. (They ប្រើ were)\n\n✍️ លំហាត់អនុវត្ត (Practice Exercise)៖\nចូរបំពេញចន្លោះ៖ 'I (study) ___ when he knocked on the door.'"
  },
  {
    "topic": "Present Perfect Tense",
    "kh": "📖 និយមន័យ និងការប្រើប្រាស់ (Definition & Usage)៖\nបច្ចុប្បន្នកាលបរិបូរណ៍ ប្រើសម្រាប់សកម្មភាពកើតក្នុងអតីតកាលបន្តដល់បច្ចុប្បន្ន បទពិសោធន៍ជីវិត ឬសកម្មភាពទើបនឹងបញ្ចប់ថ្មីៗ។\n\n📐 រូបមន្ត និងក្បួនវេយ្យាករណ៍ (Formulas & Rules)៖\n(+) S + have/has + V3 + O\n(-) S + haven't/hasn't + V3 + O\n(?) Have/Has + S + V3 + O?\n(Signal words: already, just, yet, ever, never, since, for)\n\n💡 ឧទាហរណ៍ជាក់ស្តែង & ការបកប្រែជាភាសាខ្មែរ (Practical Examples with Khmer Translation)៖\n1. 🇬🇧 I have studied English on this online platform for over six months.\n   🇰🇭 (ខ្ញុំបានរៀនភាសាអង់គ្លេសនៅលើវេទិកាអនឡាញនេះអស់រយៈពេលជាង ៦ ខែមកហើយ។)\n\n2. 🇬🇧 She has already achieved an advanced score on her English assessment.\n   🇰🇭 (នាងសម្រេចបានពិន្ទុកម្រិតខ្ពស់ក្នុងការវាយតម្លៃភាសាអង់គ្លេសរបស់នាងរួចរាល់ហើយ។)\n\n3. 🇬🇧 Have you ever traveled to an English-speaking country for study?\n   🇰🇭 (តើអ្នកធ្លាប់បានធ្វើដំណើរទៅកាន់ប្រទេសនិយាយភាសាអង់គ្លេសដើម្បីសិក្សាដែរឬទេ?)\n\n4. 🇬🇧 We haven't finished designing the new user interface yet.\n   🇰🇭 (ពួកយើងមិនទាន់បានបញ្ចប់ការរចនាផ្ទាំងកម្មវិធីថ្មីនៅឡើយទេ។)\n\n⚠️ កំហុសញឹកញាប់ដែលត្រូវចៀសវាង (Common Mistakes)៖\n❌ ខុស: I have seen him yesterday.\n✅ ត្រូវ: I saw him yesterday. (បើមាន yesterday ត្រូវប្រើ Past Simple មិនមែន Present Perfect ទេ)\n\n✍️ លំហាត់អនុវត្ត (Practice Exercise)៖\nចូរជ្រើសរើសចម្លើយត្រឹមត្រូវ៖ 'She has (work / worked) here since 2020.'"
  },
  {
    "topic": "Present Perfect Continuous",
    "kh": "📖 និយមន័យ និងការប្រើប្រាស់ (Definition & Usage)៖\nបច្ចុប្បន្នកាលបរិបូរណ៍កំពុងបន្ត ប្រើដើម្បីសង្កត់ធ្ងន់លើ 'រយៈពេល' នៃសកម្មភាពដែលបានចាប់ផ្តើមតាំងពីអតីតកាល ហើយកំពុងតែបន្តធ្វើឥតឈប់ឈររហូតមកដល់បច្ចុប្បន្ន។\n\n📐 រូបមន្ត និងក្បួនវេយ្យាករណ៍ (Formulas & Rules)៖\n(+) S + have/has + been + V-ing + O\n(-) S + haven't/hasn't + been + V-ing + O\n(?) Have/Has + S + been + V-ing + O?\n(How long, for, since, all day)\n\n💡 ឧទាហរណ៍ជាក់ស្តែង & ការបកប្រែជាភាសាខ្មែរ (Practical Examples with Khmer Translation)៖\n1. 🇬🇧 I have been learning English conversation for two hours without taking a break.\n   🇰🇭 (ខ្ញុំបាននិងកំពុងរៀនការសន្ទនាភាសាអង់គ្លេសអស់រយៈពេល ២ ម៉ោងហើយដោយមិនបានសម្រាកឡើយ។)\n\n2. 🇬🇧 How long have you been working as an online English instructor?\n   🇰🇭 (តើអ្នកបាននិងកំពុងធ្វើការជាគ្រូបង្រៀនភាសាអង់គ្លេសអនឡាញអស់រយៈពេលប៉ុន្មានហើយ?)\n\n3. 🇬🇧 It has been raining continuously since early this morning.\n   🇰🇭 (ភ្លៀងបាននិងកំពុងធ្លាក់ឥតឈប់ឈរតាំងពីព្រលឹមស្រាងៗមកម្ល៉េះ។)\n\n4. 🇬🇧 She has been preparing for her master's degree scholarship all year.\n   🇰🇭 (នាងបាននិងកំពុងរៀបចំខ្លួនសម្រាប់អាហារូបករណ៍ថ្នាក់អនុបណ្ឌិតពេញមួយឆ្នាំនេះ។)\n\n⚠️ កំហុសញឹកញាប់ដែលត្រូវចៀសវាង (Common Mistakes)៖\n❌ ខុស: I have been knowing him for five years.\n✅ ត្រូវ: I have known him for five years. (Stative verbs ដូចជា know ប្រើក្នុង Present Perfect ធម្មតា)\n\n✍️ លំហាត់អនុវត្ត (Practice Exercise)៖\nចូរបំពេញចន្លោះ៖ 'They have been (practice) ___ speaking English all morning.'"
  },
  {
    "topic": "Past Perfect Tense",
    "kh": "📖 និយមន័យ និងការប្រើប្រាស់ (Definition & Usage)៖\nអតីតកាលបរិបូរណ៍ ប្រើសម្រាប់សកម្មភាពមួយដែលបានកើតឡើង និងបានបញ្ចប់មុនសកម្មភាពមួយទៀតក្នុងអតីតកាល (The earlier past action)។\n\n📐 រូបមន្ត និងក្បួនវេយ្យាករណ៍ (Formulas & Rules)៖\n(+) S + had + V3 + O\n(-) S + hadn't + V3 + O\n(?) Had + S + V3 + O?\n(ក្បួន: Had + V3 កើតមុន | Past Simple V2 កើតក្រោយ | Before, After, By the time)\n\n💡 ឧទាហរណ៍ជាក់ស្តែង & ការបកប្រែជាភាសាខ្មែរ (Practical Examples with Khmer Translation)៖\n1. 🇬🇧 When I arrived at the airport, the flight had already departed.\n   🇰🇭 (នៅពេលដែលខ្ញុំបានទៅដល់ព្រលានយន្តហោះ ជើងហោះហើរបានចេញដំណើររួចស្រេចទៅហើយ។)\n\n2. 🇬🇧 She had completed all her assignments before she went to bed last night.\n   🇰🇭 (នាងបានបញ្ចប់កិច្ចការទាំងអស់របស់នាងរួចរាល់ មុនពេលនាងចូលគេងកាលពីយប់មិញ។)\n\n3. 🇬🇧 By the time the manager came, the team had solved the technical problem.\n   🇰🇭 (នៅពេលដែលអ្នកគ្រប់គ្រងមកដល់ ក្រុមការងារបានដោះស្រាយបញ្ហាបច្ចេកទេសរួចរាល់បាត់ទៅហើយ។)\n\n4. 🇬🇧 Had you studied English before you started using this AI application?\n   🇰🇭 (តើអ្នកធ្លាប់បានរៀនភាសាអង់គ្លេសពីមុនមកទេ មុនពេលអ្នកចាប់ផ្តើមប្រើប្រាស់កម្មវិធី AI នេះ?)\n\n⚠️ កំហុសញឹកញាប់ដែលត្រូវចៀសវាង (Common Mistakes)៖\n❌ ខុស: After he had ate breakfast, he went to school.\n✅ ត្រូវ: After he had eaten breakfast, he went to school. (had + V3 គឺ eaten មិនមែន ate ទេ)\n\n✍️ លំហាត់អនុវត្ត (Practice Exercise)៖\nចូរជ្រើសរើសទម្រង់ត្រូវ៖ 'She (had finished / finished) the test before time was up.'"
  },
  {
    "topic": "Future Simple Tense",
    "kh": "📖 និយមន័យ និងការប្រើប្រាស់ (Definition & Usage)៖\nអនាគតកាលធម្មតា (Will) ប្រើសម្រាប់ការសម្រេចចិត្តភ្លាមៗ ការទស្សន៍ទាយ ឬការសន្យា។\n\n📐 រូបមន្ត និងក្បួនវេយ្យាករណ៍ (Formulas & Rules)៖\n(+) S + will + V1 + O\n(-) S + will not (won't) + V1 + O\n(?) Will + S + V1 + O?\n(Tomorrow, next week, soon, I think, I promise)\n\n💡 ឧទាហរណ៍ជាក់ស្តែង & ការបកប្រែជាភាសាខ្មែរ (Practical Examples with Khmer Translation)៖\n1. 🇬🇧 I will help you practice your English interview questions tomorrow.\n   🇰🇭 (ខ្ញុំនឹងជួយអ្នកហ្វឹកហាត់សំណួរសម្ភាសន៍ការងារជាភាសាអង់គ្លេសនៅថ្ងៃស្អែក។)\n\n2. 🇬🇧 Don't worry about the examination; you will do great!\n   🇰🇭 (កុំបារម្ភចំពោះការប្រឡងអី អ្នកនឹងធ្វើវាបានយ៉ាងល្អប្រសើរ!)\n\n3. 🇬🇧 Will artificial intelligence change the way we learn foreign languages?\n   🇰🇭 (តើបញ្ញាសិប្បនិម្មិតនឹងផ្លាស់ប្តូររបៀបដែលយើងរៀនភាសាបរទេសដែរឬទេ?)\n\n4. 🇬🇧 We will send you the confirmation email and study schedule right away.\n   🇰🇭 (ពួកយើងនឹងផ្ញើអ៊ីមែលបញ្ជាក់ និងកាលវិភាគសិក្សាជូនអ្នកភ្លាមៗ។)\n\n⚠️ កំហុសញឹកញាប់ដែលត្រូវចៀសវាង (Common Mistakes)៖\n❌ ខុស: I will to call you tomorrow.\n✅ ត្រូវ: I will call you tomorrow. (ក្រោយ will ត្រូវប្រើ V1 គ្មាន 'to' ឡើយ)\n\n✍️ លំហាត់អនុវត្ត (Practice Exercise)៖\nចូរប្តូរប្រយោគនេះជាទម្រង់បដិសេធ៖ 'He will join the meeting.'"
  },
  {
    "topic": "Future Continuous Tense",
    "kh": "📖 និយមន័យ និងការប្រើប្រាស់ (Definition & Usage)៖\nអនាគតកាលកំពុងបន្ត ប្រើសម្រាប់សកម្មភាពដែលនឹងកំពុងតែកើតឡើងនៅចំណុចពេលវេលាជាក់លាក់ណាមួយក្នុងអនាគត។\n\n📐 រូបមន្ត និងក្បួនវេយ្យាករណ៍ (Formulas & Rules)៖\n(+) S + will be + V-ing + O\n(-) S + won't be + V-ing + O\n(?) Will + S + be + V-ing + O?\n(At this time tomorrow, at 8 PM tonight)\n\n💡 ឧទាហរណ៍ជាក់ស្តែង & ការបកប្រែជាភាសាខ្មែរ (Practical Examples with Khmer Translation)៖\n1. 🇬🇧 At this time tomorrow, I will be attending an international English conference.\n   🇰🇭 (នៅពេលនេះថ្ងៃស្អែក ខ្ញុំនឹងកំពុងចូលរួមសន្និសីទភាសាអង់គ្លេសអន្តរជាតិមួយ។)\n\n2. 🇬🇧 Don't call him at 9:00 PM tonight; he will be teaching his online class.\n   🇰🇭 (កុំទូរស័ព្ទទៅគាត់នៅម៉ោង ៩:០០ យប់នេះ គាត់នឹងកំពុងបង្រៀនថ្នាក់អនឡាញរបស់គាត់។)\n\n3. 🇬🇧 Will you be working at the office all day this coming Saturday?\n   🇰🇭 (តើអ្នកនឹងកំពុងធ្វើការនៅការិយាល័យពេញមួយថ្ងៃនៅថ្ងៃសៅរ៍ខាងមុខនេះឬ?)\n\n⚠️ កំហុសញឹកញាប់ដែលត្រូវចៀសវាង (Common Mistakes)៖\n❌ ខុស: I will be sleep at midnight.\n✅ ត្រូវ: I will be sleeping at midnight. (will be + V-ing)\n\n✍️ លំហាត់អនុវត្ត (Practice Exercise)៖\nចូរបំពេញចន្លោះ៖ 'This time next week, we will be (travel) ___ to Thailand.'"
  },
  {
    "topic": "Be Going To (ផែនការ)",
    "kh": "📖 និយមន័យ និងការប្រើប្រាស់ (Definition & Usage)៖\nទម្រង់ Be going to ប្រើសម្រាប់ផែនការដែលបានសម្រេចចិត្ត ឬគ្រោងទុករួចរាល់ ឬការទស្សន៍ទាយដែលមានភស្តុតាងជាក់ស្តែងនៅចំពោះមុខ។\n\n📐 រូបមន្ត និងក្បួនវេយ្យាករណ៍ (Formulas & Rules)៖\n(+) S + am/is/are + going to + V1 + O\n(-) S + am not/isn't/aren't + going to + V1 + O\n(?) Am/Is/Are + S + going to + V1 + O?\n\n💡 ឧទាហរណ៍ជាក់ស្តែង & ការបកប្រែជាភាសាខ្មែរ (Practical Examples with Khmer Translation)៖\n1. 🇬🇧 I am going to enroll in the advanced English speaking diploma course next Monday.\n   🇰🇭 (ខ្ញុំនឹងចុះឈ្មោះចូលរៀនវគ្គសញ្ញាបត្រសន្ទនាភាសាអង់គ្លេសកម្រិតខ្ពស់នៅថ្ងៃចន្ទសប្តាហ៍ក្រោយ។)\n\n2. 🇬🇧 Look at the dark clouds! It is definitely going to rain very heavily.\n   🇰🇭 (មើលពពកខ្មៅនោះន៎! វានឹងធ្លាក់ភ្លៀងយ៉ាងខ្លាំងជាក់ជាមិនខាន។)\n\n3. 🇬🇧 What are you going to do after you achieve your English certificate?\n   🇰🇭 (តើអ្នកនឹងគ្រោងធ្វើអ្វីបន្ទាប់ពីអ្នកទទួលបានវិញ្ញាបនបត្រភាសាអង់គ្លេសរបស់អ្នក?)\n\n⚠️ កំហុសញឹកញាប់ដែលត្រូវចៀសវាង (Common Mistakes)៖\n❌ ខុស: I am going to buying a new phone.\n✅ ត្រូវ: I am going to buy a new phone. (going to + V1)\n\n✍️ លំហាត់អនុវត្ត (Practice Exercise)៖\nចូរបង្កើតល្បះមួយដែលបង្ហាញពីផែនការរបស់អ្នកនៅចុងសប្តាហ៍នេះដោយប្រើ 'be going to'."
  },
  {
    "topic": "Modal Verbs: Can & Could",
    "kh": "📖 និយមន័យ និងការប្រើប្រាស់ (Definition & Usage)៖\nCan ប្រើសម្រាប់សមត្ថភាពបច្ចុប្បន្ន ការសុំអនុញ្ញាត ឬលទ្ធភាព។ Could ប្រើសម្រាប់សមត្ថភាពអតីតកាល ឬការស្នើសុំដោយគួរសមខ្ពស់។\n\n📐 រូបមន្ត និងក្បួនវេយ្យាករណ៍ (Formulas & Rules)៖\nSubject + can / could + V1 (infinitive) + Object\n(ចំណាំ៖ ក្រោយ modal verbs ត្រូវប្រើ V1 សុទ្ធជានិច្ច គ្មាន to គ្មាន s)\n\n💡 ឧទាហរណ៍ជាក់ស្តែង & ការបកប្រែជាភាសាខ្មែរ (Practical Examples with Khmer Translation)៖\n1. 🇬🇧 Could you please speak a little slower so I can understand you better?\n   🇰🇭 (តើអ្នកអាចមេត្តានិយាយឱ្យរាងយឺតបន្តិចបានទេ ដើម្បីឱ្យខ្ញុំអាចស្តាប់អ្នកបានកាន់តែច្បាស់? (ការស្នើសុំគួរសម))\n\n2. 🇬🇧 She can speak English, French, and Khmer with remarkable fluency.\n   🇰🇭 (នាងអាចនិយាយភាសាអង់គ្លេស បារាំង និងខ្មែរបានយ៉ាងស្ទាត់ជំនាញគួរឱ្យកោតសរសើរ។ (សមត្ថភាព))\n\n3. 🇬🇧 When he was just seven years old, he could play the piano beautifully.\n   🇰🇭 (កាលពីគាត់ទើបតែអាយុ ៧ ឆ្នាំ គាត់អាចលេងព្យាណូបានយ៉ាងពីរោះរណ្តំ។ (អតីតកាល))\n\n⚠️ កំហុសញឹកញាប់ដែលត្រូវចៀសវាង (Common Mistakes)៖\n❌ ខុស: Could you please to help me?\n✅ ត្រូវ: Could you please help me? (គ្មាន 'to' ទេ)\n\n✍️ លំហាត់អនុវត្ត (Practice Exercise)៖\nចូរប្រើ 'Could you please...' ដើម្បីសុំឱ្យនរណាម្នាក់បើកបង្អួច។"
  },
  {
    "topic": "Modal Verbs: May & Might",
    "kh": "📖 និយមន័យ និងការប្រើប្រាស់ (Definition & Usage)៖\nMay និង Might ប្រើសម្រាប់បង្ហាញពីលទ្ធភាព (Possibility) ថាអ្វីមួយអាចនឹងកើតឡើង ឬ May ប្រើសម្រាប់ការសុំការអនុញ្ញាតផ្លូវការ។\n\n📐 រូបមន្ត និងក្បួនវេយ្យាករណ៍ (Formulas & Rules)៖\nSubject + may / might + V1 + Object\n(May: ប្រហែលជា ៥០% | Might: លទ្ធភាពទាបជាងបន្តិច ៣០-៤០%)\n\n💡 ឧទាហរណ៍ជាក់ស្តែង & ការបកប្រែជាភាសាខ្មែរ (Practical Examples with Khmer Translation)៖\n1. 🇬🇧 May I come in and ask a few questions about the online English program?\n   🇰🇭 (តើខ្ញុំអាចសុំការអនុញ្ញាតចូល និងសួរសំណួរមួយចំនួនអំពីកម្មវិធីភាសាអង់គ្លេសអនឡាញបានទេ? (សុំអនុញ្ញាតផ្លូវការ))\n\n2. 🇬🇧 Take an umbrella with you; it might rain later this afternoon.\n   🇰🇭 (យកឆ័ត្រតាមខ្លួនទៅ ក្រែងលោវាអាចនឹងភ្លៀងនៅរសៀលនេះ។ (លទ្ធភាព))\n\n3. 🇬🇧 She may join our study group tomorrow if she finishes her work on time.\n   🇰🇭 (នាងប្រហែលជាអាចចូលរួមក្រុមសិក្សារបស់យើងនៅថ្ងៃស្អែក ប្រសិនបើនាងបញ្ចប់ការងារទាន់ពេល។)\n\n⚠️ កំហុសញឹកញាប់ដែលត្រូវចៀសវាង (Common Mistakes)៖\n❌ ខុស: It might rains today.\n✅ ត្រូវ: It might rain today. (ក្រោយ might ប្រើ V1 សុទ្ធ)\n\n✍️ លំហាត់អនុវត្ត (Practice Exercise)៖\nចូរសរសេរប្រយោគមួយដោយប្រើ 'might' ដើម្បីបង្ហាញពីលទ្ធភាពអាកាសធាតុ។"
  },
  {
    "topic": "Modal Verbs: Must & Have to",
    "kh": "📖 និយមន័យ និងការប្រើប្រាស់ (Definition & Usage)៖\nMust និង Have to ប្រើសម្រាប់បង្ហាញពីភាពចាំបាច់ កាតព្វកិច្ច ឬច្បាប់តឹងរ៉ឹង។ Must not (ហាមដាច់ខាត) ខុសពី Don't have to (មិនបាច់ក៏បាន)។\n\n📐 រូបមន្ត និងក្បួនវេយ្យាករណ៍ (Formulas & Rules)៖\n• Must: កាតព្វកិច្ចផ្ទាល់ខ្លួន ឬច្បាប់តឹងរ៉ឹង\n• Have to: កាតព្វកិច្ចបង្ខំដោយកាលៈទេសៈខាងក្រៅ\n• Must not (Mustn't): ការហាមប្រាមដាច់ខាត (Prohibition)\n• Don't have to: គ្មានការបង្ខិតបង្ខំ (No obligation)\n\n💡 ឧទាហរណ៍ជាក់ស្តែង & ការបកប្រែជាភាសាខ្មែរ (Practical Examples with Khmer Translation)៖\n1. 🇬🇧 You must wear a helmet when riding a motorcycle in Cambodia for your safety.\n   🇰🇭 (អ្នកត្រូវតែពាក់មួកសុវត្ថិភាពនៅពេលជិះម៉ូតូក្នុងប្រទេសកម្ពុជាដើម្បីសុវត្ថិភាពរបស់អ្នក។)\n\n2. 🇬🇧 I have to wake up early tomorrow because my English class starts at 7:00 AM.\n   🇰🇭 (ខ្ញុំត្រូវតែក្រោកពីព្រលឹមនៅថ្ងៃស្អែក ពីព្រោះថ្នាក់រៀនភាសាអង់គ្លេសចាប់ផ្តើមម៉ោង ៧:០០ ព្រឹក។)\n\n3. 🇬🇧 You must not use your mobile phone during the final examination.\n   🇰🇭 (អ្នកមិនត្រូវប្រើប្រាស់ទូរស័ព្ទដៃក្នុងអំឡុងពេលប្រឡងបញ្ចប់វគ្គជាដាច់ខាត។)\n\n4. 🇬🇧 Tomorrow is Sunday, so we don't have to go to the office.\n   🇰🇭 (ថ្ងៃស្អែកជាថ្ងៃអាទិត្យ ដូច្នេះពួកយើងមិនចាំបាច់ទៅការិយាល័យនោះទេ។)\n\n⚠️ កំហុសញឹកញាប់ដែលត្រូវចៀសវាង (Common Mistakes)៖\n❌ ខុស: You mustn't to park here.\n✅ ត្រូវ: You mustn't park here.\n\n✍️ លំហាត់អនុវត្ត (Practice Exercise)៖\nចូរជ្រើសរើសពាក្យត្រឹមត្រូវ៖ 'Students (must not / don't have to) cheat in exams.'"
  },
  {
    "topic": "Modal Verbs: Should & Ought to",
    "kh": "📖 និយមន័យ និងការប្រើប្រាស់ (Definition & Usage)៖\nShould និង Ought to ប្រើសម្រាប់ផ្តល់ដំបូន្មាន ការណែនាំល្អៗ ឬការប្រាប់ពីអ្វីដែលសមរម្យគួរធ្វើ។\n\n📐 រូបមន្ត និងក្បួនវេយ្យាករណ៍ (Formulas & Rules)៖\nSubject + should / ought to + V1 + Object\n(Negative: shouldn't + V1)\n\n💡 ឧទាហរណ៍ជាក់ស្តែង & ការបកប្រែជាភាសាខ្មែរ (Practical Examples with Khmer Translation)៖\n1. 🇬🇧 You should practice speaking English every day if you want to become fluent.\n   🇰🇭 (អ្នកគួរតែហ្វឹកហាត់និយាយភាសាអង់គ្លេសជារៀងរាល់ថ្ងៃ ប្រសិនបើអ្នកចង់និយាយបានស្ទាត់ជំនាញ។)\n\n2. 🇬🇧 You look exhausted from working late. You ought to get some proper rest.\n   🇰🇭 (អ្នកមើលទៅហត់នឿយខ្លាំងណាស់ពីការធ្វើការដល់យប់ជ្រៅ។ អ្នកគួរតែសម្រាកឱ្យបានគ្រប់គ្រាន់។)\n\n3. 🇬🇧 Learners shouldn't be afraid of making mistakes when speaking English.\n   🇰🇭 (អ្នករៀនមិនគួរភ័យខ្លាចក្នុងការបង្កើតកំហុសនៅពេលនិយាយភាសាអង់គ្លេសនោះឡើយ។)\n\n⚠️ កំហុសញឹកញាប់ដែលត្រូវចៀសវាង (Common Mistakes)៖\n❌ ខុស: You should to practice speaking.\n✅ ត្រូវ: You should practice speaking. (ក្រោយ should គ្មាន 'to' ទេ)\n\n✍️ លំហាត់អនុវត្ត (Practice Exercise)៖\nចូរផ្តល់ដំបូន្មានដល់មិត្តភក្តិដែលឈឺក្បាលដោយប្រើ 'You should...'"
  },
  {
    "topic": "Adverbs of Manner (របៀប)",
    "kh": "📖 និយមន័យ និងការប្រើប្រាស់ (Definition & Usage)៖\nគុណកិរិយាប្រាប់របៀប បញ្ជាក់ថាតើសកម្មភាពនោះត្រូវបានធ្វើឡើងដោយរបៀបណា។ ភាគច្រើនបង្កើតដោយ គុណនាម + 'ly' (Adjective + ly)។\n\n📐 រូបមន្ត និងក្បួនវេយ្យាករណ៍ (Formulas & Rules)៖\n• quick -> quickly (យ៉ាងលឿន)\n• fluent -> fluently (យ៉ាងស្ទាត់ជំនាញ)\n• careful -> carefully (យ៉ាងប្រុងប្រយ័ត្ន)\n• មិនទៀងទាត់៖ good -> well (យ៉ាងល្អ), fast -> fast (យ៉ាងលឿន), hard -> hard (យ៉ាងលំបាក/ខ្លាំង)\n\n💡 ឧទាហរណ៍ជាក់ស្តែង & ការបកប្រែជាភាសាខ្មែរ (Practical Examples with Khmer Translation)៖\n1. 🇬🇧 After six months of dedicated practice, she speaks English very fluently.\n   🇰🇭 (បន្ទាប់ពីការហ្វឹកហាត់យ៉ាងយកចិត្តទុកដាក់អស់រយៈពេល ៦ ខែ នាងនិយាយភាសាអង់គ្លេសបានយ៉ាងស្ទាត់ជំនាញ។)\n\n2. 🇬🇧 Please drive carefully on the highway, especially when it is raining.\n   🇰🇭 (សូមមេត្តាបើកបរដោយប្រុងប្រយ័ត្ននៅលើផ្លូវល្បឿនលឿន ជាពិសេសនៅពេលមានភ្លៀងធ្លាក់។)\n\n3. 🇬🇧 He worked very hard to earn a full international scholarship.\n   🇰🇭 (គាត់បានខិតខំប្រឹងប្រែងធ្វើការយ៉ាងខ្លាំងដើម្បីដណ្តើមយកអាហារូបករណ៍អន្តរជាតិពេញថ្លៃ។)\n\n⚠️ កំហុសញឹកញាប់ដែលត្រូវចៀសវាង (Common Mistakes)៖\n❌ ខុស: She speaks English good.\n✅ ត្រូវ: She speaks English well. (ដើម្បីបញ្ជាក់ន័យឱ្យកិរិយាសព្ទ speaks ត្រូវប្រើគុណកិរិយា 'well' មិនមែន 'good' ទេ)\n\n✍️ លំហាត់អនុវត្ត (Practice Exercise)៖\nចូរប្តូរគុណនាម 'patient' ទៅជាគុណកិរិយាប្រាប់របៀប។"
  },
  {
    "topic": "Adverbs of Frequency (ភាពញឹកញាប់)",
    "kh": "📖 និយមន័យ និងការប្រើប្រាស់ (Definition & Usage)៖\nគុណកិរិយាប្រាប់ភាពញឹកញាប់ បញ្ជាក់ថាតើសកម្មភាពនោះកើតឡើងញឹកញាប់កម្រិតណា។\n\n📐 រូបមន្ត និងក្បួនវេយ្យាករណ៍ (Formulas & Rules)៖\nalways (100% ជានិច្ច), usually (80% ជាធម្មតា), often (60% ញឹកញាប់), sometimes (50% ជួនកាល), rarely/seldom (10% កម្រ), never (0% មិនដែល)\nទីតាំង៖ នៅពីមុខកិរិយាសព្ទធម្មតា តែនៅខាងក្រោយកិរិយាសព្ទ To Be!\n\n💡 ឧទាហរណ៍ជាក់ស្តែង & ការបកប្រែជាភាសាខ្មែរ (Practical Examples with Khmer Translation)៖\n1. 🇬🇧 I always review my vocabulary notes before going to sleep.\n   🇰🇭 (ខ្ញុំតែងតែរំលឹកកំណត់ចំណាំវាក្យសព្ទរបស់ខ្ញុំជានិច្ច មុនពេលចូលគេង។)\n\n2. 🇬🇧 She is always punctual and prepared for every business meeting.\n   🇰🇭 (នាងតែងតែទៀងទាត់ពេលវេលា និងត្រៀមខ្លួនរួចរាល់ជានិច្ចសម្រាប់ការប្រជុំអាជីវកម្មនីមួយៗ។ (នៅក្រោយ is))\n\n3. 🇬🇧 We sometimes study English together at the weekend café.\n   🇰🇭 (ពួកយើងជួនកាលរៀនភាសាអង់គ្លេសជាមួយគ្នានៅហាងកាហ្វេចុងសប្តាហ៍។)\n\n⚠️ កំហុសញឹកញាប់ដែលត្រូវចៀសវាង (Common Mistakes)៖\n❌ ខុស: I go always to school by bus.\n✅ ត្រូវ: I always go to school by bus. (នៅមុខកិរិយាសព្ទ go)\n\n✍️ លំហាត់អនុវត្ត (Practice Exercise)៖\nចូរដាក់ពាក្យ 'usually' ចូលក្នុងប្រយោគ៖ 'He eats breakfast at 7 AM.'"
  },
  {
    "topic": "Adverbs of Time (ពេលវេលា)",
    "kh": "📖 និយមន័យ និងការប្រើប្រាស់ (Definition & Usage)៖\nគុណកិរិយាប្រាប់ពេលវេលា បញ្ជាក់ថាតើសកម្មភាពនោះកើតឡើងនៅពេលណា (When)។\n\n📐 រូបមន្ត និងក្បួនវេយ្យាករណ៍ (Formulas & Rules)៖\nnow, today, yesterday, tomorrow, soon, recently, lately, already, yet\nទីតាំង៖ ជាធម្មតានៅចុងប្រយោគ ឬនៅដើមប្រយោគដើម្បីសង្កត់ធ្ងន់។\n\n💡 ឧទាហរណ៍ជាក់ស្តែង & ការបកប្រែជាភាសាខ្មែរ (Practical Examples with Khmer Translation)៖\n1. 🇬🇧 We will launch our new online learning mobile application soon.\n   🇰🇭 (ពួកយើងនឹងដាក់ឱ្យដំណើរការកម្មវិធីទូរស័ព្ទសិក្សាអនឡាញថ្មីរបស់យើងក្នុងពេលឆាប់ៗនេះ។)\n\n2. 🇬🇧 Recently, more and more Cambodian students are mastering English through AI.\n   🇰🇭 (ថ្មីៗនេះ សិស្សានុសិស្សកម្ពុជាកាន់តែច្រើនឡើងកំពុងចេះភាសាអង់គ្លេសយ៉ាងស្ទាត់តាមរយៈ AI។)\n\n3. 🇬🇧 I received the official admission letter from the university yesterday.\n   🇰🇭 (ខ្ញុំបានទទួលលិខិតផ្លូវការអនុញ្ញាតឱ្យចូលរៀនពីសាកលវិទ្យាល័យកាលពីម្សិលមិញ។)\n\n⚠️ កំហុសញឹកញាប់ដែលត្រូវចៀសវាង (Common Mistakes)៖\n❌ ខុស: I yesterday went to the market.\n✅ ត្រូវ: I went to the market yesterday. (ឬ Yesterday, I went to the market.)\n\n✍️ លំហាត់អនុវត្ត (Practice Exercise)៖\nចូរបង្កើតល្បះមួយដោយប្រើ 'recently'."
  },
  {
    "topic": "Adverbs of Place (ទីកន្លែង)",
    "kh": "📖 និយមន័យ និងការប្រើប្រាស់ (Definition & Usage)៖\nគុណកិរិយាប្រាប់ទីកន្លែង បញ្ជាក់ថាតើសកម្មភាពនោះកើតឡើងនៅឯណា (Where)។\n\n📐 រូបមន្ត និងក្បួនវេយ្យាករណ៍ (Formulas & Rules)៖\nhere (ទីនេះ), there (ទីនោះ), everywhere (គ្រប់ទីកន្លែង), nowhere (គ្មានកន្លែងណា), inside (ខាងក្នុង), outside (ខាងក្រៅ), upstairs, downstairs\n\n💡 ឧទាហរណ៍ជាក់ស្តែង & ការបកប្រែជាភាសាខ្មែរ (Practical Examples with Khmer Translation)៖\n1. 🇬🇧 Please come inside and have a seat; it is raining outside.\n   🇰🇭 (សូមអញ្ជើញចូលមកខាងក្នុង ហើយអង្គុយចុះ ខាងក្រៅកំពុងធ្លាក់ភ្លៀង។)\n\n2. 🇬🇧 With an internet connection, you can study English anywhere in the world.\n   🇰🇭 (ដោយគ្រាន់តែមានការភ្ជាប់អ៊ីនធឺណិត អ្នកអាចរៀនភាសាអង់គ្លេសនៅគ្រប់ទីកន្លែងក្នុងពិភពលោក។)\n\n3. 🇬🇧 I looked everywhere for my lost car keys, but I couldn't find them.\n   🇰🇭 (ខ្ញុំបានស្វែងរកកូនសោឡានដែលបាត់នៅគ្រប់ទីកន្លែង ប៉ុន្តែរកមិនឃើញសោះ។)\n\n⚠️ កំហុសញឹកញាប់ដែលត្រូវចៀសវាង (Common Mistakes)៖\n❌ ខុស: Please put here the box.\n✅ ត្រូវ: Please put the box here.\n\n✍️ លំហាត់អនុវត្ត (Practice Exercise)៖\nចូរបំពេញចន្លោះ៖ 'Sit (here / nowhere) next to me.'"
  },
  {
    "topic": "Prepositions of Time (ធ្នាក់ពេលវេលា)",
    "kh": "📖 និយមន័យ និងការប្រើប្រាស់ (Definition & Usage)៖\nធ្នាក់ពេលវេលា At, On, In ប្រើសម្រាប់បញ្ជាក់កាលវេលាជាក់លាក់។\n\n📐 រូបមន្ត និងក្បួនវេយ្យាករណ៍ (Formulas & Rules)៖\n• AT (ចំណុចម៉ោងជាក់លាក់, បុណ្យទាន): at 7 o'clock, at midnight, at noon, at Khmer New Year\n• ON (ថ្ងៃនៃសប្តាហ៍, កាលបរិច្ឆេទជាក់លាក់): on Monday, on July 15th, on my birthday\n• IN (ខែ, ឆ្នាំ, រដូវ, សតវត្សរ៍, ពេលនៃថ្ងៃ): in January, in 2026, in summer, in the morning/afternoon\n\n💡 ឧទាហរណ៍ជាក់ស្តែង & ការបកប្រែជាភាសាខ្មែរ (Practical Examples with Khmer Translation)៖\n1. 🇬🇧 Our online live class starts promptly at 8:00 PM every Monday and Friday.\n   🇰🇭 (ថ្នាក់ផ្សាយផ្ទាល់អនឡាញរបស់យើងចាប់ផ្តើមចំម៉ោង ៨:០០ យប់គត់រៀងរាល់ថ្ងៃចន្ទ និងថ្ងៃសុក្រ។)\n\n2. 🇬🇧 He graduated from the Royal University of Phnom Penh in 2024.\n   🇰🇭 (គាត់បានបញ្ចប់ការសិក្សាពីសាកលវិទ្យាល័យភូមិន្ទភ្នំពេញនៅក្នុងឆ្នាំ ២០២៤។)\n\n3. 🇬🇧 We are organizing a special study webinar on Sunday afternoon.\n   🇰🇭 (ពួកយើងកំពុងរៀបចំសិក្ខាសាលាលើបណ្តាញពិសេសមួយនៅរសៀលថ្ងៃអាទិត្យ។)\n\n⚠️ កំហុសញឹកញាប់ដែលត្រូវចៀសវាង (Common Mistakes)៖\n❌ ខុស: I was born in 15th May.\n✅ ត្រូវ: I was born on 15th May. (មានកាលបរិច្ឆេទថ្ងៃជាក់លាក់ ត្រូវប្រើ 'on')\n\n✍️ លំហាត់អនុវត្ត (Practice Exercise)៖\nចូរបំពេញធ្នាក់ត្រឹមត្រូវ៖ 'The train departs ___ 6:30 AM.'"
  },
  {
    "topic": "Prepositions of Place (ធ្នាក់ទីកន្លែង)",
    "kh": "📖 និយមន័យ និងការប្រើប្រាស់ (Definition & Usage)៖\nធ្នាក់ទីកន្លែង In, On, At ប្រើសម្រាប់បញ្ជាក់ទីតាំង និងទីកន្លែង។\n\n📐 រូបមន្ត និងក្បួនវេយ្យាករណ៍ (Formulas & Rules)៖\n• IN (ក្នុងទីធ្លាបិទជិត, ទីក្រុង, ប្រទេស): in the room, in Phnom Penh, in Cambodia\n• ON (នៅលើផ្ទៃ, លើផ្លូវ, លើជាន់): on the table, on Norodom Boulevard, on the 3rd floor\n• AT (ទីតាំងជាក់លាក់, អាសយដ្ឋានមានលេខផ្ទះ): at the bus stop, at the airport, at home, at work\n\n💡 ឧទាហរណ៍ជាក់ស្តែង & ការបកប្រែជាភាសាខ្មែរ (Practical Examples with Khmer Translation)៖\n1. 🇬🇧 Our main administrative headquarters is located in Phnom Penh.\n   🇰🇭 (ការិយាល័យកណ្តាលរដ្ឋបាលចម្បងរបស់យើងគឺស្ថិតនៅក្នុងរាជធានីភ្នំពេញ។)\n\n2. 🇬🇧 Please leave the signed registration documents on my desk.\n   🇰🇭 (សូមទុកឯកសារចុះឈ្មោះដែលបានចុះហត្ថលេខារួចនៅលើតុធ្វើការរបស់ខ្ញុំ។)\n\n3. 🇬🇧 I will meet you at the entrance of the National Museum at 3:00 PM.\n   🇰🇭 (ខ្ញុំនឹងជួបអ្នកនៅមាត់ទ្វារចូលសារមន្ទីរជាតិនៅម៉ោង ៣:០០ រសៀល។)\n\n⚠️ កំហុសញឹកញាប់ដែលត្រូវចៀសវាង (Common Mistakes)៖\n❌ ខុស: I live on Cambodia.\n✅ ត្រូវ: I live in Cambodia. (ប្រទេស ប្រើ 'in')\n\n✍️ លំហាត់អនុវត្ត (Practice Exercise)៖\nចូរបំពេញធ្នាក់ត្រឹមត្រូវ៖ 'He is waiting ___ the bus stop.'"
  },
  {
    "topic": "Articles: a, an, the",
    "kh": "📖 និយមន័យ និងការប្រើប្រាស់ (Definition & Usage)៖\nA និង An ជានិទស្សន្តសព្ទមិនកំណត់ (Indefinite Articles) ប្រើជាមួយនាមរាប់បានឯកវចនៈទូទៅ។ The ជានិទស្សន្តសព្ទកំណត់ (Definite Article) ប្រើជាមួយនាមជាក់លាក់ ឬរបស់តែមួយគត់ក្នុងលោក។\n\n📐 រូបមន្ត និងក្បួនវេយ្យាករណ៍ (Formulas & Rules)៖\n• A: ប្រើពីមុខពាក្យចាប់ផ្តើមដោយសំឡេងព្យញ្ជនៈ (a book, a university, a doctor)\n• AN: ប្រើពីមុខពាក្យចាប់ផ្តើមដោយសំឡេងស្រៈ a, e, i, o, u (an apple, an hour, an engineer)\n• THE: ប្រើជាមួយរបស់ជាក់លាក់ ដែលអ្នកនិយាយនិងអ្នកស្តាប់ស្គាល់ដូចគ្នា ឬរបស់តែមួយគត់ (the sun, the moon, the capital of Cambodia)\n\n💡 ឧទាហរណ៍ជាក់ស្តែង & ការបកប្រែជាភាសាខ្មែរ (Practical Examples with Khmer Translation)៖\n1. 🇬🇧 She is an experienced English teacher who holds a master's degree.\n   🇰🇭 (នាងគឺជាគ្រូបង្រៀនភាសាអង់គ្លេសដែលមានបទពិសោធន៍ម្នាក់ ដែលមានសញ្ញាបត្រអនុបណ្ឌិត។)\n\n2. 🇬🇧 The sun provides essential energy and light to our entire planet.\n   🇰🇭 (ព្រះអាទិត្យផ្តល់ថាមពល និងពន្លឺដ៏សំខាន់ដល់ភពផែនដីទាំងមូលរបស់យើង។)\n\n3. 🇬🇧 I bought a book yesterday. The book is about international leadership.\n   🇰🇭 (ខ្ញុំបានទិញសៀវភៅមួយក្បាលកាលពីម្សិលមិញ។ សៀវភៅនោះគឺស្តីអំពីភាពជាអ្នកដឹកនាំអន្តរជាតិ។)\n\n⚠️ កំហុសញឹកញាប់ដែលត្រូវចៀសវាង (Common Mistakes)៖\n❌ ខុស: It takes a hour to get there.\n✅ ត្រូវ: It takes an hour to get there. (hour បញ្ចេញសំឡេងស្រៈ /aʊər/ ត្រូវប្រើ 'an')\n\n✍️ លំហាត់អនុវត្ត (Practice Exercise)៖\nចូរជ្រើសរើស a ឬ an៖ 'He is ___ honest businessman.'"
  },
  {
    "topic": "Quantifiers: some, any",
    "kh": "📖 និយមន័យ និងការប្រើប្រាស់ (Definition & Usage)៖\nSome និង Any ប្រើសម្រាប់បញ្ជាក់បរិមាណខ្លះៗ។ Some ជាទូទៅប្រើក្នុងប្រយោគស្រប (+) ឬការស្នើសុំ/ផ្តល់ជូនគួរសម។ Any ជាទូទៅប្រើក្នុងប្រយោគបដិសេធ (-) និងប្រយោគសំណួរ (?)។\n\n📐 រូបមន្ត និងក្បួនវេយ្យាករណ៍ (Formulas & Rules)៖\n(+) Some: I have some questions.\n(-) Any: I don't have any money.\n(?) Any: Do you have any ideas?\n(Polite Offer / Request ប្រើ Some): Would you like some coffee?\n\n💡 ឧទាហរណ៍ជាក់ស្តែង & ការបកប្រែជាភាសាខ្មែរ (Practical Examples with Khmer Translation)៖\n1. 🇬🇧 We have some very important announcements to share with the students.\n   🇰🇭 (ពួកយើងមានសេចក្តីជូនដំណឹងដ៏សំខាន់មួយចំនួនដើម្បីចែករំលែកជាមួយសិស្សានុសិស្ស។)\n\n2. 🇬🇧 Do you have any questions about today's English grammar lesson?\n   🇰🇭 (តើអ្នកមានសំណួរអ្វីខ្លះទេអំពីមេរៀនវេយ្យាករណ៍ភាសាអង់គ្លេសថ្ងៃនេះ?)\n\n3. 🇬🇧 I didn't receive any notifications regarding the class schedule change.\n   🇰🇭 (ខ្ញុំមិនបានទទួលការជូនដំណឹងណាមួយទាក់ទងនឹងការផ្លាស់ប្តូរកាលវិភាគថ្នាក់រៀននោះទេ។)\n\n4. 🇬🇧 Would you like some fresh orange juice while waiting?\n   🇰🇭 (តើលោកអ្នកចង់ពិសាទឹកក្រូចស្រស់ខ្លះទេក្នុងអំឡុងពេលរង់ចាំ? (ការផ្តល់ជូនគួរសម))\n\n⚠️ កំហុសញឹកញាប់ដែលត្រូវចៀសវាង (Common Mistakes)៖\n❌ ខុស: I don't have some pens.\n✅ ត្រូវ: I don't have any pens. (បដិសេធប្រើ any)\n\n✍️ លំហាត់អនុវត្ត (Practice Exercise)៖\nចូរបំពេញ some ឬ any៖ 'Are there ___ vacant rooms in the hotel?'"
  },
  {
    "topic": "Quantifiers: much, many, a lot of",
    "kh": "📖 និយមន័យ និងការប្រើប្រាស់ (Definition & Usage)៖\nMany ប្រើជាមួយនាមរាប់បានពហុវចនៈ។ Much ប្រើជាមួយនាមរាប់មិនបាន (ភាគច្រើនក្នុងបដិសេធ និងសំណួរ)។ A lot of / lots of ប្រើបានទាំងពីរ ក្នុងប្រយោគស្រប។\n\n📐 រូបមន្ត និងក្បួនវេយ្យាករណ៍ (Formulas & Rules)៖\n• Many + Countable Plural: many students, many cars\n• Much + Uncountable: much money, much time, much water\n• A lot of + Countable/Uncountable: a lot of books, a lot of rice\n\n💡 ឧទាហរណ៍ជាក់ស្តែង & ការបកប្រែជាភាសាខ្មែរ (Practical Examples with Khmer Translation)៖\n1. 🇬🇧 There are many talented students enrolled in our online academy.\n   🇰🇭 (មានសិស្សានុសិស្សដែលមានទេពកោសល្យជាច្រើនបានចុះឈ្មោះចូលរៀនក្នុងបណ្ឌិត្យសភាអនឡាញរបស់យើង។)\n\n2. 🇬🇧 We don't have much time left before the exam begins.\n   🇰🇭 (ពួកយើងមិនមានពេលវេលាច្រើននៅសល់ឡើយ មុនពេលការប្រឡងចាប់ផ្តើម។)\n\n3. 🇬🇧 She has achieved a lot of success in her business career.\n   🇰🇭 (នាងសម្រេចបានជោគជ័យជាច្រើននៅក្នុងអាជីពអាជីវកម្មរបស់នាង។)\n\n⚠️ កំហុសញឹកញាប់ដែលត្រូវចៀសវាង (Common Mistakes)៖\n❌ ខុស: How much books did you buy?\n✅ ត្រូវ: How many books did you buy? (books រាប់បាន ប្រើ many)\n\n✍️ លំហាត់អនុវត្ត (Practice Exercise)៖\nចូរបំពេញ much ឬ many៖ 'How ___ money do you need?'"
  },
  {
    "topic": "Quantifiers: few, little",
    "kh": "📖 និយមន័យ និងការប្រើប្រាស់ (Definition & Usage)៖\nA few និង A little មានន័យថា 'មានខ្លះៗល្មមប្រើ' (វិជ្ជមាន)។ Few និង Little គ្មាន 'a' មានន័យថា 'ស្ទើរតែគ្មានសោះ មិនគ្រប់គ្រាន់' (អវិជ្ជមាន)។\n\n📐 រូបមន្ត និងក្បួនវេយ្យាករណ៍ (Formulas & Rules)៖\n• A few / Few + នាមរាប់បានពហុវចនៈ: a few friends (មានមិត្តភក្តិខ្លះ), few friends (ស្ទើរតែគ្មានមិត្ត)\n• A little / Little + នាមរាប់មិនបាន: a little water (មានទឹកខ្លះ), little water (ស្ទើរតែគ្មានទឹក)\n\n💡 ឧទាហរណ៍ជាក់ស្តែង & ការបកប្រែជាភាសាខ្មែរ (Practical Examples with Khmer Translation)៖\n1. 🇬🇧 I have a few questions about the final examination format.\n   🇰🇭 (ខ្ញុំមានសំណួរពីរបីទាក់ទងនឹងទម្រង់នៃការប្រឡងបញ្ចប់វគ្គ។ (រាប់បាន))\n\n2. 🇬🇧 He has a little free time this afternoon to help us review.\n   🇰🇭 (គាត់មានពេលទំនេរបន្តិចបន្តួចនៅរសៀលនេះដើម្បីជួយពួកយើងរំលឹកមេរៀន។ (រាប់មិនបាន))\n\n3. 🇬🇧 Unfortunately, few people attended the conference due to the storm.\n   🇰🇭 (ជាអកុសល មនុស្សតិចតួចបំផុត (ស្ទើរតែគ្មាន) បានចូលរួមសន្និសីទ ដោយសារតែព្យុះភ្លៀង។)\n\n⚠️ កំហុសញឹកញាប់ដែលត្រូវចៀសវាង (Common Mistakes)៖\n❌ ខុស: I have a few money in my wallet.\n✅ ត្រូវ: I have a little money in my wallet. (money រាប់មិនបាន ប្រើ a little)\n\n✍️ លំហាត់អនុវត្ត (Practice Exercise)៖\nចូរបំពេញ a few ឬ a little៖ 'Add ___ sugar to the coffee.'"
  },
  {
    "topic": "Conjunctions: and, but, or",
    "kh": "📖 និយមន័យ និងការប្រើប្រាស់ (Definition & Usage)៖\nពាក្យភ្ជាប់ And (និង - បន្ថែមគំនិតស្របគ្នា), But (ប៉ុន្តែ - បង្ហាញភាពផ្ទុយគ្នា), Or (ឬ - បង្ហាញជម្រើស)។\n\n📐 រូបមន្ត និងក្បួនវេយ្យាករណ៍ (Formulas & Rules)៖\n• And: I like apples and oranges.\n• But: He studied hard, but he failed.\n• Or: Do you prefer tea or coffee?\n\n💡 ឧទាហរណ៍ជាក់ស្តែង & ការបកប្រែជាភាសាខ្មែរ (Practical Examples with Khmer Translation)៖\n1. 🇬🇧 She works as a software engineer and teaches English on weekends.\n   🇰🇭 (នាងធ្វើការជាវិស្វករសូហ្វវែរផង និងបង្រៀនភាសាអង់គ្លេសនៅចុងសប្តាហ៍ផង។)\n\n2. 🇬🇧 He studied very hard for the test, but he still found the grammar challenging.\n   🇰🇭 (គាត់បានខិតខំប្រឹងប្រែងរៀនសូត្រខ្លាំងណាស់សម្រាប់ការប្រឡង ប៉ុន្តែគាត់នៅតែយល់ថាវេយ្យាករណ៍មានការលំបាក។)\n\n3. 🇬🇧 You can attend the class in person or join via the online live stream.\n   🇰🇭 (អ្នកអាចចូលរួមរៀនក្នុងថ្នាក់ផ្ទាល់ ឬចូលរួមតាមរយៈការផ្សាយផ្ទាល់តាមអនឡាញក៏បាន។)\n\n⚠️ កំហុសញឹកញាប់ដែលត្រូវចៀសវាង (Common Mistakes)៖\n❌ ខុស: Although he was tired, but he continued working.\n✅ ត្រូវ: Although he was tired, he continued working. (មាន Although ហើយ មិនប្រើ but ទៀតទេ)\n\n✍️ លំហាត់អនុវត្ត (Practice Exercise)៖\nចូរភ្ជាប់ប្រយោគទាំងពីរ៖ 'I like reading.' 'I like writing.'"
  },
  {
    "topic": "Conjunctions: because, so",
    "kh": "📖 និយមន័យ និងការប្រើប្រាស់ (Definition & Usage)៖\nBecause (ពីព្រោះ) បង្ហាញពី 'មូលហេតុ' (Reason)។ So (ដូច្នេះ) បង្ហាញពី 'លទ្ធផល' (Result)។\n\n📐 រូបមន្ត និងក្បួនវេយ្យាករណ៍ (Formulas & Rules)៖\n• Structure: Result + because + Reason (I passed because I studied hard.)\n• Structure: Reason + , so + Result (I studied hard, so I passed.)\n\n💡 ឧទាហរណ៍ជាក់ស្តែង & ការបកប្រែជាភាសាខ្មែរ (Practical Examples with Khmer Translation)៖\n1. 🇬🇧 She practices speaking every day because she wants to work for an international firm.\n   🇰🇭 (នាងហ្វឹកហាត់និយាយរាល់ថ្ងៃ ពីព្រោះនាងចង់ធ្វើការឱ្យក្រុមហ៊ុនអន្តរជាតិមួយ។)\n\n2. 🇬🇧 The weather was terrible with heavy rain, so the outdoor concert was canceled.\n   🇰🇭 (អាកាសធាតុគឺមិនល្អដោយសារភ្លៀងធ្លាក់ខ្លាំង ដូច្នេះការប្រគំតន្ត្រីក្រៅផ្ទះត្រូវបានលុបចោល។)\n\n3. 🇬🇧 He felt confident during the interview because he had prepared thoroughly.\n   🇰🇭 (គាត់មានអារម្មណ៍ជឿជាក់ក្នុងអំឡុងពេលសម្ភាសន៍ ពីព្រោះគាត់បានត្រៀមខ្លួនយ៉ាងហ្មត់ចត់។)\n\n⚠️ កំហុសញឹកញាប់ដែលត្រូវចៀសវាង (Common Mistakes)៖\n❌ ខុស: Because he was sick, so he didn't come. (ក្នុងភាសាអង់គ្លេស មិនប្រើ Because និង So ក្នុងប្រយោគតែមួយឡើយ!)\n✅ ត្រូវ: Because he was sick, he didn't come. (ឬ He was sick, so he didn't come.)\n\n✍️ លំហាត់អនុវត្ត (Practice Exercise)៖\nចូរជ្រើសរើស because ឬ so៖ 'I was tired, ___ I went to bed early.'"
  },
  {
    "topic": "Conjunctions: although, even though",
    "kh": "📖 និយមន័យ និងការប្រើប្រាស់ (Definition & Usage)៖\nAlthough និង Even though (ទោះបីជាយ៉ាងណាក៏ដោយ) ប្រើសម្រាប់បង្ហាញពីភាពផ្ទុយគ្នា និងការភ្ញាក់ផ្អើល (Concession & Contrast)។ Even though មានកម្រិតធ្ងន់ និងខ្លាំងជាង Although។\n\n📐 រូបមន្ត និងក្បួនវេយ្យាករណ៍ (Formulas & Rules)៖\nAlthough / Even though + Subject + Verb, Main Clause\n(ចំណាំ៖ មិនប្រើ 'but' នៅក្នុងប្រយោគដែលមាន Although ឡើយ)\n\n💡 ឧទាហរណ៍ជាក់ស្តែង & ការបកប្រែជាភាសាខ្មែរ (Practical Examples with Khmer Translation)៖\n1. 🇬🇧 Although the final exam was very challenging, all our students passed successfully.\n   🇰🇭 (ទោះបីជាការប្រឡងបញ្ចប់វគ្គមានការពិបាកខ្លាំងក៏ដោយ ក៏សិស្សានុសិស្សរបស់យើងទាំងអស់បានប្រឡងជាប់ដោយជោគជ័យ។)\n\n2. 🇬🇧 Even though she was extremely tired after work, she still completed her English lesson.\n   🇰🇭 (ទោះបីជានាងហត់នឿយខ្លាំងយ៉ាងណាក្តីក្រោយចេញពីធ្វើការ ក៏នាងនៅតែបំពេញមេរៀនភាសាអង់គ្លេសរបស់នាងរួចរាល់ដែរ។)\n\n3. 🇬🇧 He speaks English with great confidence although he only started learning six months ago.\n   🇰🇭 (គាត់និយាយភាសាអង់គ្លេសប្រកបដោយទំនុកចិត្តខ្ពស់ ទោះបីជាគាត់ទើបតែចាប់ផ្តើមរៀនបាន ៦ ខែក៏ដោយ។)\n\n⚠️ កំហុសញឹកញាប់ដែលត្រូវចៀសវាង (Common Mistakes)៖\n❌ ខុស: Although it rained, but we went out.\n✅ ត្រូវ: Although it rained, we went out.\n\n✍️ លំហាត់អនុវត្ត (Practice Exercise)៖\nចូរភ្ជាប់ប្រយោគដោយប្រើ 'Although'៖ 'He is rich. He is unhappy.'"
  },
  {
    "topic": "Relative Clauses: who, which, that",
    "kh": "📖 និយមន័យ និងការប្រើប្រាស់ (Definition & Usage)៖\nឈ្នាប់កថាខណ្ឌទំនាក់ទំនង ប្រើដើម្បីបញ្ជាក់លម្អិតអំពីនាម។ Who (សម្រាប់មនុស្ស), Which (សម្រាប់វត្ថុ ឬសត្វ), That (សម្រាប់ទាំងមនុស្ស និងវត្ថុក្នុង Defining Clauses)។\n\n📐 រូបមន្ត និងក្បួនវេយ្យាករណ៍ (Formulas & Rules)៖\n• Who: The teacher who taught me is very kind.\n• Which: The laptop which I bought is fast.\n• That: The car that won the race is red.\n\n💡 ឧទាហរណ៍ជាក់ស្តែង & ការបកប្រែជាភាសាខ្មែរ (Practical Examples with Khmer Translation)៖\n1. 🇬🇧 The dedicated instructor who teaches our advanced speaking course has ten years of experience.\n   🇰🇭 (លោកគ្រូដែលបង្រៀនវគ្គសន្ទនាកម្រិតខ្ពស់របស់យើង មានបទពិសោធន៍រហូតដល់ទៅ ១០ ឆ្នាំ។)\n\n2. 🇬🇧 This is the mobile application which has helped thousands of learners master English.\n   🇰🇭 (នេះគឺជាកម្មវិធីទូរស័ព្ទដែលបានជួយអ្នករៀនរាប់ពាន់នាក់ឱ្យចេះភាសាអង់គ្លេសយ៉ាងស្ទាត់ជំនាញ។)\n\n3. 🇬🇧 The scholarship that she applied for covers full tuition fees and accommodation.\n   🇰🇭 (អាហារូបករណ៍ដែលនាងបានដាក់ពាក្យស្នើសុំ រ៉ាប់រងថ្លៃសិក្សាពេញលេញ និងកន្លែងស្នាក់នៅ។)\n\n⚠️ កំហុសញឹកញាប់ដែលត្រូវចៀសវាង (Common Mistakes)៖\n❌ ខុស: The man which called you is my uncle.\n✅ ត្រូវ: The man who called you is my uncle. (មនុស្ស ត្រូវប្រើ who មិនមែន which ទេ)\n\n✍️ លំហាត់អនុវត្ត (Practice Exercise)៖\nចូរបំពេញ who ឬ which៖ 'The book ___ I read was fascinating.'"
  },
  {
    "topic": "Relative Clauses: whose, whom, where",
    "kh": "📖 និយមន័យ និងការប្រើប្រាស់ (Definition & Usage)៖\nWhose (កម្មសិទ្ធិ - របស់នរណា), Whom (កម្មបទមនុស្សក្នុងភាសាផ្លូវការ), Where (ទីកន្លែង - នៅឯណា)។\n\n📐 រូបមន្ត និងក្បួនវេយ្យាករណ៍ (Formulas & Rules)៖\n• Whose: The boy whose car was stolen.\n• Whom: The person whom I met yesterday.\n• Where: The city where I was born.\n\n💡 ឧទាហរណ៍ជាក់ស្តែង & ការបកប្រែជាភាសាខ្មែរ (Practical Examples with Khmer Translation)៖\n1. 🇬🇧 Siem Reap is the historic city where millions of international tourists visit every year.\n   🇰🇭 (ខេត្តសៀមរាប គឺជាទីក្រុងប្រវត្តិសាស្ត្រដែលភ្ញៀវទេសចរអន្តរជាតិរាប់លាននាក់មកទស្សនារៀងរាល់ឆ្នាំ។)\n\n2. 🇬🇧 The student whose English essay won the national competition was awarded a certificate.\n   🇰🇭 (សិស្សដែលតែងសេចក្តីភាសាអង់គ្លេសរបស់គាត់បានឈ្នះការប្រកួតថ្នាក់ជាតិ ត្រូវបានទទួលរង្វាន់វិញ្ញាបនបត្រ។)\n\n3. 🇬🇧 This is the study room where our online group discussions take place.\n   🇰🇭 (នេះគឺជាបន្ទប់សិក្សាដែលការពិភាក្សាក្រុមអនឡាញរបស់យើងប្រព្រឹត្តទៅ។)\n\n⚠️ កំហុសញឹកញាប់ដែលត្រូវចៀសវាង (Common Mistakes)៖\n❌ ខុស: The hotel which we stayed was very clean.\n✅ ត្រូវ: The hotel where we stayed was very clean. (ទីកន្លែងដែលស្នាក់នៅ ប្រើ where)\n\n✍️ លំហាត់អនុវត្ត (Practice Exercise)៖\nចូរបំពេញ where ឬ whose៖ 'The man ___ laptop was broken called the technician.'"
  },
  {
    "topic": "Passive Voice Present (ទម្រង់អកម្ម)",
    "kh": "📖 និយមន័យ និងការប្រើប្រាស់ (Definition & Usage)៖\nទម្រង់អកម្មបច្ចុប្បន្ន ប្រើនៅពេលផ្តោតលើអ្នករងអំពើជាជាងអ្នកធ្វើអំពើ។\n\n📐 រូបមន្ត និងក្បួនវេយ្យាករណ៍ (Formulas & Rules)៖\nFormula: Object + am / is / are + V3 (Past Participle) + (by Subject)\n\n💡 ឧទាហរណ៍ជាក់ស្តែង & ការបកប្រែជាភាសាខ្មែរ (Practical Examples with Khmer Translation)៖\n1. 🇬🇧 English is spoken by millions of business professionals across the globe.\n   🇰🇭 (ភាសាអង់គ្លេសត្រូវបាននិយាយដោយអ្នកជំនាញអាជីវកម្មរាប់លាននាក់នៅទូទាំងពិភពលោក។)\n\n2. 🇬🇧 All student certificates are officially verified and signed before graduation.\n   🇰🇭 (វិញ្ញាបនបត្រសិស្សទាំងអស់ត្រូវបានផ្ទៀងផ្ទាត់ និងចុះហត្ថលេខាជាផ្លូវការមុនពេលបញ្ចប់ការសិក្សា។)\n\n3. 🇬🇧 Fresh vegetables and fruits are delivered to the supermarket every morning.\n   🇰🇭 (បន្លែ និងផ្លែឈើស្រស់ៗត្រូវបានដឹកជញ្ជូនមកកាន់ផ្សារទំនើបរៀងរាល់ព្រឹក។)\n\n⚠️ កំហុសញឹកញាប់ដែលត្រូវចៀសវាង (Common Mistakes)៖\n❌ ខុស: The classroom is clean every day.\n✅ ត្រូវ: The classroom is cleaned every day. (កិរិយាសព្ទត្រូវតែជា V3 គឺ cleaned)\n\n✍️ លំហាត់អនុវត្ត (Practice Exercise)៖\nចូរប្តូរជា Passive Voice៖ 'They build new roads every year.'"
  },
  {
    "topic": "Passive Voice Past (ទម្រង់អកម្មអតីតកាល)",
    "kh": "📖 និយមន័យ និងការប្រើប្រាស់ (Definition & Usage)៖\nទម្រង់អកម្មអតីតកាល ប្រើសម្រាប់សកម្មភាពដែលបានទទួលរងអំពើក្នុងអតីតកាល។\n\n📐 រូបមន្ត និងក្បួនវេយ្យាករណ៍ (Formulas & Rules)៖\nFormula: Object + was / were + V3 (Past Participle) + (by Subject)\n\n💡 ឧទាហរណ៍ជាក់ស្តែង & ការបកប្រែជាភាសាខ្មែរ (Practical Examples with Khmer Translation)៖\n1. 🇬🇧 The ancient Angkor Wat temple was built during the 12th century.\n   🇰🇭 (ប្រាសាទអង្គរវត្តបុរាណត្រូវបានសាងសង់ឡើងក្នុងអំឡុងសតវត្សរ៍ទី ១២។)\n\n2. 🇬🇧 The important business partnership was finalized and signed last week.\n   🇰🇭 (ភាពជាដៃគូអាជីវកម្មដ៏សំខាន់ត្រូវបានបញ្ចប់ និងចុះហត្ថលេខាកាលពីសប្តាហ៍មុន។)\n\n3. 🇬🇧 These historical documents were discovered by archeologists in 1995.\n   🇰🇭 (ឯកសារប្រវត្តិសាស្ត្រទាំងនេះត្រូវបានរកឃើញដោយអ្នកបុរាណវិទ្យាក្នុងឆ្នាំ ១៩៩៥។)\n\n⚠️ កំហុសញឹកញាប់ដែលត្រូវចៀសវាង (Common Mistakes)៖\n❌ ខុស: The bridge was destroyed in 1970 by the flood.\n✅ ត្រូវ: The bridge was destroyed in 1970 by the flood. (ត្រូវប្រើ was + V3)\n\n✍️ លំហាត់អនុវត្ត (Practice Exercise)៖\nចូរប្តូរជា Passive Voice៖ 'Shakespeare wrote Hamlet.'"
  },
  {
    "topic": "Direct and Indirect Speech",
    "kh": "📖 និយមន័យ និងការប្រើប្រាស់ (Definition & Usage)៖\nការនិយាយផ្ទាល់ (Direct Speech) គឺការស្រង់ពាក្យសម្តីដើមមកនិយាយទាំងស្រុងដោយដាក់ក្នុងសញ្ញាសម្រង់ (\"...\")។ ការនិយាយដោយប្រយោល (Indirect / Reported Speech) គឺការនាំពាក្យសម្តីរបស់អ្នកដទៃមកនិយាយប្រាប់គេឡើងវិញ ដោយត្រូវថយ Tense មួយកម្រិត។\n\n📐 រូបមន្ត និងក្បួនវេយ្យាករណ៍ (Formulas & Rules)៖\n• Present Simple -> Past Simple: \"I am tired\" -> He said that he was tired.\n• Present Continuous -> Past Continuous: \"I am studying\" -> She said that she was studying.\n• Will -> Would: \"I will help\" -> He said he would help.\n\n💡 ឧទាហរណ៍ជាក់ស្តែង & ការបកប្រែជាភាសាខ្មែរ (Practical Examples with Khmer Translation)៖\n1. 🇬🇧 Direct: Sophea said, \"I want to improve my English speaking skills.\"\n   🇰🇭 (ផ្ទាល់៖ សុភាបាននិយាយថា៖ «ខ្ញុំចង់ពង្រឹងជំនាញនិយាយភាសាអង់គ្លេសរបស់ខ្ញុំ។»)\n\n2. 🇬🇧 Reported: Sophea said that she wanted to improve her English speaking skills.\n   🇰🇭 (ប្រយោល៖ សុភាបាននិយាយថានាងចង់ពង្រឹងជំនាញនិយាយភាសាអង់គ្លេសរបស់នាង។)\n\n3. 🇬🇧 Direct: The teacher said, \"The final examination will take place next Friday.\"\n   🇰🇭 (ផ្ទាល់៖ លោកគ្រូបានមានប្រសាសន៍ថា៖ «ការប្រឡងបញ្ចប់វគ្គនឹងប្រព្រឹត្តទៅនៅថ្ងៃសុក្រក្រោយ។»)\n\n4. 🇬🇧 Reported: The teacher announced that the final examination would take place the following Friday.\n   🇰🇭 (ប្រយោល៖ លោកគ្រូបានប្រកាសថាការប្រឡងបញ្ចប់វគ្គនឹងប្រព្រឹត្តទៅនៅថ្ងៃសុក្របន្ទាប់។)\n\n⚠️ កំហុសញឹកញាប់ដែលត្រូវចៀសវាង (Common Mistakes)៖\n❌ ខុស: He said that he is tired yesterday.\n✅ ត្រូវ: He said that he was tired. (កិរិយាសព្ទត្រូវថយទៅអតីតកាល was)\n\n✍️ លំហាត់អនុវត្ត (Practice Exercise)៖\nចូរប្តូរទៅ Reported Speech៖ 'Mary said, \"I like coffee.\"'"
  },
  {
    "topic": "Conditional Type 0 & 1",
    "kh": "📖 និយមន័យ និងការប្រើប្រាស់ (Definition & Usage)៖\nលក្ខខណ្ឌ Type 0 បង្ហាញពីការពិតវិទ្យាសាស្ត្រ (If + Present, Present)។ លក្ខខណ្ឌ Type 1 បង្ហាញពីស្ថានភាពជាក់ស្តែងដែលអាចកើតឡើងក្នុងអនាគត (If + Present, will + V1)។\n\n📐 រូបមន្ត និងក្បួនវេយ្យាករណ៍ (Formulas & Rules)៖\n• Type 0: If you freeze water, it turns into ice.\n• Type 1: If you practice every day, you will speak fluently.\n\n💡 ឧទាហរណ៍ជាក់ស្តែង & ការបកប្រែជាភាសាខ្មែរ (Practical Examples with Khmer Translation)៖\n1. 🇬🇧 If you heat ice, it melts into water instantly. (Scientific fact - Type 0)\n   🇰🇭 (ប្រសិនបើអ្នកកម្តៅដុំទឹកកក វានឹងរលាយទៅជាទឹកភ្លាមៗ។ (ការពិតវិទ្យាសាស្ត្រ - Type 0))\n\n2. 🇬🇧 If you study English consistently on StudyAI, you will pass your exam with high scores.\n   🇰🇭 (ប្រសិនបើអ្នករៀនភាសាអង់គ្លេសជាប្រចាំលើ StudyAI អ្នកនឹងប្រឡងជាប់ដោយទទួលបានពិន្ទុខ្ពស់។ (Type 1))\n\n3. 🇬🇧 If it rains tomorrow morning, we will conduct our speaking session via video call.\n   🇰🇭 (ប្រសិនបើមានភ្លៀងធ្លាក់នៅព្រឹកថ្ងៃស្អែក ពួកយើងនឹងរៀបចំវគ្គហ្វឹកហាត់និយាយតាមរយៈ Video Call។)\n\n⚠️ កំហុសញឹកញាប់ដែលត្រូវចៀសវាង (Common Mistakes)៖\n❌ ខុស: If it will rain, I will stay home.\n✅ ត្រូវ: If it rains, I will stay home. (ក្នុងឃ្លា If-clause មិនប្រើ will ឡើយ)\n\n✍️ លំហាត់អនុវត្ត (Practice Exercise)៖\nចូរបំពេញចន្លោះ៖ 'If you study hard, you (pass) ___ the test.'"
  },
  {
    "topic": "Conditional Type 2",
    "kh": "📖 និយមន័យ និងការប្រើប្រាស់ (Definition & Usage)៖\nលក្ខខណ្ឌ Type 2 ប្រើសម្រាប់និយាយអំពីស្ថានភាពសម្មតិកម្ម ស្រមើស្រមៃ ឬមិនពិតក្នុងពេលបច្ចុប្បន្ន (Unreal present situation)។\n\n📐 រូបមន្ត និងក្បួនវេយ្យាករណ៍ (Formulas & Rules)៖\nFormula: If + Past Simple (V2), Subject + would + V1\n(ចំណាំ៖ To Be ក្នុង If-clause ប្រើ 'were' សម្រាប់គ្រប់ Subject)\n\n💡 ឧទាហរណ៍ជាក់ស្តែង & ការបកប្រែជាភាសាខ្មែរ (Practical Examples with Khmer Translation)៖\n1. 🇬🇧 If I won a million dollars, I would build modern English schools across rural Cambodia.\n   🇰🇭 (ប្រសិនបើខ្ញុំឈ្នះប្រាក់មួយលានដុល្លារ ខ្ញុំនឹងសាងសង់សាលារៀនភាសាអង់គ្លេសទំនើបៗនៅទូទាំងជនបទនៃប្រទេសកម្ពុជា។)\n\n2. 🇬🇧 If I were in your position, I would take that great opportunity immediately.\n   🇰🇭 (ប្រសិនបើខ្ញុំស្ថិតក្នុងជំហររបស់អ្នក ខ្ញុំនឹងចាប់យកឱកាសដ៏អស្ចារ្យនោះភ្លាមៗ។ (ការផ្តល់ដំបូន្មាន))\n\n3. 🇬🇧 If we had more free time, we would travel around the world to practice English.\n   🇰🇭 (ប្រសិនបើពួកយើងមានពេលទំនេរច្រើនជាងនេះ ពួកយើងនឹងធ្វើដំណើរជុំវិញពិភពលោកដើម្បីហ្វឹកហាត់ភាសាអង់គ្លេស។)\n\n⚠️ កំហុសញឹកញាប់ដែលត្រូវចៀសវាង (Common Mistakes)៖\n❌ ខុស: If I was you, I would study harder.\n✅ ត្រូវ: If I were you, I would study harder. (ក្នុងភាសាផ្លូវការប្រើ were)\n\n✍️ លំហាត់អនុវត្ត (Practice Exercise)៖\nចូរបំពេញចន្លោះ៖ 'If I (have) ___ wings, I would fly.'"
  },
  {
    "topic": "Conditional Type 3",
    "kh": "📖 និយមន័យ និងការប្រើប្រាស់ (Definition & Usage)៖\nលក្ខខណ្ឌ Type 3 ប្រើសម្រាប់បង្ហាញពីការសោកស្តាយ ឬការស្រមើស្រមៃអំពីអ្វីមួយដែលបានកន្លងផុតទៅក្នុងអតីតកាល ហើយមិនអាចកែប្រែបានឡើយ (Unreal past / Regret)។\n\n📐 រូបមន្ត និងក្បួនវេយ្យាករណ៍ (Formulas & Rules)៖\nFormula: If + Past Perfect (had + V3), Subject + would have + V3\n\n💡 ឧទាហរណ៍ជាក់ស្តែង & ការបកប្រែជាភាសាខ្មែរ (Practical Examples with Khmer Translation)៖\n1. 🇬🇧 If I had enrolled in this online English academy earlier, I would have passed the scholarship interview.\n   🇰🇭 (ប្រសិនបើកាលនោះខ្ញុំបានចុះឈ្មោះរៀននៅសាលាភាសាអង់គ្លេសអនឡាញនេះលឿនជាងនេះ ខ្ញុំប្រហែលជាបានជាប់សម្ភាសន៍អាហារូបករណ៍បាត់ទៅហើយ។)\n\n2. 🇬🇧 If we had set off thirty minutes earlier, we wouldn't have missed our international flight.\n   🇰🇭 (ប្រសិនបើពួកយើងបានចេញដំណើរ ៣០ នាទីមុននេះ ពួកយើងច្បាស់ជាមិនខកជើងហោះហើរអន្តរជាតិនោះឡើយ។)\n\n3. 🇬🇧 She would have achieved a band 8.0 on IELTS if she had practiced writing more frequently.\n   🇰🇭 (នាងច្បាស់ជាទទួលបានពិន្ទុ 8.0 លើ IELTS ប្រសិនបើនាងបានហ្វឹកហាត់សរសេរឱ្យបានញឹកញាប់ជាងនេះ។)\n\n⚠️ កំហុសញឹកញាប់ដែលត្រូវចៀសវាង (Common Mistakes)៖\n❌ ខុស: If I had studied, I would passed.\n✅ ត្រូវ: If I had studied, I would have passed. (would have + V3)\n\n✍️ លំហាត់អនុវត្ត (Practice Exercise)៖\nចូរបំពេញចន្លោះ៖ 'If you had called me, I (help) ___ you.'"
  }
];
