const verbsList = {
  "A_C": [
    { v1: "arise",     v2: "arose",       v3: "arisen",      kh: "កើតឡើង, ចោះ" },
    { v1: "awake",     v2: "awoke",       v3: "awoken",      kh: "ភ្ញាក់ (ធ្វើឱ្យ)" },
    { v1: "be",        v2: "was/were",    v3: "been",        kh: "ជា, គឺ, នៅ" },
    { v1: "bear",      v2: "bore",        v3: "borne",       kh: "ទ្រទ្រង់, ចម្លង" },
    { v1: "beat",      v2: "beat",        v3: "beaten",      kh: "វាយ" },
    { v1: "become",    v2: "became",      v3: "become",      kh: "ក្លាយជា" },
    { v1: "begin",     v2: "began",       v3: "begun",       kh: "ចាប់ផ្តើម" },
    { v1: "bend",      v2: "bent",        v3: "bent",        kh: "បត់, ពត់" },
    { v1: "bet",       v2: "bet",         v3: "bet",         kh: "ភ្នាល់" },
    { v1: "bind",      v2: "bound",       v3: "bound",       kh: "ចង, ចងចាំ" },
    { v1: "bite",      v2: "bit",         v3: "bitten",      kh: "ខាំ" },
    { v1: "bleed",     v2: "bled",        v3: "bled",        kh: "ហូរឈាម" },
    { v1: "blow",      v2: "blew",        v3: "blown",       kh: "បក់, ផ្ទុះ" },
    { v1: "break",     v2: "broke",       v3: "broken",      kh: "បំបែក, បាក់" },
    { v1: "breed",     v2: "bred",        v3: "bred",        kh: "ចិញ្ចឹម, ប្រកបពូជ" },
    { v1: "bring",     v2: "brought",     v3: "brought",     kh: "នាំយកមក" },
    { v1: "broadcast", v2: "broadcast",   v3: "broadcast",   kh: "ផ្សាយ" },
    { v1: "build",     v2: "built",       v3: "built",       kh: "សាងសង់" },
    { v1: "burn",      v2: "burnt/burned",v3: "burnt/burned",kh: "ដុត, ឆេះ" },
    { v1: "burst",     v2: "burst",       v3: "burst",       kh: "ផ្ទុះ" },
    { v1: "buy",       v2: "bought",      v3: "bought",      kh: "ទិញ" },
    { v1: "cast",      v2: "cast",        v3: "cast",        kh: "បោះ, លើករូបភាព" },
    { v1: "catch",     v2: "caught",      v3: "caught",      kh: "ចាប់" },
    { v1: "choose",    v2: "chose",       v3: "chosen",      kh: "ជ្រើសរើស" },
    { v1: "cling",     v2: "clung",       v3: "clung",       kh: "ស្ទោះ, ស្ពឹក" },
    { v1: "come",      v2: "came",        v3: "come",        kh: "មក" },
    { v1: "cost",      v2: "cost",        v3: "cost",        kh: "មានតម្លៃ" },
    { v1: "creep",     v2: "crept",       v3: "crept",       kh: "rangles" },
    { v1: "cut",       v2: "cut",         v3: "cut",         kh: "កាត់" }
  ],
  "D_F": [
    { v1: "deal",      v2: "dealt",       v3: "dealt",       kh: "ដោះស្រាយ, លក់ដូរ" },
    { v1: "dig",       v2: "dug",         v3: "dug",         kh: "ជីក" },
    { v1: "do",        v2: "did",         v3: "done",        kh: "ធ្វើ" },
    { v1: "draw",      v2: "drew",        v3: "drawn",       kh: "គូរ, ទាញ" },
    { v1: "dream",     v2: "dreamt",      v3: "dreamt",      kh: "យល់សប្តិ" },
    { v1: "drink",     v2: "drank",       v3: "drunk",       kh: "ផឹក" },
    { v1: "drive",     v2: "drove",       v3: "driven",      kh: "បើកបរ" },
    { v1: "eat",       v2: "ate",         v3: "eaten",       kh: "ញ៉ាំ" },
    { v1: "fall",      v2: "fell",        v3: "fallen",      kh: "ធ្លាក់" },
    { v1: "feed",      v2: "fed",         v3: "fed",         kh: "ចិញ្ចឹម, ផ្តល់អាហារ" },
    { v1: "feel",      v2: "felt",        v3: "felt",        kh: "មានអារម្មណ៍" },
    { v1: "fight",     v2: "fought",      v3: "fought",      kh: "ប្រយុទ្ធ, ឈ្លោះ" },
    { v1: "find",      v2: "found",       v3: "found",       kh: "ស្វែងរកឃើញ" },
    { v1: "flee",      v2: "fled",        v3: "fled",        kh: "រត់គេច" },
    { v1: "fly",       v2: "flew",        v3: "flown",       kh: "ហោះ" },
    { v1: "forbid",    v2: "forbade",     v3: "forbidden",   kh: "ហាមឃាត់" },
    { v1: "forget",    v2: "forgot",      v3: "forgotten",   kh: "ភ្លេច" },
    { v1: "forgive",   v2: "forgave",     v3: "forgiven",    kh: "អត់ទោស" },
    { v1: "freeze",    v2: "froze",       v3: "frozen",      kh: "얼다, កកទឹក" }
  ],
  "G_L": [
    { v1: "get",       v2: "got",         v3: "got/gotten",  kh: "ទទួលបាន" },
    { v1: "give",      v2: "gave",        v3: "given",       kh: "ផ្តល់ឲ្យ" },
    { v1: "go",        v2: "went",        v3: "gone",        kh: "ទៅ" },
    { v1: "grind",     v2: "ground",      v3: "ground",      kh: "កិន, ពង្រាយ" },
    { v1: "grow",      v2: "grew",        v3: "grown",       kh: "លូតលាស់" },
    { v1: "hang",      v2: "hung",        v3: "hung",        kh: "ព្យួរ" },
    { v1: "have",      v2: "had",         v3: "had",         kh: "មាន" },
    { v1: "hear",      v2: "heard",       v3: "heard",       kh: "ឮ" },
    { v1: "hide",      v2: "hid",         v3: "hidden",      kh: "លាក់" },
    { v1: "hit",       v2: "hit",         v3: "hit",         kh: "វាយ" },
    { v1: "hold",      v2: "held",        v3: "held",        kh: "កាន់" },
    { v1: "hurt",      v2: "hurt",        v3: "hurt",        kh: "ធ្វើឲ្យឈឺ" },
    { v1: "keep",      v2: "kept",        v3: "kept",        kh: "រក្សាទុក" },
    { v1: "kneel",     v2: "knelt",       v3: "knelt",       kh: "ជង្គុក" },
    { v1: "knit",      v2: "knit/knitted",v3: "knit/knitted",kh: "짜다, ប្រតិបត្តិ" },
    { v1: "know",      v2: "knew",        v3: "known",       kh: "ដឹង, ស្គាល់" },
    { v1: "lay",       v2: "laid",        v3: "laid",        kh: "ដាក់ (ផ្ដេក)" },
    { v1: "lead",      v2: "led",         v3: "led",         kh: "ដឹកនាំ" },
    { v1: "lean",      v2: "leant/leaned",v3: "leant/leaned",kh: "ទ្រ, ត្រសេះ" },
    { v1: "leap",      v2: "leapt/leaped",v3: "leapt/leaped",kh: "លោត" },
    { v1: "learn",     v2: "learnt/learned",v3: "learnt/learned",kh: "រៀន" },
    { v1: "leave",     v2: "left",        v3: "left",        kh: "ចាកចេញ" },
    { v1: "lend",      v2: "lent",        v3: "lent",        kh: "ឲ្យខ្ចី" },
    { v1: "let",       v2: "let",         v3: "let",         kh: "អនុញ្ញាត" },
    { v1: "lie",       v2: "lay",         v3: "lain",        kh: "ដេក, ដេករំ" },
    { v1: "light",     v2: "lit",         v3: "lit",         kh: "បំភ្លឺ" },
    { v1: "lose",      v2: "lost",        v3: "lost",        kh: "បាត់, ចាញ់" }
  ],
  "M_R": [
    { v1: "make",      v2: "made",        v3: "made",        kh: "ធ្វើ, បង្កើត" },
    { v1: "mean",      v2: "meant",       v3: "meant",       kh: "មានន័យ" },
    { v1: "meet",      v2: "met",         v3: "met",         kh: "ជួប" },
    { v1: "mow",       v2: "mowed",       v3: "mown/mowed",  kh: "កាស់ (ស្មៅ)" },
    { v1: "overcome",  v2: "overcame",    v3: "overcome",    kh: "យកឈ្នះ" },
    { v1: "overtake",  v2: "overtook",    v3: "overtaken",   kh: "抢先, ជ្រៀតចូល" },
    { v1: "pay",       v2: "paid",        v3: "paid",        kh: "បង់ប្រាក់" },
    { v1: "prove",     v2: "proved",      v3: "proved/proven",kh: "បញ្ជាក់, ពិសោធ" },
    { v1: "put",       v2: "put",         v3: "put",         kh: "ដាក់" },
    { v1: "quit",      v2: "quit",        v3: "quit",        kh: "ឈប់, លា" },
    { v1: "read",      v2: "read",        v3: "read",        kh: "អាន" },
    { v1: "ride",      v2: "rode",        v3: "ridden",      kh: "ជិះ" },
    { v1: "ring",      v2: "rang",        v3: "rung",        kh: "រោទិ៍" },
    { v1: "rise",      v2: "rose",        v3: "risen",       kh: "ឡើង, រះ (ព្រះអាទិត្យ)" },
    { v1: "run",       v2: "ran",         v3: "run",         kh: "រត់" }
  ],
  "S_Z": [
    { v1: "say",       v2: "said",        v3: "said",        kh: "និយាយ" },
    { v1: "see",       v2: "saw",         v3: "seen",        kh: "ឃើញ" },
    { v1: "seek",      v2: "sought",      v3: "sought",      kh: "ស្វែងរក" },
    { v1: "sell",      v2: "sold",        v3: "sold",        kh: "លក់" },
    { v1: "send",      v2: "sent",        v3: "sent",        kh: "ផ្ញើ" },
    { v1: "set",       v2: "set",         v3: "set",         kh: "ដាក់, កំណត់" },
    { v1: "shake",     v2: "shook",       v3: "shaken",      kh: "ញ័រ, ដើរ" },
    { v1: "shed",      v2: "shed",        v3: "shed",        kh: "ដេញ, បោះចោល" },
    { v1: "shine",     v2: "shone",       v3: "shone",       kh: "ចាំង, ចែង" },
    { v1: "shoot",     v2: "shot",        v3: "shot",        kh: "បាញ់" },
    { v1: "show",      v2: "showed",      v3: "shown",       kh: "បង្ហាញ" },
    { v1: "shrink",    v2: "shrank",      v3: "shrunk",      kh: "រួញ" },
    { v1: "shut",      v2: "shut",        v3: "shut",        kh: "បិទ" },
    { v1: "sing",      v2: "sang",        v3: "sung",        kh: "ច្រៀង" },
    { v1: "sink",      v2: "sank",        v3: "sunk",        kh: "លិច" },
    { v1: "sit",       v2: "sat",         v3: "sat",         kh: "អង្គុយ" },
    { v1: "sleep",     v2: "slept",       v3: "slept",       kh: "គេង" },
    { v1: "slide",     v2: "slid",        v3: "slid",        kh: "រអិល, ចុះ" },
    { v1: "smell",     v2: "smelt/smelled",v3: "smelt/smelled",kh: "ក្លិន" },
    { v1: "speak",     v2: "spoke",       v3: "spoken",      kh: "និយាយ" },
    { v1: "spell",     v2: "spelt/spelled",v3: "spelt/spelled",kh: "ប្រកប" },
    { v1: "spend",     v2: "spent",       v3: "spent",       kh: "ចំណាយ" },
    { v1: "spill",     v2: "spilt/spilled",v3: "spilt/spilled",kh: "ឆក់ (ទឹក)" },
    { v1: "spin",      v2: "spun",        v3: "spun",        kh: "វិល, ក្ម្រ" },
    { v1: "spread",    v2: "spread",      v3: "spread",      kh: "រីករាល, ផ្សព្វ" },
    { v1: "spring",    v2: "sprang",      v3: "sprung",      kh: "លោត, ងើប" },
    { v1: "stand",     v2: "stood",       v3: "stood",       kh: "ឈរ" },
    { v1: "steal",     v2: "stole",       v3: "stolen",      kh: "លួច" },
    { v1: "stick",     v2: "stuck",       v3: "stuck",       kh: "ជាប់, ចូចចូល" },
    { v1: "sting",     v2: "stung",       v3: "stung",       kh: "ចឹក (ដំបូក)" },
    { v1: "stink",     v2: "stank",       v3: "stunk",       kh: "ម៉ូ, ក្លិនស្អុយ" },
    { v1: "strike",    v2: "struck",      v3: "struck/stricken",kh: "វាយ, ផ្ទះ" },
    { v1: "strive",    v2: "strove",      v3: "striven",     kh: "ខិតខំ" },
    { v1: "swear",     v2: "swore",       v3: "sworn",       kh: "សំបោរ, ស្ប" },
    { v1: "sweep",     v2: "swept",       v3: "swept",       kh: "បោស" },
    { v1: "swim",      v2: "swam",        v3: "swum",        kh: "ហែលទឹក" },
    { v1: "swing",     v2: "swung",       v3: "swung",       kh: "ហួច, ហួញ" },
    { v1: "take",      v2: "took",        v3: "taken",       kh: "យក" },
    { v1: "teach",     v2: "taught",      v3: "taught",      kh: "បង្រៀន" },
    { v1: "tear",      v2: "tore",        v3: "torn",        kh: "ហែក" },
    { v1: "tell",      v2: "told",        v3: "told",        kh: "ប្រាប់" },
    { v1: "think",     v2: "thought",     v3: "thought",     kh: "គិត" },
    { v1: "throw",     v2: "threw",       v3: "thrown",      kh: "បោះ, ចោល" },
    { v1: "understand",v2: "understood",  v3: "understood",  kh: "យល់" },
    { v1: "upset",     v2: "upset",       v3: "upset",       kh: "ជ្រួតជ្រើម, ខ្ចាប" },
    { v1: "wake",      v2: "woke",        v3: "woken",       kh: "ភ្ញាក់" },
    { v1: "wear",      v2: "wore",        v3: "worn",        kh: "ពាក់" },
    { v1: "weave",     v2: "wove",        v3: "woven",       kh: "ត" },
    { v1: "weep",      v2: "wept",        v3: "wept",        kh: "យំ" },
    { v1: "win",       v2: "won",         v3: "won",         kh: "ឈ្នះ" },
    { v1: "wind",      v2: "wound",       v3: "wound",       kh: "រ៉ូត, រ៉ូ" },
    { v1: "withdraw",  v2: "withdrew",    v3: "withdrawn",   kh: "ដកថយ, ដកប្រាក់" },
    { v1: "write",     v2: "wrote",       v3: "written",     kh: "សរសេរ" }
  ]
};

module.exports = verbsList;
