const verbsList = {
  "A_C": [
    { v1: "be", v2: "was/were", v3: "been", kh: "ជា, គឺ, នៅ" },
    { v1: "beat", v2: "beat", v3: "beaten", kh: "វាយ" },
    { v1: "become", v2: "became", v3: "become", kh: "ក្លាយជា" },
    { v1: "begin", v2: "began", v3: "begun", kh: "ចាប់ផ្តើម" },
    { v1: "bite", v2: "bit", v3: "bitten", kh: "ខាំ" },
    { v1: "break", v2: "broke", v3: "broken", kh: "បំបែក, បាក់" },
    { v1: "bring", v2: "brought", v3: "brought", kh: "នាំយកមក" },
    { v1: "build", v2: "built", v3: "built", kh: "សាងសង់" },
    { v1: "buy", v2: "bought", v3: "bought", kh: "ទិញ" },
    { v1: "catch", v2: "caught", v3: "caught", kh: "ចាប់" },
    { v1: "choose", v2: "chose", v3: "chosen", kh: "ជ្រើសរើស" },
    { v1: "come", v2: "came", v3: "come", kh: "មក" },
    { v1: "cost", v2: "cost", v3: "cost", kh: "មានតម្លៃ" },
    { v1: "cut", v2: "cut", v3: "cut", kh: "កាត់" }
  ],
  "D_F": [
    { v1: "do", v2: "did", v3: "done", kh: "ធ្វើ" },
    { v1: "draw", v2: "drew", v3: "drawn", kh: "គូរ" },
    { v1: "dream", v2: "dreamt", v3: "dreamt", kh: "យល់សប្តិ" },
    { v1: "drink", v2: "drank", v3: "drunk", kh: "ផឹក" },
    { v1: "drive", v2: "drove", v3: "driven", kh: "បើកបរ" },
    { v1: "eat", v2: "ate", v3: "eaten", kh: "ញ៉ាំ" },
    { v1: "fall", v2: "fell", v3: "fallen", kh: "ធ្លាក់" },
    { v1: "feel", v2: "felt", v3: "felt", kh: "មានអារម្មណ៍" },
    { v1: "fight", v2: "fought", v3: "fought", kh: "ប្រយុទ្ធ, ឈ្លោះ" },
    { v1: "find", v2: "found", v3: "found", kh: "ស្វែងរកឃើញ" },
    { v1: "fly", v2: "flew", v3: "flown", kh: "ហោះ" },
    { v1: "forget", v2: "forgot", v3: "forgotten", kh: "ភ្លេច" }
  ],
  "G_L": [
    { v1: "get", v2: "got", v3: "got/gotten", kh: "ទទួលបាន" },
    { v1: "give", v2: "gave", v3: "given", kh: "ផ្តល់ឲ្យ" },
    { v1: "go", v2: "went", v3: "gone", kh: "ទៅ" },
    { v1: "grow", v2: "grew", v3: "grown", kh: "លូតលាស់" },
    { v1: "have", v2: "had", v3: "had", kh: "មាន" },
    { v1: "hear", v2: "heard", v3: "heard", kh: "ឮ" },
    { v1: "hide", v2: "hid", v3: "hidden", kh: "លាក់" },
    { v1: "hit", v2: "hit", v3: "hit", kh: "វាយ" },
    { v1: "hold", v2: "held", v3: "held", kh: "កាន់" },
    { v1: "hurt", v2: "hurt", v3: "hurt", kh: "ធ្វើឲ្យឈឺ" },
    { v1: "keep", v2: "kept", v3: "kept", kh: "រក្សាទុក" },
    { v1: "know", v2: "knew", v3: "known", kh: "ដឹង, ស្គាល់" },
    { v1: "leave", v2: "left", v3: "left", kh: "ចាកចេញ" },
    { v1: "lose", v2: "lost", v3: "lost", kh: "បាត់, ចាញ់" }
  ],
  "M_R": [
    { v1: "make", v2: "made", v3: "made", kh: "ធ្វើ, បង្កើត" },
    { v1: "meet", v2: "met", v3: "met", kh: "ជួប" },
    { v1: "pay", v2: "paid", v3: "paid", kh: "បង់ប្រាក់" },
    { v1: "put", v2: "put", v3: "put", kh: "ដាក់" },
    { v1: "read", v2: "read", v3: "read", kh: "អាន" },
    { v1: "ride", v2: "rode", v3: "ridden", kh: "ជិះ" },
    { v1: "ring", v2: "rang", v3: "rung", kh: "រោទិ៍" },
    { v1: "run", v2: "ran", v3: "run", kh: "រត់" }
  ],
  "S_W": [
    { v1: "say", v2: "said", v3: "said", kh: "និយាយ" },
    { v1: "see", v2: "saw", v3: "seen", kh: "ឃើញ" },
    { v1: "sell", v2: "sold", v3: "sold", kh: "លក់" },
    { v1: "send", v2: "sent", v3: "sent", kh: "ផ្ញើ" },
    { v1: "show", v2: "showed", v3: "shown", kh: "បង្ហាញ" },
    { v1: "sing", v2: "sang", v3: "sung", kh: "ច្រៀង" },
    { v1: "sit", v2: "sat", v3: "sat", kh: "អង្គុយ" },
    { v1: "sleep", v2: "slept", v3: "slept", kh: "គេង" },
    { v1: "speak", v2: "spoke", v3: "spoken", kh: "និយាយ" },
    { v1: "spend", v2: "spent", v3: "spent", kh: "ចំណាយ" },
    { v1: "stand", v2: "stood", v3: "stood", kh: "ឈរ" },
    { v1: "swim", v2: "swam", v3: "swum", kh: "ហែលទឹក" },
    { v1: "take", v2: "took", v3: "taken", kh: "យក" },
    { v1: "teach", v2: "taught", v3: "taught", kh: "បង្រៀន" },
    { v1: "tell", v2: "told", v3: "told", kh: "ប្រាប់" },
    { v1: "think", v2: "thought", v3: "thought", kh: "គិត" },
    { v1: "understand", v2: "understood", v3: "understood", kh: "យល់" },
    { v1: "wake", v2: "woke", v3: "woken", kh: "ភ្ញាក់" },
    { v1: "wear", v2: "wore", v3: "worn", kh: "ពាក់" },
    { v1: "win", v2: "won", v3: "won", kh: "ឈ្នះ" },
    { v1: "write", v2: "wrote", v3: "written", kh: "សរសេរ" }
  ]
};

module.exports = verbsList;
